---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Asia/Novosibirsk"
  CLUSTER_DOMAIN: "xinfra.ru"
  POSTGRES_HOST: "lab-postgres-rw.database.svc.cluster.local"
