apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 30m
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - "status"
          - "metadata.generation"
          - "metadata.managedFields"
          - "metadata.annotations"
        target:
          kind: "*"
  releaseName: flux-operator
  chartRef:
    kind: OCIRepository
    name: flux-operator
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
