---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespaces/
- storage/
- traefik/namespace.yaml
- traefik/traefik-helmrelease.yaml
- traefik/tlsoption-strictverify.yaml
- flux-operator-ingress.yaml
- flux-operator-source.yaml
- flux-operator-helmrelease.yaml
