---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard
  namespace: flux-system
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: k8s/apps/adguard
      sourceRef:
        kind: GitRepository
        name: apps-charts
        namespace: flux-system
      interval: 1h
  releaseName: adguard
  targetNamespace: apps-adguard
  values:
    auth:
      enabled: true
      existingSecret: adguard-admin-creds
    ingress:
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: kube-system-crowdsec-bouncer@kubernetescrd
