---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: database
spec:
  interval: 10m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.29.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  values:
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lab-postgres
  namespace: database
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname

  primaryUpdateStrategy: unsupervised

  storage:
    storageClass: longhorn
    size: 10Gi

  walStorage:
    storageClass: longhorn
    size: 5Gi

  bootstrap:
    initdb:
      database: app_db
      owner: app_user

  postgresql:
    parameters:
      shared_buffers: "256MB"
      max_connections: "100"

  monitoring:
    enablePodMonitor: true
