---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: excalidraw
  namespace: apps-excalidraw
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: excalidraw
      sourceRef:
        kind: HelmRepository
        name: excalidraw
        namespace: flux-system
      interval: 1h
  releaseName: excalidraw
  targetNamespace: apps-excalidraw
  values:
    excalidraw:
      ingress:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: kube-system-crowdsec-bouncer@kubernetescrd,apps-excalidraw-forwardauth-authelia@kubernetescrd
        host: excalidraw.xinfra.ru
        path: /
        type: Prefix
        tls:
          secretName: wildcard-xinfra-ru-tls
          host: excalidraw.xinfra.ru
