---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: developer-tools
spec:
  interval: 10m
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - "/status"
          - "/metadata/generation"
          - "/metadata/managedFields"
          - "/metadata/annotations"
        target:
          kind: ".*"
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: k8s/apps/forgejo
      sourceRef:
        kind: GitRepository
        name: apps-charts
        namespace: flux-system
      interval: 1h
  values:
    extraEnv:
      - name: TZ
        value: Asia/Novosibirsk
      - name: FORGEJO__database__PASSWD
        valueFrom:
          secretKeyRef:
            name: forgejo-db-secret
            key: password
      - name: FORGEJO__SESSION__PROVIDER_CONFIG
        value: redis://forgejo-valkey.developer-tools.svc.cluster.local:6379/1?pool_size=100&idle_timeout=180s
      - name: FORGEJO__QUEUE__CONN_STR
        value: redis://forgejo-valkey.developer-tools.svc.cluster.local:6379/2?pool_size=100&idle_timeout=180s
      - name: FORGEJO__CACHE__HOST
        value: redis://forgejo-valkey.developer-tools.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s

    forgejo:
      replicaCount: 1

      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        capabilities:
          drop:
            - ALL

      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 2000m
          memory: 1536Mi

      persistence:
        claimName: forgejo-storage-rwo
        size: 10Gi
        accessModes:
          - ReadWriteOnce
        storageClass: "longhorn"

      extraVolumes:
        - name: custom-templates
          configMap:
            name: forgejo-custom-templates
      extraContainerVolumeMounts:
        - name: custom-templates
          mountPath: /data/gitea/templates/home.tmpl
          subPath: home.tmpl

      gitea:
        config:
          database:
            DB_TYPE: postgres
            HOST: lab-postgres-rw.database.svc.cluster.local:5432
            NAME: forgejo
            USER: forgejo
          session:
            PROVIDER: redis
            PROVIDER_CONFIG: redis://forgejo-valkey.developer-tools.svc.cluster.local:6379/1?pool_size=100&idle_timeout=180s
          queue:
            TYPE: redis
            CONN_STR: redis://forgejo-valkey.developer-tools.svc.cluster.local:6379/2?pool_size=100&idle_timeout=180s
          cache:
            ADAPTER: redis
            HOST: redis://forgejo-valkey.developer-tools.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s
          server:
            LFS_START_SERVER: true
          lfs:
            ENABLED: true

    valkey:
      resources:
        requests:
          cpu: 15m
          memory: 64Mi
        limits:
          cpu: 2000m
          memory: 256Mi
      persistence:
        storageClassName: "longhorn"

    ingress: {}
