---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
  namespace: apps-forgejo-runner
spec:
  interval: 5m
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - "/status"
          - "/metadata/generation"
          - "/metadata/managedFields"
          - "/metadata/annotations"
        target:
          kind: ".*"
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: forgejo-runner
      sourceRef:
        kind: HelmRepository
        name: forgejo-runner
        namespace: flux-system
      interval: 1h
  releaseName: forgejo-runner
  targetNamespace: apps-forgejo-runner
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: forgejo-runner
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  name: dind-sock
                  mountPath: /var/run
              - op: add
                path: /spec/template/spec/containers/1/volumeMounts/-
                value:
                  name: dind-sock
                  mountPath: /var/run
              - op: add
                path: /spec/template/spec/containers/1/args
                value:
                  - "--mtu=1450"
              - op: add
                path: /spec/template/spec/containers/1/lifecycle
                value:
                  postStart:
                    exec:
                      command:
                        - /bin/sh
                        - -c
                        - "for i in $(seq 1 10); do iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1410 2>/dev/null && break || sleep 1; done"
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: dind-sock
                  emptyDir: {}
  values:
    knownLastVersion: true
    runner:
      config:
        create: true
        existingInitSecret: forgejo-runner-init
        instance: http://forgejo-http.apps-forgejo.svc.cluster.local:3000
        file:
          runner:
            capacity: 1
            envs: {}
            labels:
              - "ubuntu-latest:docker://catthehacker/ubuntu:act-latest"
          container:
            privileged: true
            docker_host: ""
            options: "-v /var/run/docker.sock:/var/run/docker.sock"
            valid_volumes:
              - '**'

    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 2000m
        memory: 3072Mi
    dind:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 3072Mi
