---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: apps-forgejo
spec:
  interval: 5m
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - "/status"
          - "/metadata/generation"
          - "/metadata/managedFields"
          - "/metadata/annotations"
        target:
          kind: ".*"
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: k8s/apps/forgejo
      sourceRef:
        kind: GitRepository
        name: apps-charts
        namespace: flux-system
      interval: 1h
  releaseName: forgejo
  targetNamespace: apps-forgejo
  values:
    extraEnv:
      - name: TZ
        value: Asia/Novosibirsk
      - name: FORGEJO__database__PASSWD
        valueFrom:
          secretKeyRef:
            name: forgejo-db-secret
            key: password
    forgejo:
      replicaCount: 2
      persistence:
        claimName: forgejo-shared-storage-rwx
        size: 10Gi
        accessModes:
          - ReadWriteMany
        storageClass: "longhorn"
      gitea:
        config:
          database:
            DB_TYPE: postgres
            HOST: lab-postgres-rw.database.svc.cluster.local:5432
            NAME: forgejo
            USER: forgejo
          server:
            LFS_START_SERVER: true
          lfs:
            ENABLED: true
    valkey:
      persistence:
        storageClassName: "longhorn"
    ingress: {}
