---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: apps-forgejo
spec:
  interval: 5m
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - "status"
          - "metadata.generation"
          - "metadata.managedFields"
          - "metadata.annotations"
        target:
          kind: ".*"
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: k8s/apps/forgejo
      sourceRef:
        kind: GitRepository
        name: apps-charts
        namespace: flux-system
      interval: 1h
  releaseName: forgejo
  targetNamespace: apps-forgejo
  values:
    forgejo:
      persistence:
        storageClass: "longhorn"
    valkey:
      persistence:
        storageClassName: "longhorn"
    extraEnv:
      - name: TZ
        value: Asia/Novosibirsk
    ingress: {}
