apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gloria
  namespace: apps
spec:
  interval: 5m
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - "/status"
          - "/metadata/generation"
          - "/metadata/managedFields"
          - "/metadata/annotations"
        target:
          kind: ".*"
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: .helm
      sourceRef:
        kind: GitRepository
        name: gloria
        namespace: flux-system
      interval: 1h
  values:
    image:
      repository: zot.xinfra.ru/gloria
      tag: "0.1.0"
      pullPolicy: Always
    imagePullSecrets:
      - name: zot-reader
    collector:
      existingSecret: gloria-config
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: gloria.xinfra.ru
          paths:
            - path: /login/confirm
              pathType: Prefix
            - path: /login
              pathType: Prefix
      tls:
        - secretName: wildcard-xinfra-ru-tls
          hosts:
            - gloria.xinfra.ru
