---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- authelia.yaml
- authelia-ingressroute.yaml
- zot.yaml
- crowdsec.yaml
- crowdsec-bouncer-middleware.yaml
- vikunja.yaml
- vaultwarden.yaml
- adguard.yaml
- dozzle.yaml
- excalidraw.yaml
- forgejo.yaml
- kube-prometheus-stack.yaml
- lldap.yaml
- locust.yaml
- gickup.yaml
- goldilocks.yaml
- ntfy.yaml
- supersync.yaml
- mailu.yaml
- mailu-ingressroute-tcp.yaml
- longhorn.yaml
