---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- adguard.yaml
- authelia.yaml
- cnpg-databases.yaml
- cnpg.yaml
- dozzle.yaml
- forgejo-custom-templates.yaml
- forgejo-runner.yaml
- forgejo.yaml
- forgesync.yaml
- gloria.yaml
- goldilocks.yaml
- kube-prometheus-stack.yaml
- lldap.yaml
- locust.yaml
- longhorn.yaml
- ntfy.yaml
- pgadmin.yaml
- pvcs.yaml
- supersync.yaml
- twitch-bot.yaml
- vaultwarden.yaml
- xray.yaml
- zot.yaml
