---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
      version: v1.12.0
  interval: 1m0s
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - "/status"
          - "/metadata/generation"
          - "/metadata/managedFields"
          - "/metadata/annotations"
        target:
          kind: ".*"
  releaseName: longhorn
  targetNamespace: longhorn-system
  install:
    timeout: 20m0s
  upgrade:
    timeout: 20m0s
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.xinfra.ru
      path: /
      pathType: Prefix
      tls: true
      tlsSecret: wildcard-xinfra-ru-tls
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: longhorn-system-forwardauth-authelia@kubernetescrd,longhorn-system-longhorn-buffering@kubernetescrd
        traefik.ingress.kubernetes.io/router.tls.options: traefik-mtls-strict@kubernetescrd
