---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: 1.12.0


  interval: 1m0s
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - "/status"
          - "/metadata/generation"
          - "/metadata/managedFields"
          - "/metadata/annotations"
        target:
          kind: ".*"
  install:
    timeout: 20m0s
  upgrade:
    timeout: 20m0s
  values:
    ingress:
      enabled: false
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 3
    defaultSettings:
      defaultReplicaCount: 3
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.xinfra.ru`)
      kind: Rule
      middlewares:
        - name: forwardauth-authelia
          namespace: longhorn-system
        - name: longhorn-buffering
          namespace: longhorn-system
      services:
        - kind: Service
          name: longhorn-frontend
          namespace: longhorn-system
          passHostHeader: true
          port: 80
  tls:
    options:
      name: mtls-strict
      namespace: networking
    secretName: wildcard-xinfra-ru-tls
