---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-bf2b7fb6-80e2-4262-8797-42f55160f149
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-2c9c41df-eb1c-4605-a543-14b94372af45
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data-vaultwarden-0
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 15Gi
  volumeName: pvc-53d1a4a8-093a-4c3a-871f-2bb3507a2a01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-files-vaultwarden-0
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 15Gi
  volumeName: pvc-9d9dbfc8-1faa-4c52-b7e5-3fb0537327d4
