---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vikunja
  namespace: flux-system
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: vikunja
      sourceRef:
        kind: HelmRepository
        name: vikunja
        namespace: flux-system
      interval: 1h
  releaseName: vikunja
  targetNamespace: apps-vikunja
  values:
    vikunja:
      image:
        pullPolicy: Always
        tag: "2.3.0"
      env:
        TZ: Asia/Novosibirsk
      configMaps:
        config:
          enabled: false
      resources:
        requests:
          cpu: 15m
          memory: 100Mi
        limits:
          memory: 192Mi
      persistence:
        config:
          enabled: true
          type: secret
          name: vikunja-config
        data:
          enabled: true
          accessMode: ReadWriteOnce
          size: 10Gi
          mountPath: /app/vikunja/files
      ingress:
        main:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: kube-system-crowdsec-bouncer@kubernetescrd
          hosts:
            - host: vikunja.xinfra.ru
              paths:
                - path: /
          tls:
            - hosts:
                - vikunja.xinfra.ru
              secretName: wildcard-xinfra-ru-tls
