---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  releaseName: reflector
  chart:
    spec:
      chart: reflector
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
      interval: 1h
  targetNamespace: reflector
  values:
    replicaCount: 1

    image:
      pullPolicy: Always

    extraEnv:
      - name: TZ
        value: Asia/Novosibirsk

    configuration:
      logging:
        minimumLevel: Information

    rbac:
      enabled: true

    serviceAccount:
      create: true

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 512Mi
