---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: reflector
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
      interval: 1h
  install:
    namespace: reflector
    createNamespace: true
  targetNamespace: reflector
  values:
    replicaCount: 1

    configuration:
      logging:
        minimumLevel: Information

    rbac:
      enabled: true

    serviceAccount:
      create: true

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 300m
        memory: 128Mi
