apiVersion: v1
kind: Secret
metadata:
    name: adguard-admin-creds
    namespace: apps-adguard
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:k2s4oOalNw==,iv:GtGUGDq7doRvBhVcumN22hkZWL2F5nVrUp4yQuLBulA=,tag:yGIwr2Y85gM5quTdId/pew==,type:str]
    password: ENC[AES256_GCM,data:Jyx7pemioqYO,iv:bJN/A5k/CZpWOtnBuw/iIsmu2jXGP3I2Bl3zNz03eKE=,tag:9qrX3t173O3PTvNHiCTnCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUzlhZkdHQ1pMUU9IeGxT
            aXhrVjVXYjREeUlRcXAxN0kxUXpuRElLTEVRCkNhYTgyWmZHaXg2Wk5TMUpCa21W
            Ym1EMkJ5N3hkOEpEVDdvUFQzbWVQcjgKLS0tIFFEemNtR3dOcU9pemhmcjlmcUFV
            ek16SlhDOVNNY1JscXpqQnYvYXpLNFkKYktP24ykrjoXjj++/E4MWMI4ZpDvi3oK
            HvWZWHLSQgArqtVv9ir0OLNboMBPJaoFt9dnyDpMVhmVZEQeTyLesw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T18:09:45Z"
    mac: ENC[AES256_GCM,data:oxS1V8or7c+VQGUSOBpgveT7762YKTMObCPCBNApEXG7Jt6FjkQnFbsrwjlaSw6yBNUYiFn56xTvOGa2zkyek83OiYXSdJR/BlvFLZV4f1AeQip4Fz0cXqUA9+x2F9rIujTFZZfzucrD1qLKOS7jo7lw3KkBlThk2jeFeGnagLY=,iv:A9XFLOTDwm1zQIa1MRvr1TLLE06Cytgde1JCdhucr/U=,tag:bgkfnTW01dE15PBVWraSXg==,type:str]
    version: 3.13.1
