apiVersion: v1
kind: Secret
metadata:
    name: adguard-admin-creds
    namespace: networking
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:1pNE6TW2pQ==,iv:zdu/fqkUAD99VjOGlrjTMRN3fZQnwUEpctoczzEQTaY=,tag:4pQa+Sw4tbU9y7yWES74jw==,type:str]
    password: ENC[AES256_GCM,data:Ek4OfEcBY28F,iv:EjWxPxg6kCqUNIKePO08imhZqMfANS4963scnBpEwUw=,tag:5Gq2oFrMra6/PgW30+uRsQ==,type:str]
    #ENC[AES256_GCM,data:n/73No4MM4njvFfo41bgEQOMvnJGz1L9Jack5Qrzo6d2Svn7QPW0DbyYiVuQ1m2u23sOK5WbHbTF+iqE+7SQ0kqXitXXQQ==,iv:Eu6S9MMYm10cmj2KyVfOmvNzEZJ2gJp1MzPJhqbpGWw=,tag:0Qf+TNlcwoWKFYFhYKZk9A==,type:comment]
    password_hash: ENC[AES256_GCM,data:lgcq7EFyTYvETdLxqKuEO8FGLg9MnGZUQ1dXRvRCjKlJ1NUl8hHMSZCOpOzbMCnjFsdekJF7AUV8EaJO,iv:AV2TQNPPfN1rkS0CP4Xss/wwWC9tnn3ivGBs+Ug/giI=,tag:HssNZCssjnNZUptDPxHAJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOEFlN1o3YVNoZ1JJK0JE
            RmJ3S0dxZC9YdU5IZXgwSWhsdUkwdWpsTm13CmtPSWtCVmpCMFhvT1BMUkl5U0xF
            V3E5dmFrT3VhN0IxQkxIQWxqRTlVaEUKLS0tIGx5VEg3Z2s2THEvQWdJU1NvY0pv
            NURncGsyLzMwKytFaWlyVXQwODBnZjAKApX6u6OgL0TsmKysPJdbJRgohpcae6xr
            wRMkFGM8bGbseggf+F7Tif87xrj4CNLXcIzKoR31WggtddcxKS+/Uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T04:53:34Z"
    mac: ENC[AES256_GCM,data:cjPoUKRRFGGwczFU2F5Tn8nHhubRf2dztaY4Ct5Tf7FwI7ic1D8GyNyaYRLGKSQV9oyDLDYAuNpRpp2U5RdgLAjaysmF7cemKfwkM8fgQG25AsDNPb8eHOQFpqxOW21QhkVfX2XwZeTU34J3xH7d7Egf4/8wGJr5ZADu2jy3qiM=,iv:tQEINyipzx2d+6TEKgGkGcSNKVcAipTztXGvBXNXNO8=,tag:tTE9kts3UGnqCkYK0Dwq1A==,type:str]
    version: 3.13.1
