apiVersion: v1
kind: Secret
metadata:
    name: adguard-admin-creds
    namespace: apps-adguard
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:1pNE6TW2pQ==,iv:zdu/fqkUAD99VjOGlrjTMRN3fZQnwUEpctoczzEQTaY=,tag:4pQa+Sw4tbU9y7yWES74jw==,type:str]
    password: ENC[AES256_GCM,data:Ek4OfEcBY28F,iv:EjWxPxg6kCqUNIKePO08imhZqMfANS4963scnBpEwUw=,tag:5Gq2oFrMra6/PgW30+uRsQ==,type:str]
    #ENC[AES256_GCM,data:n/73No4MM4njvFfo41bgEQOMvnJGz1L9Jack5Qrzo6d2Svn7QPW0DbyYiVuQ1m2u23sOK5WbHbTF+iqE+7SQ0kqXitXXQQ==,iv:Eu6S9MMYm10cmj2KyVfOmvNzEZJ2gJp1MzPJhqbpGWw=,tag:0Qf+TNlcwoWKFYFhYKZk9A==,type:comment]
    password_hash: ENC[AES256_GCM,data:lgcq7EFyTYvETdLxqKuEO8FGLg9MnGZUQ1dXRvRCjKlJ1NUl8hHMSZCOpOzbMCnjFsdekJF7AUV8EaJO,iv:AV2TQNPPfN1rkS0CP4Xss/wwWC9tnn3ivGBs+Ug/giI=,tag:HssNZCssjnNZUptDPxHAJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOEFlN1o3YVNoZ1JJK0JE
            RmJ3S0dxZC9YdU5IZXgwSWhsdUkwdWpsTm13CmtPSWtCVmpCMFhvT1BMUkl5U0xF
            V3E5dmFrT3VhN0IxQkxIQWxqRTlVaEUKLS0tIGx5VEg3Z2s2THEvQWdJU1NvY0pv
            NURncGsyLzMwKytFaWlyVXQwODBnZjAKApX6u6OgL0TsmKysPJdbJRgohpcae6xr
            wRMkFGM8bGbseggf+F7Tif87xrj4CNLXcIzKoR31WggtddcxKS+/Uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T19:52:23Z"
    mac: ENC[AES256_GCM,data:HbLHJypqvicDT3fxMuxf0y9kb4D2MpZVPMPRurRWgFsc5qx0tvv6sVKgba7rJPUaFI+ZbPa6G8zlxfooeZrpZ9oX+7JUNmXSWnZOD77PXSBabJ/jmICk47EIS6beNCNb+nidGWAsyTduyCP8nGFpkZ+kmWN118NE7iaU/4GDQR4=,iv:dPgADxhCFrdhzOz9Fa60b+jxPBH8TY5G0XA/yoEUoCg=,tag:auqtEvRoVKkQ/w7namgu2g==,type:str]
    version: 3.13.1
