apiVersion: v1
data:
    web-config.yaml: ""
kind: Secret
metadata:
    name: alertmanager-kube-prometheus-stack-alertmanager-web-config
    namespace: monitoring
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aFNUbTNMeThmVEQyVFJX
            WTlodFBOenh0ZmVOVEZ4VC9rVll4ZFNyU1UwCm8weDVsaENkamF1VDA0cGRkMVBY
            RTNlRFczVTE3eU85T3Z4clhqektPd3cKLS0tIHBuOWdjc01CQXVPYkxkLzdFUmpx
            TGdtTjJxNm05K01hd293ZVRQYWV5WjAKW8E6A0mESEu7MqVBNCU2X5JQfG+TAt5G
            MGZDJlLF854jAeJx8fcmXx4vMGR/i7s7fkIMtVUj6dTjd0c4MQs2yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T03:45:35Z"
    mac: ENC[AES256_GCM,data:Mt+TnV2umjB4zdXXuotY8wVSN7+v0PYSriAWeNmSS78IDF37lmjDImQnnpdV5s998bBIX7rBEJpD7tFU3Lz6OEd7ScVQXGSArfHnO+3cFrb7MGVH+f+NQ4ssZQA2ItQfZDW4xl6ozk2fghp/GYvkXg9SxvduDAZVY40u7a2DzjE=,iv:2Uwd5pr8CciRyjFqo9nidbBly29kHvZaALppmEoLrWg=,tag:kaRzAJucG/rH6rvtV1k0kg==,type:str]
    version: 3.13.2
