---
apiVersion: v1
data:
    token: ENC[AES256_GCM,data:0kTBzlzsOGgoOugFS58QpLCMl90DCzXtMbdnhHRv7Ou4z443gULNWURxLFo=,iv:SsJQKIbHDutcZqkTCOJxWMdeFv+DYtQmWWz12of2qXw=,tag:FlNabmWCisE8/MnbG/jW9w==,type:str]
kind: Secret
metadata:
    name: alertmanager-ntfy-token
    namespace: apps-kube-prometheus-stack
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aEw1dThoS3laNUt1TmJO
            eGU5MFBNN0x3N0hjTy9vVm9WY1h3aWlEN0JRCnBGajQ2dU9EUWhMMVJyQmhXN3Jj
            UnpMaXJVY0tqOGRTQ2gxazNtazlXWDgKLS0tIHl3VlgyQlM4WWs3dlhESllLMHRn
            MENjTmRxMm8zSmlVakxCcXowaW9pdGcKagahWSLNiwAo2LPQeyybhhJAwZsTws8r
            YqRydhob/uSo3sZm8PLg8TnmklOiJTW996q6r+WLyBM5LmAW21t1Zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:23:00Z"
    mac: ENC[AES256_GCM,data:UeqeXqLEdmnYhj33nl8yV6/F5H7xxkabA+i3rMdDygRM3Zhrb+G8bDWgyZO+dAS+k8s8iqensGmFQUA1ZJKbxsy92m6sjbac8TSWcGHVghs6Bb+c7iF4TK1K/3CMMx1OSMJVFeH3THMAUUMsLioPW538lr6K99g/1+FDuYhFVg4=,iv:4TOBooc6x06oW2LVoKBdP0YLcb157H4nEI7hAWqzcnU=,tag:pBeyLknn0ERt3DEc3lmcMw==,type:str]
    version: 3.13.1
