apiVersion: v1
data:
    cluster-tls-config.yaml: ""
kind: Secret
metadata:
    name: alertmanager-kube-prometheus-stack-alertmanager-cluster-tls-config
    namespace: monitoring
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eHlEQWtFajBRWHljQ1NJ
            ZGVabGNNU3d3QnFudW55UGl4U01DRDd0dlJzCmNLWHJBMGpTRG4xRlA1elp2RGZ2
            SUlFQnNtRXNiMWdCSWdicWZ2cWxjTTQKLS0tIFJOVlFxWGRFWG9WOVNhQnZtaWZo
            UGk5T2szZEhwMHkvd2U0NWtTaU5mK2cK8tJk1j/wlZnU5BmeweX/Ag/9T0eUAZJs
            UbInI4mmElr3+OZTJiqk03ln2aagqIQbEazgjUYPwNdbI2GrmrlMyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T03:45:34Z"
    mac: ENC[AES256_GCM,data:K2YDLLhVkcw5i+PKDB3rXuwv3Uqpimv6RRzqu+XdFA2DXjMCnfImeJI9DssEX81gQcVLjUOF5x6nlThcZcsHZd9jaJgA9TqDsiYjOdP8FdPxHQY+hsjSofd2SPWhQZ200uju7+x+7kHN0wC//a6xCl0eo3ZdV54vx5uS6ftOwGM=,iv:LvgN4IH3+5mL6P4iDuRTVvYTKAMcdmiaUqwGCn447to=,tag:CoauBwxpAUnN4mDTnDROcg==,type:str]
    version: 3.13.2
