apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy-token
    namespace: apps-kube-prometheus-stack
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:SRsDlgi3QHz2VQFk8gxd/OOIOAcEKs2kV19pP7eoVAc=,iv:dqGjcYEaECMiaPXdktfzwPCvgoa7J3Gsph1Aa7B+YhI=,tag:1gnwQ+OasLS7EKjOZDS4yA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaem05cEttb2VORG1tbkdH
            N1ExbkxtaWNRTGdzZXMyQ0d5Y3ZRV0dLOTBRCmY2K0I2eG82OVRPVmU0R2FFbVZW
            alRDcm95a1RDbXN3L1ByS2NVd25JUGMKLS0tIE5YRmhTaEdWWDl0bG1kWStOWGhy
            cHdvN2lSSG96VHYrTURmVkNrRE9aeWcKymQRTsQd8yquHAKZxKM6cZGAN4ZV+dKi
            beIAGgTRYnK1AOR+my7YFXJ0BGYw69nLS8Y4br/aAEo1kyltlpvJrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T18:29:07Z"
    mac: ENC[AES256_GCM,data:TrFnAtPMSguMHq0i1HjwG14ar/xgXYHsJbMaAMNREkbzU+NgDMF+FFSXv44L706Jpeup74TL6U977H8kXnubeHdqr+uV5wAjTg7ASiLqDH/aetR2OPRhwOqloAuT1Z+QyxHDvKD8TA2ODAaF975PAsjnLYGRlofGi8NvS0RxBXw=,iv:xSy5ctAijHpeuN2QPA2ZQEJvfhIvKMwIhDLabfBDqoY=,tag:4b66r8GL4+pALBMgGj4Jqw==,type:str]
    version: 3.13.1
