apiVersion: v1
kind: Secret
metadata:
    creationTimestamp: "2026-05-28T14:50:24Z"
    labels:
        app.kubernetes.io/managed-by: prometheus-operator
        managed-by: prometheus-operator
    name: alertmanager-kube-prometheus-stack-alertmanager-tls-assets-0
    namespace: apps-kube-prometheus-stack
    ownerReferences:
        - apiVersion: monitoring.coreos.com/v1
          blockOwnerDeletion: true
          controller: true
          kind: Alertmanager
          name: kube-prometheus-stack-alertmanager
          uid: 5db978c4-e893-4eb7-a1db-7371ce3593d2
    resourceVersion: "1544747"
    uid: 80f5ce74-bcde-4598-8776-73de37667ff1
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYUdicUxJL3J2b2ozVVB5
            ZXhTbWVSMU1vOUJyYk1PY2Q0ckVRUDRYbzBNCjdGdDNSeElBODJFR0NSSVYxd0FJ
            V0ZEN0JrMElGbjVYUjcxTTNETE4xNUEKLS0tIGxFOTNCcmpOMjdCQTA0SnFsUFV3
            c1hZWWptcXUyaTJNWkZnSjJxaVVhWEEKMHUeKGTZpdutgR7jA7q7MVhKsLkO/QYT
            MkCJwC+wf0y3FYb8th6mGVJkHioc9TNwOByskCkvgJXb+7nfqk/cBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T16:16:56Z"
    mac: ENC[AES256_GCM,data:5lGCzKeFjn3SKfp0H37H/+htu8MhUhtburFJlh8+IQLbjdgBk3iSg+Paie+4JGuq4tzN0F3Z194Wn9av/YLa+Wf9SFC71kZVyBHn2eJLDbDDRIY+quA7fMQ2ClzyLrMNqzsAJamRk1govF+0WgXyh0F/8VCTUDlwSthGDH2blAg=,iv:EGBvJ3jIuA9Mbeak+R40nq1OV1q5brFJyx8ekq3dj/Y=,tag:xw4b76OrGyULcBBr6gyRxQ==,type:str]
    version: 3.13.1
