apiVersion: v1
data:
    cluster-tls-config.yaml: ""
kind: Secret
metadata:
    name: alertmanager-kube-prometheus-stack-alertmanager-cluster-tls-config
    namespace: apps-kube-prometheus-stack
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOWJ0cHFEV1lUTnNqVjAw
            dlRFMmNPYy9vYnREYU5kRHROay9ndnU4RUVNCnBRbjFLMFJuT2RkU1kyOGVQVGN6
            cUV6dDhVL3dEbjB2ZG1mRW9IbGQ5TlEKLS0tIEcxOW1Lb2tvWlZFZFlkUVBJcE14
            MTNnRzNjQzFvemlxRVZraEhYWmV6QXcKyrm36eLRWFAtZ8VtzK4kW1dWH4V/oJ0B
            mqIV4x5gVJiWUt9QODo+DNipvo1ifGNsb2BCEMViZ5dtZlCEKjWVhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:01:24Z"
    mac: ENC[AES256_GCM,data:64zkOk2nr1dSvh8EUw1eve7JZeD2nAuXtpNyqzaVSeHxBoNYBR9I10uNsd7M/UV0sVGfW/IvW+eBIO2WjEjQZ+/Bo60ZoOwqCw4RasHW2hSNYY1z5V1gj0rp6aCxKvAfBGdD2VpM+J5Pxy3U59bLW5vBpP5hoof3u17DKz8xoWQ=,iv:upmzBGupKqbzs368093v7aznfasfr9St2MdvcYTY5OE=,tag:CTG+e6qdUg6udk5WueWs6w==,type:str]
    version: 3.13.1
