apiVersion: v1
data:
    alertmanager.yaml.gz: ENC[AES256_GCM,data:cCMeoiiftPZBkPD8ZbFKg1aB78Ge5WCPftFOyE48JVQrHCMrH2wDk4ymAtJfZFmv+t3XIPZGrO0x9j17gomEwyM6MLFLaVHTRbez3g5lJr+zmNed587rOMzuMMldT6EegmKv9ZGttAwezV6q/sj/OTYYMaruZYaS4LFhlZ6WDjd9qnRqQZXZQV7cRcSqjtWW2rxuLLX0db85aNkU2yKqnvdUNZkUNecyf/e1mI13i50MXgdPCyIKy6XcFvsGw5KwgcXwkNrXMS8Qcqs0b8nLCRUt4IK9okkrcfpp8AliAIwSnq1IZXCX1ykqb4QO14b2MStgA73SHwwme7/yqD0zxV5CuoOR9ytTGj9OOTIsOqvYN0iskFiYbxuvc/jU6TP6GHHz+G9LuNQLNYChLhJZuQUOuu+VFQgZZSSOqdh6b3TTTruZtr6rn7+XXeMtVswWVll1fRa3/5YD60d/N65CkBD4oXkapNgPz7QLgNjNBUogURUfgcTb5bTFyWODOcbFc95EpSZ+Hws78BLiPB6P6ef9CIn5Oyk3U8Y58nGayVExWdOIrimjcYzNh2dMbj+Ggpry6tbJU61NnQMMnjGgc4vxLks+R3/u4zSe5fCEwFh6XWjdux1LMW/quXIxshN6E5GoFC68HHIgC/YmNXCS5kJ9wmpmJzdk,iv:2pdKg9UtTMGF/2LQzS67KPqJQW+7jHcjhwfF93Fs8KA=,tag:tVMhghZ1IvZvBYC8LomocQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-05-28T14:50:24Z"
    labels:
        app.kubernetes.io/managed-by: prometheus-operator
        managed-by: prometheus-operator
    name: alertmanager-kube-prometheus-stack-alertmanager-generated
    namespace: apps-kube-prometheus-stack
    ownerReferences:
        - apiVersion: monitoring.coreos.com/v1
          blockOwnerDeletion: true
          controller: true
          kind: Alertmanager
          name: kube-prometheus-stack-alertmanager
          uid: 5db978c4-e893-4eb7-a1db-7371ce3593d2
    resourceVersion: "1694976"
    uid: 88bb34e1-2d1b-4731-8b75-45fada8353a1
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMWRSNDJUejVIZDhuRHpB
            THBVZmhrcnhyRmM4TU9hbVNDWFNjd1FkQ1I4Clh1d1JBclJTZmg0WDRNU0U5VnNT
            cmlsd3hQRkpiQ2tsd3VGSEFaRHBnUWMKLS0tIGtxZ3FaeFJ3N1k2US9HdEhtSHpZ
            NDFSdHR2b2xPL0luTUlwSFNXbGllWUkK38bS4A13nR3+i9PM97HFh/AZvG8dZ5A3
            MMmRlUPXY81DJqh31fmcd/+eLWZix5/BCOqL2GeifwN+BTBTU1orDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T16:16:56Z"
    mac: ENC[AES256_GCM,data:38g9x5469IMWqJ/XOurnXMORp7KHe49pfzLsZsvFwVx57+TrpVPcp6Sm0uoqh8+tWnVDD99r68lFfxrYQSMXvLKVj+8yn9qEQGq3Vo+gtze49jBxtj8Gd1ooUWJZxcCrsNHgQQ4FiwVfC3Y0m6Ek8b9hQVroZ9zGv866eSd98Hk=,iv:TGOZnLs5/Te6KNk1Qjv2TIFYR68FjFkNkUwlzVw7qRk=,tag:Hj95O89vjWaFp7JVfS3UlQ==,type:str]
    version: 3.13.1
