apiVersion: v1
data:
    web-config.yaml: ""
kind: Secret
metadata:
    name: alertmanager-kube-prometheus-stack-alertmanager-web-config
    namespace: apps-kube-prometheus-stack
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQXU2bTcrZC9zZm9yOTI0
            REdqV1ZhZTBmRVY1ZDEwUXVmbG00RksxeDFFCjlVejBmN0hoMEZoT2lpQmd4a1JK
            QnUxZ0ZjckE5My9mRnlzMXA2Sk84alkKLS0tIElpaFBDL2NubitsUnZWSmRsVkQr
            RHgxS0lKVXVEYjVnWmoyN01nUStVNW8KeKefMZknoSbMD3OupHovZHbWSWcg/LE/
            q632jCNXtn/fvjy74kbTAo4omiLOOOb8V561qgfsk1klgOX7lwSweQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:23:00Z"
    mac: ENC[AES256_GCM,data:/XdefYMHJIteZDbM1Rc5yCB4wE3FzhZbJnHOlkpwFsoYlCzcZAoXE/tn3TRagNaJCtDgWiNZyCskFA/mKPlWGWSausqdHKF/+ssvC8GPNpWQtt1ae9h/HNgy/W3TLcbPhueypeFBXuvPsVzg/dIix7xJqi5dokXlES5IN29NHPU=,iv:TK5umEcNXJBOgY3bpiayVRJ1+BhMbb0cvxyY3zrjeKU=,tag:IcqwTt8NWCqLfPBMIf3NYQ==,type:str]
    version: 3.13.1
