apiVersion: v1
data:
    cluster-tls-config.yaml: ""
kind: Secret
metadata:
    creationTimestamp: "2026-05-28T14:50:24Z"
    labels:
        app.kubernetes.io/managed-by: prometheus-operator
        managed-by: prometheus-operator
    name: alertmanager-kube-prometheus-stack-alertmanager-cluster-tls-config
    namespace: apps-kube-prometheus-stack
    ownerReferences:
        - apiVersion: monitoring.coreos.com/v1
          blockOwnerDeletion: true
          controller: true
          kind: Alertmanager
          name: kube-prometheus-stack-alertmanager
          uid: 5db978c4-e893-4eb7-a1db-7371ce3593d2
    resourceVersion: "1544753"
    uid: 8faffc8d-63f8-4811-a08b-c6ba56664423
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdUV0TitWeFdqT1luTHpC
            a2pxdDd0UnlsaGdIcTI0akpjTUNoWGx6TEJnClJ1QU8zaEsrVmpJaml2emxlclRB
            UmZTYWUrU25Uak05QXBNaUJMSDJiTUEKLS0tIDlOZlZOdS9HZVlEMVRRdGxIWkNo
            WUZFdWNyM3hqR0pLRTBRZXZYUldjOVUK6hl8q4qwWRftZB4JxMGS0GyY39mouNmW
            OfAKEejP/SxM7CGh5RpJH6WKjmO24h/MRti6V0rWSvxEuRjGOSqMSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T16:16:56Z"
    mac: ENC[AES256_GCM,data:KENY5eVIE7lKF4kEMu9v3k1XA2VXZlU8VxvOhYV0hL/7lpgF93Hj9eiaBYKX5iN49Fg2n53QVXTkpUFHfsVbzC8YjKYKbA4BDJyML5vPOMTCIEbPKh5lI8+79C4wzMq7DCI8E6O92GF3voAu+xRgz32BT2XybIKeSQ5jlFBuX2s=,iv:D/EMB3d70R5x1WA6QjDp/yRGxLsd9970rHGmMMWfIiY=,tag:MAZ75B4fY15WIcyPcj81Kg==,type:str]
    version: 3.13.1
