{
	"data": "ENC[AES256_GCM,data:hzzVUsDKGQ3coeRDsgSSlIXlNWzB1haM6jkEVmDwHgW4LWOweajP7QUo9W3jb5f+iZzYpCUHTP8KAWeQVOTJ+9SScTRqNLui3siJf2LyQhUhmsgJhLRpmwayIa5nQLoMnynw/BY56Fzs4OLKZ+hT/vvLlewJ+k2Q6FQh7mTe8aAHYIEgyyngSVaLFLW3Wj9yzeCIW6unAOXDbOdeHzmdjQDJ7LnyacDiB7iVFWwtIxpQFcYp8wtTKxo1CdVUvflYSyAGL+8aQ+KiSKtmnElHw/sEgNjYvjsHeuFEya7iTTyA4A3SzXUAfrhZXCEFmhcz3MfBKfTtEIu4tlPcQV6IvfPfmNlPZYekVJU3tL+KSzaNsd4iOhL8FZrK7CE6SGLZQdpEoq27xqgqGPwB/rMxuhw5+P5RJn+djYdMoEkFZ5l5KE1XxNkKBS+uEoCNd1J3cCZCMjTCqw5rbpxOXVA8p2Kp+6jwcKClCn5XDVCK3raH/w8+FDnb9fLy4ACJwRxcfryijlu/fXlFJnSm5OWTWh61VX1aQp3ZBx/9ntxH/1TgiPBKOcWnI/FCBZZkxpVSA7YMqTuvf/WSZuJQFUnkO6er3kpTJcpQRpEKqAnkaua0CrICWoTMI24VK05IOaSwvn0z9nNGBuMPl4w2htSd7nuuYLP6qnUobzYMW8QdGxAw9LZRwa009EH5w8plBTAZrHPKWfA3XVMBgT3rRhjOx+71Ju81TYvRw6BNW66fl1mdy6NCYBdYuYfTX6NaEFmLtLHyRHVJxQ==,iv:rXZKUQsvj5SSdkGdDg8v68aQ4mB8pQFD4yHpR3qXVBQ=,tag:7BqDQGT7bxx/3RnSSFa8Wg==,type:str]",
	"sops": {
		"age": [
			{
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNmpKT2VpSS85bFp2eVFQ\naERpWkxoVm82V0E5THpvVk82bTh2emtPZGdrCnk2REV3VEMvOXhHZXo3TFlWQmd5\nZXNzZUR0MFJzbGRJa2VIZzlObDJXTE0KLS0tIFJvUnA0b2VMZEtsa3U3NVg1dUIy\nOXZ2Rjd5T1R3OStVRkZyTGlaNGl5NGMKEDKuYqISc5TF+34yh7AXai1Vvd854VOw\nLSkRHPtxLNaXSc2E4JGRjBNKC0Tb0DE3UpgK5RAR0G9akc1ANpmnOA==\n-----END AGE ENCRYPTED FILE-----\n",
				"recipient": "age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0"
			}
		],
		"lastmodified": "2026-06-19T16:14:39Z",
		"mac": "ENC[AES256_GCM,data:YCkVYoUxkBqCORAK9/ANWWBW90gueU6ACuYdzHNumNKpOJEDYnQGg1cE2rEYjt09C7fEfsWcY7Ra13AMT457jrphDLzuyMAapWgQvExReb3P2o4Z1WBwGJn1yaz1zGVjRd30+UW0Q6R3k0T2qTlMIdXKVzlYI6wKAXvVGBXRCgI=,iv:z/lS44+P4MhtOJNw7jujMtFatmuaxNFSWmUz2qU55Fw=,tag:qDTRAgB3Tgf+FAY9GyENkw==,type:str]",
		"version": "3.13.1"
	}
}
