apiVersion: v1
data:
  alertmanager.yaml.gz: ENC[AES256_GCM,data:5xs+thIw9aVBwDAWHElRNBqLb9dmKPq8p8kmdIsmdxz7prWhfT7fY0qZzVdhCj9OkYPXR/XUwSw7hgOKsQK7yA12ma7vXln5xT5JZ1EC0obVTXfjJMCdsv44oHaITzt3e/hx6lmwETv6nwD1RQQO66xHyJ9PBdnwrO5B9AALTm9x0IoXOSOXwRacxTkZuJfskjXjDSZ2CAdWJxZ9BLigCGxHORUmvAa5F5h5RzjbH2UnJnSULhHw/jU0hEx1vRp8kRonksplYz+lCFcsk0Uaaj1TUTy+o8WihGZJjbAfBWDuKlfFqneZBJAqfmcBGGk8icajosjIHhb9cqoRSn7Wscz3D+ZvpAMVAHzpVh1ZwvXzo/ytg52C1ZSKARvatmNfZUMLq1CvObmbM+JF5+yrlR8/y+0yOIJ7ztbZ4lMinI4nD1RaMVirTRTIMyc9HbAiBmcZn1sjYUb1mUF8F0sKbD5ERT7E681B2WaH1BD66gvHayuYEz4pljHoLEMSbRrNtt+MDGE5TyUgejyfWOqA8hd6J+sroOZNxbdQSmCBp0jj9DfmjsfuLB9j7KGQUtLvQ7T3nPupaj3MhhchLQjlVXY9wtiD7TBlV7XyMXfHlHSG7vLwUHh1Io+79ItLV/oaf6N3gZpkIer4gah8Gd0XMKpT5KFIMAlX,iv:/F1GXElXEeUmKAaHfnPjqovaoF7xu4UzJAkdDzzGcDQ=,tag:JFWaj9P7XjaXVHm0SrUZmA==,type:str]
kind: Secret
metadata:
  creationTimestamp: '2026-05-28T14:50:24Z'
  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    managed-by: prometheus-operator
  name: alertmanager-kube-prometheus-stack-alertmanager-generated
  namespace: apps-kube-prometheus-stack
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Alertmanager
    name: kube-prometheus-stack-alertmanager
    uid: 5db978c4-e893-4eb7-a1db-7371ce3593d2
  resourceVersion: '1694976'
  uid: 88bb34e1-2d1b-4731-8b75-45fada8353a1
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYUlSRWxleVJiZEs3Nm0v

      dFRmRklFOW5RMDk2ZFhqYy8wcU5saXdDUzNVClo0NmswbEgvdklBalNsc3ZEaG9t

      NkV3RU5WOTBnSy81b1Fkc05IZHg2b3MKLS0tIDJMUUJxbGZmNVdmdzdnNFNwWU1O

      NmV0N1A4L3lxZ2JKUWFWOXdZZkdYcDgKEHqpGVwnED59Nnvo8RJtpKY1v8KLiUdx

      dJTqSiGHZAHBUHgo3EgfHB/uHdJgAk95rW0ub+KEVuTZCHLZxZ6UZA==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-06-19T10:57:28Z'
  mac: ENC[AES256_GCM,data:jmMeIWbP4D52aYFbV4gd5srZ9EH/raWqbPZ+JOICbQG+Mai1sw/T3lqcLilbHyB1P7GgWX1rGPaHHclNtAtk0Rjka2Tkgz/ZRWbK+2Ez5LBUXUdBGii2DHF+KTE2bBmV8Qu7PU6jKXBJwkq2Y/GIbI+WGkvW8TLnov2ALCoXQXw=,iv:rmC8fDANft/GoV9sxxQO+JfYBnp70x7Xn9Av8DsHCJA=,tag:W/mvTRJNeZEdsF9UVJrCmg==,type:str]
  version: 3.13.1
type: Opaque
