apiVersion: v1
kind: Secret
metadata:
    name: supersync-secret
    namespace: apps
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:vg4uam8t5jdhS/G3U1jFyxtAIKeF7OkKwHK05k55zyIER7pd7gf97QG91nkMtXVGnSLM2x4pOZEnixWfYDCUbg==,iv:x31vc4t3yq/vOnadkYENIRbJvxBbn+BnMT2eLAsoEjA=,tag:/XVfuVcyzGgDvqi9FuaSyQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:STq1ySvhcSMBKphsvBfWbfkzswprZu93Eh3izfG121BeeQJq1AdpWALvfn2wi1LHV51knsv41HHAIefNs7Reqwjbpxn6Ygnc4zt+RHtVm4ZRwNBj6Si7DEOgFQ==,iv:zoikAdPNAbJPRmON4plbfjXSBLiPM0kInmbGTLXuofA=,tag:Zku6um8dqBLwhIy9dzX3oA==,type:str]
    password: ENC[AES256_GCM,data:0Xjn1MBHZHkoaW9v/RbgmuwM9gyV+KK1qR5GwXGZJS8=,iv:ONw1GEU9b8tEJD1nv0PUdVKiizRedd8Zc8M28t3tGLk=,tag:3vZlftdXzpWl3O6+ZC717g==,type:str]
    postgres-password: ENC[AES256_GCM,data:dxd1TVz67wD1xEx25VtQ2mr+ir92/6p58UQyA5SrWFE=,iv:q6LhCcw8FxNCzNsjA0iBHRhV5Zp6vNe8lFxBmwvYxK8=,tag:h5ng1D1BuYDkY3XAs16Ing==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcCsvbkpOY2xBN3NCQ1BZ
            T0Y3MnRSWkhtYTJLTjMvU2U1YnJnNm5mMXlJCnRBSE9jN1B1N2NhVHlvYUpDQ1Ba
            c3NtL21QcURncnljTnhwYVQrVUk1ZkUKLS0tIDNWSitqQytKem5Wak9CbXBLdTRK
            ZDZ0dzZMYnlqRmxRVkUzNy9jeFhCM1UKvYqqO1VnCeMmtf2M/Jba/bG0ZnKspLHz
            mULVZWQtvMXTG2ArtPh2infn6HvgB8eZFzQM/ZPykrrS5TpSuIgBbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T10:55:27Z"
    mac: ENC[AES256_GCM,data:iFi7FWYWBOltUbu1h+vGSWGqp7lfPsEDBOnN8F76F6ZVw+KGUDIJFMsYxxsNokB/qorrvimfz11tzlCr5xeEsSVSQuX9sqd4g47L1d68EH0Hw542f8tgLPuUXjxyFqY9taEMYRXGOdQBeZ7qt680/vNrUKzLDXfaOt4wpRcndu8=,iv:YXttbe/Q2+fTF8tZMC7tRld3qr6Dkmzw7TLkjj6hPUw=,tag:WePjHVgyNnAWKsQAO1N1zw==,type:str]
    version: 3.13.2
