apiVersion: v1
data:
  identity: ENC[AES256_GCM,data:nu9O2aLUnttRELXfyJtI0Ozdbk+Mtbh+GA1QhG25O8vj9b2qnSnO90oPh6qTKbWfS7ECYMt7Do/p/Kj6K3wdezu2NgyT9hOOImK1DVk9EClBjZ9v5lVVbfhNZN08/W6gQAv/allXkGdL8NS5NXsi6pbK9IZrdE/fG7mspauONRrBaHSVG9DKv9a7zNcwmHnPMEE/X7NIyx6WBDFXQaqQsg==,iv:+j++uN1f9iR1Z0nFHCTymkei149hbpjDHySBMnUlHUA=,tag:+aEGo8KSyYC+JkdHnIIcTw==,type:str]
  identity.pub: ENC[AES256_GCM,data:8HARj/EIO/joWmw/FL51MjaoZDnsAxkCioE6fYhF7V7vNtODYUZyhOppTx4bCb/qI1+Yyn0bJINiA5QgsIH1WKwEOOE/c18dLeMion/PnDhQIbJ0yixOfCn+oNOsP1ZFp+i5kwAK1iep0LqY,iv:cCXIPko28xRtV2TwDD6JbYRVOYJlk5u3PbiRckbjxHc=,tag:lSTER25r3LsfGYL/wX4BYg==,type:str]
  known_hosts: ENC[AES256_GCM,data:8IO9upHVuEGuh57yoNq03lgnqAPba6Z9EKpBRgxBJQADnmUFlRO6VNjAt79LaO41EsQnmeYkChGyWNeoXPmyAV/m6aajPiySbfrgeec+AECngmGx4p6prQPz2DcKROj2lpNYiUu/ZAumdRTMavjM3gZHba+DPEwGNY67AccashlyRXFHPOouP6w3eAXNgVmtP8qe8zypMWO/cs+1mmiTJ4ogoq7tFbApqunhon1FufhWJXLTkodRgCbkXtXoRVHIabOgW0CZEXImYEw6JeK0GFKE9gXzHUZNSRmmALtfBj01rZ/NDWVvZiDMSSxrlsFE7ZhKD+lLDQ/x29i+3OpxIqDwZFfrNbHC0bpX1fkLkh6UyYQmW00Q6v28SPz/yFyI4F7XxMuHRiAwNfRUihZTH5V4o8Ki50bpACIqNrElsBisp188kgKbAXFSseNvgUI9C36L/PKdCfBSh+WW/ezT8xsMugUGFDtMRFxIglfhX7xcMxK5ZVLbv6vt2NswSbkgqisLBr+wmtNchjDj3MAA4eiBOQJ6bSqB414qPWNyZtiO9qi6GAO3XiEZAUUqHUE7nsmZze6Jq67vBKJANUh+7KSpPLrPzUps5f2R/S+LvMvhgykH0opB106cNoVoc78TZ17cSBI850Lt3g4pvVzQyU0WynWXZ2jiQPcA1H3BTr0DlafxBA9HKeakuqTzhI4gQXpu+0vqZOCOy/hTvGWP1jQmEkc6x8/asYRLJXA9dmiPi77ERVR4l/clJWRsUHtUa+kksuhTOV1rB0rWD4+rxdhGxyS9clsUzr9JezSNbsbBrW3Qvppgb4GotJpmpvx8wQLlJgOc3G2F6CXJhDvCqTbA33e5TFawHBFpkeA7xFFFg/PQfOPcANK0Z+cBKEFr4RsW4qChSZS+6Msily5SaujnceHiiguCW8ts2Uyg6uTsqyxIv8oqlMOUd9Qu/m1BIq2i/XK3Um3JQNGKAOMaI8SOj42L+vcv9h8dBJFOjgs3D5fqtbmDlgY/YSyeWK0Ns0nLRqCTXDrHTjYA7ElBP48vvrBM1jjDC0zDDKkU0saSPSW4O89VQF01WOydV56vjskZxWLiYFBGiwKHxEkXuhuKeh3w67NEg1AtnfbeY7MqASlsrVMd9Yz2/ouNeoSANGXmYgbvKrVOKRefiWYLI4I0CKdnwHmPJJ/82Bh8z5kI5EnPrOK1Zen5yMjFi2HNMqq4K+mXulUUgnEy8su+RQ947g5Kv0s5US+INHe58pX2UURHARfxRaeV2Q7/ZzGDIruD+JNhgYTbyQBhLjFHXgp8zYbSNpUa,iv:vG4eioMBwfq2QhnZfVMW8eACDdkOKb991wB4p6bJpx8=,tag:Wb4Ah9uDyWVdHUHvzw8OBA==,type:str]
kind: Secret
metadata:
  name: apps-charts
  namespace: flux-system
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYUlSRWxleVJiZEs3Nm0v

      dFRmRklFOW5RMDk2ZFhqYy8wcU5saXdDUzNVClo0NmswbEgvdklBalNsc3ZEaG9t

      NkV3RU5WOTBnSy81b1Fkc05IZHg2b3MKLS0tIDJMUUJxbGZmNVdmdzdnNFNwWU1O

      NmV0N1A4L3lxZ2JKUWFWOXdZZkdYcDgKEHqpGVwnED59Nnvo8RJtpKY1v8KLiUdx

      dJTqSiGHZAHBUHgo3EgfHB/uHdJgAk95rW0ub+KEVuTZCHLZxZ6UZA==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-06-19T10:57:28Z'
  mac: ENC[AES256_GCM,data:jmMeIWbP4D52aYFbV4gd5srZ9EH/raWqbPZ+JOICbQG+Mai1sw/T3lqcLilbHyB1P7GgWX1rGPaHHclNtAtk0Rjka2Tkgz/ZRWbK+2Ez5LBUXUdBGii2DHF+KTE2bBmV8Qu7PU6jKXBJwkq2Y/GIbI+WGkvW8TLnov2ALCoXQXw=,iv:rmC8fDANft/GoV9sxxQO+JfYBnp70x7Xn9Av8DsHCJA=,tag:W/mvTRJNeZEdsF9UVJrCmg==,type:str]
  version: 3.13.1
type: Opaque
