apiVersion: v1
kind: Secret
metadata:
    name: supersync-secret
    namespace: apps-supersync
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:FD8MZP/jt3KW8MvkISnsLF7rL4mK9UhW+kPFx8799BNO96i5GO9Wqz5+nHSlUoYB/LKfETHiHbkoJgP2igEMyQ==,iv:l2QXnMwVK2tWkeB6icf1MYldKCfQSFwB5TB+8+n5Q5k=,tag:V6SVNTvtapdo+omr3a/dsQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:x1l6eBI2io/BNipadi2js8W+fbROZmAtwSUoB5DOAE08rfn8WH7f8M5oZiKGxuTbpgxscr4gZC1mEPrrX54P513gyAQ4FP4txlJTghehl4jvAjGDjCkx24RGAw==,iv:sU4p5kitefPQNhouB5BT6zEVhIGwj8XCqvXHbTKtd7k=,tag:NHIg+F3NPJEj8Aa1cWlC9A==,type:str]
    password: ENC[AES256_GCM,data:JFhFmDr2BcmU2D1CVqUhyFlnBMi9un0d5diyxxLoyns=,iv:HnW8lIoNn37f/wQMU5KzxOsIgrph6e1EoL9YEwm02Ms=,tag:IMy9GUi9VBMRHoJRB0OV7w==,type:str]
    postgres-password: ENC[AES256_GCM,data:QYcX/YGMMVugTzMBdtOHd+N05yhsUieBJyvjqkYhI44=,iv:FDMBvy6I9+MSmACO3+SSl24rhZ3dc0oHy2Z4WPGCehA=,tag:0RK8U4dySVOUjXzdgjpoKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Q0pBRWhJTG9UUWJNVXF4
            TGU4RXJHK1pCSXJaOUZpWGlHaFBTSk5rVGtrCjZ6Zm5QZ1c4akpzeGNVSldITk9Z
            Y0FXNGVCcDFVK1c2aVVIMGhiajFSblkKLS0tIEVqYUJyWXQwWHQzQStZdlRZc0xs
            UGRpTmF1N2RCNmJtdndZVjBod0RlRlkKyp74xE5+omEyNZ6ew1L+mtgC+AlEMNBu
            CzI9H+WEOPXGjyJWg0xJ5FA7UFr+xU5dEAQAqSIWV2vymSmihtOlaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T11:55:33Z"
    mac: ENC[AES256_GCM,data:KSZ3oQ+1yWG2cYbJgmiaD54weXkZUpwPBwm9iix5weMrJ/TtaaZWcAISi6xdoMZ7F6Tfgmen0irV2rmOUzqtxsDtuGkwK4SRb7mczn72kxA3rtgXowhsa1mut3UxSi0RgeI5mwZLdRmRUyiSnJjspmmDnwIArLo9eyDFzD0U6Ec=,iv:rClUvXUNaLDkoef/SjiE/+1qeqXAh9iNUdc8RkIN9pQ=,tag:c6StzRaWI8M4JB87XKQCRw==,type:str]
    version: 3.13.1
