apiVersion: v1
kind: Secret
metadata:
    name: gickup-secrets
    namespace: apps-gickup
type: Opaque
stringData:
    forgejo-token: ENC[AES256_GCM,data:1vLLe/whMZ/SrW9VhbIcV1lIivvh9FzaeevflJe43UueV+Eo/+JGwg==,iv:ZmxdXWsjEcPsfLBsyyJo6AEcieUGIqJuCQaCtTPRPFo=,tag:ClzmzdGT3dUOUjeEKFWbag==,type:str]
    codeberg-token: ENC[AES256_GCM,data:OLA6Q2T17S+nB81K3tIEkaQ2HDxP9rQeOjf4EYt+Er/LWu1q7QdaFg==,iv:lEC82AA7eAhLRuTqnI3pCPq+dgnD+jtBETMvRnmbuhM=,tag:g9rb33MbpHa5/GqYMPLnFA==,type:str]
    ssh-key: ENC[AES256_GCM,data:j/NKScWDqinu1eGIuW+WiG/Fy6Gomh2i99ssDh/e1G4nKZ3Nyq02a0pqgXUBY3epUeCZSwwhbZzzje1n+fsfY3/jfVJQkHwKliJ8pxVj5fUDQHYTM58iS1mBhT8E1kcnj32xO2FQx5YNYe1sEkRpti/8J83yaM2bVkCAj0pCM3WCbveVx6YztGPyQG/hVKmn5qSeAp55Km6lIh9qA6j4b3CKHQaUgFqBP15IKyR6i4DEWsBxpDMEZN3KKvuQtsVjUbOK5Jsu4SK/3OlRjdVR82M/KjCT/u/xllqq2OSOYRdQKfuY27jQhel8zJYmfrcFuoX6ygSJ6ds8FTgbRqf+HvxZojnTA3uXgwpommMqAf5vfp24pqWY1lO8QHB/4XgkMal8weFm0bnZdFvSXRQuXEyIVrKvpo0L13V/iWSm/Wl/CUb2l9WdpJ4QEQQB2rIMldfDh5RKgOTALY0Pske2WVS74BRxt/gGchO/BS4x7qoW2GsqPFxLp6KDo2lD9lG/U11skX5qyp/5rz71DTy0fEabzHmbLQej/9yQ,iv:RNglcacQMDH8RWIFJ828GRXc/0PgNX/8jwnnjApXcCM=,tag:/y2Ug4cmcBIeIE5SxS+SsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtb05Sa3ZFTkhQQ1NVbmpr
            eGQxUmF2QVNBT1E2N0JBUGxJMzFrRzNyc0QwCkJQQ1hKZnBvRnRESW96OUFyMHRz
            UFUzaU0wK1dPRjlRbU56NlQxSTVPdU0KLS0tIEt0WCtZQTVBWUNLTXAvS2VsckxC
            cE5VWWRVUHJkdzFuY0s4QmZhSk1VWGsKilsUVBJPp+xEU3JjSjGb0OwJd/c72khD
            6DfHAR59YVQoo4MU9Vg97nULDylzVedHRQpUWPaOszKq2jT1luTPSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T14:35:54Z"
    mac: ENC[AES256_GCM,data:cn7TiIPlsC0y/o6NIyoquzdM9L3Xo916paBv5DvZU5xY6ngqdqeGpLCxfM8eefYMRDBQM3lJpeOWl1sM9hxW2f6vy0myD7bypKylGwWpE0JKW9M7vbXEfCeydZQloA0nexzK6X5sEIaPxIoRgjNwiTkROMwGW4PqYQ/LEVn0+qg=,iv:wuQ3W1xPK2c9v1qwIvP8CGQmc/9dY1XDrzJkFf5PaVQ=,tag:8urX9Q5D6qYcZFsRO6Yvtw==,type:str]
    version: 3.13.1
