apiVersion: v1
data:
    identity: ENC[AES256_GCM,data:g8hBWFFzilWIZIMXhCtKqda7Mpt+3jA10AdXVwlE6sJ9KArbHqhaoqUXTLyc6PMIefKDzRC5f5/xZ+F0oSnlsZMRzjUHIDO7+tfLlBGRlJy9K2blsdfrNZK4hsadRESfUGOXjHS+k20OqcW6HHy/59rYXvnV91gTa2xOItPFMJ9u+AlidU7WTAExRouJOkRHUYpF5zTaZ4wyPtFqCdgurg==,iv:RLMg0wvXiucz8mxpIBrU3d2UMNKEueUCNFR7ET6MivI=,tag:pCejpLxv56dcYKMQybGaWA==,type:str]
    identity.pub: ENC[AES256_GCM,data:8LZmt5dnM0GXbdFv4ZHGSncTAXu/ZtxHyAIAtavgrlJJvXSgaw3mfdBozZIYSaxbLFQOep1r4bcD9NGUHdXoC3es3NozqC2fdj6JukkBo/shsY9bl4QdwwJ6Xy++3bJu3Lcd9+8RxsItDXMN,iv:QDlsIjRjRE+bCStmVyuBFJid5ay75sQE3XFxwr+ry78=,tag:AtOvoV5OQkz26j5QZCUlVw==,type:str]
    known_hosts: ENC[AES256_GCM,data:mFwr64bc7DCwQvgBW1dfWYyHmhEMZAfmsBuKCUqhQOQJQhuyiafGgWlRN0xbPfed9aqIhwzSl5Rg5THrKeUQ/4wv/1aCOLcK3UGsIhMbVo1WAm9yjgcUuw3ITMKJFLX9y/2kPty7SQsRHObFpSs7VB0mcPYQKtNy5SJ5Nvwy0bmGW8G2n/1eiKZ+23NDKEmWElhn+ud6xKsv0/ptamt5Vt3B++ieoZSwsz01ANPCATESy3+PHoyIDCQpt7k8mahMFLEPt0ChZ6dME559WkSSeEqCgPPfvp0Jvq2uDXcCRrtee+/HXWegzpNBZH2ZFhaC5CKosAWFwnOEVZabzsqnjL5eDCM3r9O2hHolHFeT28lp3ZwkhxkwKSzMlzY8vE/kuwHZIwOEv6WOO8Fi1gmKK9u/53JQop5aivQXTS91VQOm2vdFtwrIY1e/YLwrAYjguSkh7mzG7uI0TglTu5AbCiusSqJ4no3RVUIC7AsE25eTLSKzzQc+YkMMGaycq8gciKxF9tdl6UgXdPWQrOssWYf1i5ANt455hWbmLSBmu0PSfu8nK/iT6tVZQ/UNCCctSXMPynQwTfEu8SpZInfGOh8QTpWJ2lvIn9wK8fyzXfKGZfNbc9e2ujm2paeDN08HwhkX1nHz8haaJcVg6dsRewPtdI9XCatuGqqJAOTn6NPV4ZDsbGrvxQrPpJo4dntoh1pwh4MEt1pDLNeaET+MIFhV3YNLtq+nrG7LbCM0Y56hbFQvcgLg3eYBMhCLIjwgz0MP6raYqmAYV9Xopa60iB4SRJi74yy/yn89frnB12Hw8r2lNHDIpkblr24HIRRYbBYwIC67vrNGMXkyTEkZJRqcvaRXgdc02V7mRq+HmZ2Z+h6ULHwQInDARDfMJ7OqCs5EuVAroiUXi/HjMyDDnBJm8VkS7jHmImIUnUL/kfsjbfPtBIMV45O4+2iYg1I0PXk9wBB33I25D/3A+4CgxSTQgTb0EyGH48/3jn3JqmeqB8JXLEHBgr3UkbLiFAY546mG/2iDV6GuCrcQpME1kgQKpRRd8rNIir591GJF7QJGLJn/pp5dAUlZV0yqGopKPofqo36awqp9pogp3bRcxtVtAoQwg7PINpAfYibwwVtALR967FttfTKPRGkw46BgVbBxBIRdrVe9WfuWXrwNju9t6ZZ4P5P+lkkQYGJgCm978nWjI9615NfWi/lWAVwAB0ph765yOMdfrIRHgUjI8opo9Ufr/8WJJxTFuxjY1PIkKF5H/gq1w+HRQy+vO0ufdxJKQut2iRAj/KZcAgso5LG6SrPbDDVz,iv:HwiRZ61tx4aunZNoPUnIEA98Jp7iifE1tEoyHf7kC9w=,tag:zmmpEJv596/YFh5WPb2m7Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-06-19T10:28:43Z"
    name: apps-charts
    namespace: flux-system
    resourceVersion: "3044014"
    uid: 203b1837-417b-4e8e-947a-53e86df354e8
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIS091UUpLTjlqdUk3M3Aw
            dXZKWTZmUG5sMG5zR1d0ZENsclhrc3BwOWxBCkJtbzdlYlU5Wm9BWng5WmF2U2pl
            LzA3VWo4NnZtL2xSSUx6VUFqVWVwclUKLS0tIEQ0endNS0dORGkrVkZQbTlXYWdS
            OFl0ajJTcFZBM1l4UUp5LzhOSnJWOUEKgra90K4yBzl44yVkVvhlwME++C1ebQyq
            zYAuKIFSRSa+usYOQfb3WdaY+c7XvcXf+IR78G2mGox9TVVjTJfPWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T16:16:56Z"
    mac: ENC[AES256_GCM,data:SDmscBzxm4xwlUvkwtoSZpCVGx2ozsmHI4LrJwxjjM3d1kSkxKqzRnv0vM89+JfoZFUbJ0VuvVrsNETPlrfd7el8Q1qu5zBtMnwMO0oeMd/gOpXKoqW77mpJj/DfOLjtK5H8/7pDtbKvaj751T4PKLCCcegNzFs/WxM5a1WAjFc=,iv:3/IPsXi6PsFow6afEH1U+GOAUN3Y52ikT4l1CTQOO3U=,tag:Sms0ylAxE9oYDyaGZ5yZew==,type:str]
    version: 3.13.1
