apiVersion: v1
kind: Secret
metadata:
    name: apps-charts
    namespace: flux-system
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:QtghRcO/8A1enJ7LZtF76hnpzTUaS8Vg6RAUizN4hxVlFlHY+Z1AjSOhDVHjB+7gG3xQmu+8BmTr+hUBQ9GUvTEORhG9YYmsVyiktIHlN/QSnxiL9nIIi0qbLz+gAVCfJVhxCfgYslqVCuTUP4ugICuKrSD0Jps=,iv:vylIg2Eu+sV+biq99XT68nnmMRkgg4LnwNgKbhXX/TE=,tag:wunutguChtLLtN4jejq6Ng==,type:str]
    identity.pub: ENC[AES256_GCM,data:KwoHBjDbUZ2xkC76Dttes8b9wH/IUr7pFBz8NoqIkdekYcWFZ3OmUpOh2c+rRBzj4nZJ9AMkZ6+LXg4H1OBTVOwcDECFMVELjI4Q6XPVl+JH,iv:9SCMKBbhPkZqZ8VUj5q3pYnJQmzS0qlnDi9DrpCV+x0=,tag:RtbxX3nvmySgCNZ1Lu9MIA==,type:str]
    known_hosts: ENC[AES256_GCM,data:sDHq+/7ejkza7E3kBR3GwwBrhd79JpLld1e5HI+8LqwLK2HoJ01Q3yHLSBbJdVj797FjLVyCc++WTImLPQzhtBMchfUAYLY9SN51epU86lC5eOr1Y5a0xfnXtHwGextr58BprD9YpPGmuXhkZZfP6Hve5mUlstl352S1uVIJVsuQAgAC9o43b69LfVIVLQdrdRXv/OOKG+m7bXBUnrmoF2ZXqKEze6bdseGGb/6hEktoIpLdAh/8YL5RURgscSvtOJMjPyanaULZd3M+JD9T6H7BR4HBvmH5f+a33rxSoA1ip5HH/tBH/Xsb0s440aeW/k+P5HDm0fwVwHGTvRerHOB8TC/Unb9lM5QuWQuFS0fRnBtAILbrBBroa5vUbIMfLvD0kI24vbKBvFOqC8+SiTvN4cFtE58+d9C7+94ameTkQRl3/90lCoAdJwTobUSVZMxPR+DKekvP/YjjW3bckkR1sGRe9xUb+k0RmFenM+taDqs4liFn29MPp8691uXCCQdqxSK5c1qsSAo9xI6jxErT5LNb7mX5HCDyBm36QyQRM2z/GF+AjwsFt06K4lQJ5UatZUichUc5w6aUpWQ/YONmSzwS6CZSKbwffsmm0LELy4t97BUjkFMTWDRzSDv2Iz1DV4wZ2Zs5HHU3X0y+BZZUXBa4xbdTdLkhUa+Ai5LOLpuOLs+AwbfmdSy9o1kO97RSeoLN/9QsfHucILgCTGgqe+/DvG+1h7ajkEU5q27TvyMYZt2EWTutUKGjlvWrAn+avBrD8nS8sd0sUD2o2eBACw7U1J5vo4n/OFduN6kVZq2Dk4cCa0TRWraQruU3cC4mQc3DZEFLFl0Q8Uc162HAD6jHJbJYqkfLc2PDf/Bm5yeSoNg+RbFrIddPTAFPxG3Xz/2jKBissBTemKIoXXLpVY7WTiimhrfSha8IUJt1w5RpqyqdmqPaRz6dAeckLwFMsevyFFO3VlVwubrXpVlE4fVIUffBL93rEQfvO2BHJArr1YT3nliaQUZ1Z3rUooQ=,iv:AMNceFscduLGHJxMPizaLmhR7ZCMdgk/lZJ8lh/LjE8=,tag:yXThUFFhiSYNRbIAbYMD3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVEpJZExlQnhZMUZzN2Va
            WElza3RLNmg2cEFSTlFtZGRhWTd0dzh4ckM0CnkxK21LT01sM3FJaktNTXFWRkZ3
            MU1FQ0hLRHZkK0RXcnVkb2tDUFF4M1UKLS0tIHFINW8valhBN0hWd0VJUDNyTzVT
            dGFyY21hTjNCMWw0MUs0RUJlcklTMmcK+JwrJa6+ZiezFLpkVo3sl9b6cq8wiiW3
            1p3FurbZ7n8insufO2ucOTA5x0Dhac5Sbt0U+pCLhbuYdphmtwgAEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T10:34:49Z"
    mac: ENC[AES256_GCM,data:nibtaxQGrqwAyL/qTA87j2CQgWXnEYm8VvtuTHFlYct/qXU2b2U+XekghyysV2sORfrCUHueHq+umA4eEMj+j3DFEpg1WQHcygy37QdHBp5IzkUXTJumkzu69m/AaSW1K1qhDww5PFhNlG81oteLr1CFYl7iECtn29YFqtlEAlw=,iv:2UX/t62VjeJlqJ3seA8PUR2xZXzbycyyYrgk4hv2+OM=,tag:aI/osOEa7D+PsGZHIHuUqw==,type:str]
    version: 3.13.2
