apiVersion: v1
kind: Secret
metadata:
    name: authelia-ldap
    namespace: security
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:l3Z2rhBUONbczf7Iox+GDluHdQDuw+jirlnbrUqWutQ=,iv:37oZ6lY56jQ5x9CpOpF5X0l8MxRvSX0+wdTe5Y9WsBs=,tag:tWFRmenfmxHvuKsvykJNyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQmxaRkhFQTlvdStuOXZT
            WWtCRjJFbWZBNnlBYXZNd2hzMXBSTDRNclQwCnloTUZGOXFDQXFMajh6VlVqZ1E3
            UWJsVjVkWUNYV0VPaXVNZndad0pRalEKLS0tIDYreHJUKzhvSk82WXd3UnhEYjZJ
            K2o3S2pJa2lHSTJqbGhhaGR4bDhVakkK7B/CfqBNQeWfXuTW8M2jC6dXFP89OmSa
            W1yMDxcoTs3BjB487RbQRl7KoOZJTLZhPyIRawkLSeiGW4xTmw2Rig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T08:39:27Z"
    mac: ENC[AES256_GCM,data:K5aXLyAK2Z4Fk4rr6CXFWabtd/NUzbiXYbin0Dzc3JJ7mxqp1tCGPDOIwRWyQVSop3YyGb+FvHvQ6RNrDtiOrFuna1y5A2lOPnt90lPELsVQ+uJ6zoHBFg5mMIHqlj2gW6e3hmb5TdYFCuFYmZuCI6mRw7C605wwhMGxI+Ko5ww=,iv:IvIONQI93Mm9P5wNumG0L+btJukxOzYq3eppgfaaRLs=,tag:mmoNnmZ4ZzwHj8m24LZ5ng==,type:str]
    version: 3.13.2
