apiVersion: v1
kind: Secret
metadata:
    name: authelia-reset-password
    namespace: security
type: Opaque
stringData:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:+RSSGtqU4mb3mymo2kM+AcuUJwnjRwGulQMI7DauNNi5uVc4xLQn8XdwZEsDot3Sr4QAAGVXrp+QrMEamanhlw==,iv:dOdC5rvTy+3GNHXYG+wY6cL+a06gAGHQwcrFX2URyOU=,tag:5icWylygvbkAMqa+81eN/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHelI2Z0hTRzlNR0NmaThS
            U1EyNkVEbTR5Y3BhZUhTZkxWdDRYMHlSVkFjCkd0bkNRQWFNSjZhTml5NU1KS2Qv
            ZmdaYmt5RWNKNWgwUGN0SitiVmh6MTgKLS0tIGNUbUFmRGtBYUg0VWhkR2o4VWhH
            UjlSelljQmdFaGQvRTRpN1lNQ00vc28KcJaF+cLuSkh+Cp25AqpjQQNwGszH0O+5
            pt3ezvNYxVyIYn+dgKA1MaaEGyKRczhEvF+SoAni+1gVw1pXOQlf8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T08:39:27Z"
    mac: ENC[AES256_GCM,data:Qo+fJ57Golp6l/svxxtjFh4pjdZo+qeBME0JtXwFqfhj6JHYQ4qzx1Pp0/BBjmeli+SSlXWodpjYHjb9a5mIWQLSZ4VeFBsN8ixYeMwbxmKsXwlw2cuW6rSItx4emLwk4NB8RA1+nWAXYDijQnEdsdW6WxiwNGKJmqgflInrcCM=,iv:KMBq9cLzkC/GNEqymAru83ay14HekzFVnYKUpsppOtU=,tag:iaPWvkfXc2DjKGeWA6B/eQ==,type:str]
    version: 3.13.2
