apiVersion: v1
kind: Secret
metadata:
    name: authelia-core
    namespace: security
type: Opaque
stringData:
    identity_providers.oidc.hmac.key: ENC[AES256_GCM,data:lobKzRRH+aXjf5cb6LuLjq2GKMJ3IdVHHky0dRmIvT1zTQ+DhxK/KM/l/LKC2aZK7jzYAzer/3PWhVBg5MjBWw==,iv:WbjCEbxrX3MyElykG7iEEASqrT95se5huPjRfZw04TI=,tag:WLoROxoi9WCJYISrIU/zEA==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:4/5JMzsLKgyq2RYzJJMGaE+rHu81es7VSVLNw+xwVsgpnRvZkwCsst+tQrEG9LeagGeH2l/hziyoaQbxQYH6fQ==,iv:sJHM2NWqKIDQrd5Kkoz+wnlyMsOyjqmKRzo5+KA9KuM=,tag:epJ68PrtDiPDyOQDfizDYw==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:uuPoXp4wo780v5MuFb9GbHDe43EYFAPrLdsbx1Vc4iQDdaB2NMTORvaV2Yxjn3LW3p6eWfe8LR+Vv7s1Qvli2Q==,iv:nWFeujP2MNPcIwwPTc/3+u1JZOWbe8mklQInXXBfsSQ=,tag:dUVnf3wQRDNpDIOSqlIcKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcWp2V05ZRWMzNy9IOENS
            aGRHL1lhUWsyQmJWWE9VWDhHQ0xBU2NFV3hNCjd1aEtoTUhHNk1TcDRLbXhNSUFS
            dTlnTTlRa0pGa2s3dzJmc2cxeVA1djQKLS0tIHlwL3IrL2ZDUG5sTE1WRjhLRW5S
            THk5K09sRGtIeE1JUngyek9vUjRBUnMKkqHz5tXzF29hNydyQws+x754H2xlAbX4
            bCFc1SXnqJ9sx8kYrPbUTx6nl6UvMjcQ8NMiK9C1DBMBVyS4uAMNqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T08:39:21Z"
    mac: ENC[AES256_GCM,data:sQFkJZdnCJAgKZuc5zc/U5bCYYO27a7S8Y1JdJCmgrlU82UuN/U1LUJX7jYMJooCAy2YqlBBvzdOjyFs0ImJk+R5Wasn+4b5atzdc1HmtDuaX7c3PtTmMUebiP9+Z+X+fVMw/HwXcxkVIN/KNWvb9j8ZUpv+F4aS57BWv4fLV6A=,iv:ouYPWTWEcGUSwsxb9cyhwtsnWiqXga4VJ52+Ckr1alg=,tag:GCs7yHGKI7FOgatbMdzzRA==,type:str]
    version: 3.13.2
