apiVersion: v1
kind: Secret
metadata:
    name: authelia-reset-password
    namespace: apps-authelia
type: Opaque
stringData:
    identity_validation.reset_password.jwt.hmac.key: ENC[AES256_GCM,data:HJC+jd6zvU/lT49tmL4RHbvBCpX8Xt+Riyf9qI6LJBcPVk5hRRdsf9pVrMWmKhDdCGOlejTu2UPCLkzAq57n7A==,iv:JNfuw8baectzoNzvvEgq1TIPj+ygutmki+4B8NFQtXE=,tag:yGNNjvTcTmI6vNxSBvOfGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc3RXUFBKYzV5UGJiMVZK
            aUJCc2pRSFp1dzdYTmQ0bmJ0Zk9yb0h0OTBzClVvU0pNeHVxWVlSMHo5RTM3MDl0
            a1lLQXBqME55bFo4dHFNZ01IVU43UUUKLS0tIDQxdEgwTWhMS0ZKSEZKNGY2ZE1p
            U1VZWlAyQzZBS1RBK0hNYStaWGJmWmMK7y/xT9KFder6bhnsNz/jybEO6VplYvDR
            OleWW0/zHZ1oKstMgyeKSNdWUHNH7UQCz/+a+OPgPPMrm+eXcW4T8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T05:40:10Z"
    mac: ENC[AES256_GCM,data:V/pD1L/DQgd7WkdN8kzK6nfmP7cWdrKcZxtTe0kA7eqQ/BMMZyda38EVo9nmHUnB28MULdyTZe9Of/0jTgLNxXiTBCZFtIGvhfnnghzsHujYPrnwdbVhwDjhKVOLoHNMJEN0mgCueSWzV1CgEbimnanvffBe/cbcwl7qCpFxuRg=,iv:UwyZLuJiyzKmnG654tC+NipoRyVQYjYDMVaZSXcBb1o=,tag:Di0F0gFMG4+lVkQ7oNaHNQ==,type:str]
    version: 3.13.1
