apiVersion: v1
kind: Secret
metadata:
    name: authelia-users-external
    namespace: security
type: Opaque
stringData:
    users_database.yml: ENC[AES256_GCM,data:iCA+q99Y7ZP8vEBSmrXry4IPRq88CtqYqF7H51LW50HOtkFEoe90NH2tFCrFrUcV0JXifxxxW2ukM2AiTLsR+20MHwlxMfzcYESSJPg4OI13h/C9rZ+05zBHDYIjzabCcJbMOPdvyXkKp7Ve4tS8Y5CL0Sgw5LSrsbZ/eweDq8uDFtNkdA+9TGhaLLEUb4Yyyv4iZY31u4Q2jTk3b5MyllX5zdXLk6KmloGKZG0yH5gF/MQ1/HCw3mksi3+Hys5Pi0umzJf/Njn2cnk6VsV3iF2yRFwdS6E/mCq9E73PymcVN1lbp0DQN6HFpZVhysRO0S1e6FDqUEM9py4U9yMGVblTBP5na1qoDz0wTJDlXjtpamGEsyin7G+7ApsGPRH6aFYTcSUOk3WfLYgw0jyOozTY,iv:VWi/NiYRC3o+4tSlbKuYWiUaMAygrWJtQe2xjYMJcaE=,tag:6Wcm0U2HRm57yhnprc/ZmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUU9LeCtjeUF0RDR2b1lu
            TC92dGdCM1RDTnlnb2licmpOblJNZWZvM0FzClphMndoMkNlK1N6K3ozbFRPQmJO
            dW9VZkhDMk9Rb0FUQTZPL2NUYm85Z3MKLS0tIDBTZVNpQzQ0VUhaUnllSVVSbmdv
            TnRwUHZIaDdrOGFyTm55emVpWWdUK0EKn7Gdse/6b8TO9XKdiTADp/nUBi06/n/O
            uK51ved7HrjOCDfFNnInrc7Hk5Bvjy9HUHH+sLJEg6XpA+ows2V6jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T08:39:27Z"
    mac: ENC[AES256_GCM,data:DbP1fqJ4WNUwUvZ0KiPkP/v/uf6F+q58O2KC/ukIpOtzZfPrJnzW1sMwEmj2qT4eyjLRY18WojdkB4+AkbpyY6tmuCndqt0Y6GFMXh1l694/wgsP7ze6Ypao2/0f/3g/CMsBNR0N4U2YpchPhDCvvN8faGOU2Z2eLKN5XqVjrRY=,iv:IF+2mYY95rkYI9XapqgJ52gmgK8xfY0dH5uwyO07zUM=,tag:UWeSJ0oPlHkE5O9+SxAojA==,type:str]
    version: 3.13.2
