apiVersion: v1
data:
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:kd3IFaPlhUag/qPUJAyYsPFQ89w8UWiHOXkz98yQvBNfDen7ExEQairTE0tL1Bxbcna0z5kU992oH3EStYMim4EbYDeF6pVrhLUI3PbTCxKWN1iFg8LYGFbtebiJ3XmzG2Iz24iwtI85DqT0L2V4PgHEktfGje1keqMeEQoVoIQ3EtOKzG+/caQkbdP3zTUs6yfExBuNtZtdYyW/7mAPcjvPP3zAB/hky1WY518XPgr3lQM47FPh8dOskYeinnmD2bdl9wwXVe/08SnvCXLpV4ARvWPHzcXfOKKEW+TM47nZuiqPAhbChYzRqn8firm2NqBUJTh1Z6hqlKcS2zLIwDaKyQNq9ZAPnx36z4I8nc7Q344jj0t2ZRjwAJBKBHLW1O0YHC7FVqXuWcjT3v4n52/gTVrP8PmQ0mj1HnkQCZEblHKzrmn+L5cBuU412lucxo6VvZIJUstpco3PgMI75UTf+laOmCJfOShbq8RXdFdQrhtVpe8wuTdYvopvv7O0cb5SCyRcjHeWyKRECPTJhcz7munjoBnhFR6XvVZcvOv5VGYxOTuHYVDTcUN8kedIdsv0z61OJQidfNJSos4nfwpGAgxpWgj6kblErqDW53DDsGhECntRRG2Rs8OD4IyPQrwbKzmaYKbqscGCP7OynkR3NHWYf71caKP0JtaRgLjfsoBOCJb6Y8V8NvGOK3qlULObEbnPjNV8j+3z+C/YlOe9IdWU3fAzxUknHeZ3Lz6ZpNj6Zr+dsM1KXiGyxUyKNKD8wmFzWuANW5ld3AjyJ6wxfBUgW5apHdcf2mOQFUOoX9tEjjgDNzmIyKJ0C6chi4wq9qI2x8yPz3EAuezB2kqcwpDvq1fKU9rsaoif6tIM5wzqyU4YeoRnfnJIZre0TNP8wsBHhkC43eHOq4Q/VfZj3ZitCc/ZzISo0T1vzUoauVXVntbznyCiYif4vy3nj+njAneglI64Bi3xqxejDMhMYa+1yr8GFm6D3nBtsefUX1Jg23d2mn5AmesgUO4UkCa1FkuGlWqWDuS+mDEriGL6BbwD57YsfC9ZqgJqF7wszsLAvCNDsiCywGm5gFJGmYSkvJqdJ6W/oSa7VAvamDScVR9uWnePZv6Dr5Nof+Y5W37F8p9ntaZ6mWB7nL+B9dSlARz54LQWyXGQl7bKuDM8Yx0Pbvib0YE2nfEmNl5xCwgyi8TH5/PGe2Py+mB447zsEKkmkjKI8cdJn+J8DxF1G9zqflynrX/Y6UluHrzASx9x3UfJSsCouKYVIs80hooJMqsk1pj8K+lq8KDfIJlPUrSZSFYzkFAsHtaMee5zITjJkUgjZrQ/BcfETpqTJ1M52xk8TWNRSXDI7PMPca1PO6NkaPb/M95rkJOjhkMLpJQ4e0e0Vay6Un8=,iv:Ik2H6Sw53jX/0/sfypk4G7KuzkXs4ytQjjEFU7IXpPI=,tag:M/Z4riyDmvxnDTvUdCCPtw==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:077Nv5/4+/gBb9+yE8hJSIWXs2EbvJrDOWqSVIRIeTCjfR65cC/Gxl2uZFj5CB47WBQJsugFE6Gc6kMN5r+vyM1YP9hXkW8k+2xr74chGZdk/H56U3TIYgAoBrBT95TWbca2YTiDWhVPMzBL,iv:FF66rOuyIeCa/pOA9GW+ctRS3x2b2FBV2lMTccHEBPo=,tag:kR+z+OMUbxRlK6+P+QiNTQ==,type:str]
kind: Secret
metadata:
    name: authentik-config
    namespace: apps-authentik
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Sk5jd1QxcmJ2WjZNenV2
            cXlLSWxaTThscmNxWTZ5dFFuVTkwS0ZaR1VnCjlBaWJybmxvaGNaSFBHVDlpVk5Q
            ZFdzUnpzK1k4cG9jZDdIa0x1VVhUbmMKLS0tIFpUQ1lQeTk3R2JJWllGUDdvWHNy
            ZnpGK2tGMG1vTmVPZ1hkdjQwcE1DV00KTNx/5doXQ+gjwAwsUQLvsE8NmSyWRl6R
            4IW+N05Y1C0xN4Ezm4QqXPHFU4IPeUsDF90ke7RsHqoQDHshemcnig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:01:23Z"
    mac: ENC[AES256_GCM,data:TWCG0bjaGcPUL5SYLz+vZlGl2Oa23gMKnm+qQyMeSA3fPvI+eGBN6KgikaiDyGjz4m2Z+VNk9loVrlMslaTnQbsE+oqvbLmbTQHb2Bka68lv9yPyxXEBUa9HR8TqHhLHjVQeBGODF7mU5doHvsuw52k0Bq3e7793yOSYNCGXAPs=,iv:6+GUlI67vq8+ZitI1+WdaZ9PvUNCwkHe6pB/kL3wdSw=,tag:FnRhQzwkkhuigO/uWbqamw==,type:str]
    version: 3.13.1
