apiVersion: v1
kind: Secret
metadata:
    name: basic-auth
    namespace: longhorn-system
data:
    auth: ENC[AES256_GCM,data:mhQ7jNf+GeEYsxhXh+Fxa4VLl501C53JrVzjj8sXd+sX02FhUJFhZQT8qDBf236a9kzDZF9JtAPNb2z7C/+g9Q==,iv:hReOzQ/SLLdERao3U+FEMJPhuTII0GwTcuPs2hmelxI=,tag:rcoQNtQ9dcGqnBrSGflKDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0c3RVUFZCVm9pQW42bDNp
            a1dFdlpXaUFUeFZrTzZFZVlVelF2NnpvLzJvCk9jRG1nYllIU0szc0xsZGg5ejhk
            bTBteWcyS09WRFNBSkhiTWJaKzljWEkKLS0tIDhGek9RMktjZGlubnJZN2tJZWJP
            Qmo5YXo4TDBpdFZrSzNmV09WaCtLMHMKYx/G16LxgHYVVl2C+O/6ccN+GGtjwD9D
            dVXo/P300NR6waMt4ifBM6Y/JmieNRkAPeISuH6sjeO9hJJftVcF1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T12:46:46Z"
    mac: ENC[AES256_GCM,data:NZQvEpUrtRzE0aDcuQqkp9ifvaUjtfUPW+nFIyx9H8ysnpKGgsF+7AC3gAp3Hnlb+8plmkFLINenPukFINf6vhFdyRW4ikn8TXEpzG4M7oXuklVYPZOPTotBtDFtJxaTaRG9bzucTfqotpm6wFVEXPeUQYRZI0SbAWtDPKOHELg=,iv:SLz3CYqWCaCNocI1EAgbylWqDfUkTxGbPQlsilPEIiU=,tag:YCz4QRIvmNlVb57XOpmaew==,type:str]
    version: 3.13.2
