apiVersion: v1
data:
  identity_providers.oidc.hmac.key: ENC[AES256_GCM,data:cg4fQbRuHU6LZL1ICxxJ8Hcx6RDcwiYAJbBkp21Drp7PlH2X0aKpivMtliGfB4kVM6ti7pdzVJnuaT6hHI9zowlOH7IUm3fN79R+0NNLImtULQKbLNMXhg==,iv:oSFQoQVlo0T+cTSKcNNdgFB+ajKr3TEWhuLhIxgi85c=,tag:hPS0PFxWq4AUeFFWhEjPdg==,type:str]
  session.encryption.key: ENC[AES256_GCM,data:CLmsrclmxue9MmSCdCtq8KOBuiF+fTQ4BJEINVu0DOvjVrj3mw8C8ddo7WudPc/inGNRNWsHdiOWyvGuMamNzVnkKpq28jQ4ovKNWY+pieejM+xuYCpTfA==,iv:5D+cX1WuSZvX8sngj0zVCFhT13y/EhByAeYU+gXMg/A=,tag:SaU+nYXHO9sk8IrB8YQFVQ==,type:str]
  storage.encryption.key: ENC[AES256_GCM,data:AeebDEP2bA4g8HUwn4dxglhlpaRyq7MjrB3KZ1yKNXbLn2vYlnMf9JVkGSS8CzUwGvrljoQiYj7Nc5T9enekXb5yE1iYbAuj7UYosy7zBHEUvNlCXAvcbw==,iv:VtUuLvnwk4b4ogi9FUxNxnQCR0ydMQSWnw/FGg8uVok=,tag:eYNgzrA64COamFFtvwjWNQ==,type:str]
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"identity_providers.oidc.hmac.key":"NDRhNDdjMzlmMjUxMDRlN2JlNzJmYWE4OThmZjM3NTBhMDgzMmE4YWQ4NmUyNjYxZTMwNjI5NDBiMzBjMWY3Ng==","session.encryption.key":"NWE1OTA0ZmMzN2Q1ZWY0N2E0NjYyMmI3NWZiZTEwNzg2MGI1M2RlZjk3NmRmMWE1MTdlNjY0YjZlNmNjZGMwZQ==","storage.encryption.key":"YjlmYjNlMjM2NjE5NDA0NGEyMDI1ZDJhNzY2MTE5ZjA5MzdmN2YwMDY4M2JlM2ZiY2NlM2ViZjVjMjZmN2QwNg=="},"kind":"Secret","metadata":{"annotations":{},"name":"authelia-core","namespace":"apps-authelia"}}

      '
  creationTimestamp: '2026-06-01T10:23:33Z'
  name: authelia-core
  namespace: apps-authelia
  resourceVersion: '1831357'
  uid: 0b503ee2-6199-479c-8fc4-2c59d8738fd9
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYUlSRWxleVJiZEs3Nm0v

      dFRmRklFOW5RMDk2ZFhqYy8wcU5saXdDUzNVClo0NmswbEgvdklBalNsc3ZEaG9t

      NkV3RU5WOTBnSy81b1Fkc05IZHg2b3MKLS0tIDJMUUJxbGZmNVdmdzdnNFNwWU1O

      NmV0N1A4L3lxZ2JKUWFWOXdZZkdYcDgKEHqpGVwnED59Nnvo8RJtpKY1v8KLiUdx

      dJTqSiGHZAHBUHgo3EgfHB/uHdJgAk95rW0ub+KEVuTZCHLZxZ6UZA==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-06-19T10:57:28Z'
  mac: ENC[AES256_GCM,data:jmMeIWbP4D52aYFbV4gd5srZ9EH/raWqbPZ+JOICbQG+Mai1sw/T3lqcLilbHyB1P7GgWX1rGPaHHclNtAtk0Rjka2Tkgz/ZRWbK+2Ez5LBUXUdBGii2DHF+KTE2bBmV8Qu7PU6jKXBJwkq2Y/GIbI+WGkvW8TLnov2ALCoXQXw=,iv:rmC8fDANft/GoV9sxxQO+JfYBnp70x7Xn9Av8DsHCJA=,tag:W/mvTRJNeZEdsF9UVJrCmg==,type:str]
  version: 3.13.1
type: Opaque
