apiVersion: v1
kind: Secret
metadata:
    name: authelia-users-external
    namespace: apps-authelia
type: Opaque
stringData:
    users_database.yml: ENC[AES256_GCM,data:vbZT1F3SDAtVjanCcUe++q/2fREfN5OBTgUj3lCm2pyT62q05OmrVBEoyGgV2HnIWtWWekZv4i2IuISu9fKqOkr9Bfv4Cf4OBYN5lQVHb64TfkYFCz0AjI5Vu34Deh5S6YnmIZ7j5Ka2rGDwKuh2yRncg9mffw+NDF0R9APQIE+V0PeZS2kfWfFRgN0t46zevlJNUPSrPQVEa28ATQ/TvJzaWVrdieavCEz3pOCxZpRA4FNCWwIZNRCZU4QeXeWLYbhoWFykBmLWioxUN8DcikylWnmgDERhz0e1hvJJwumqmL5vpI6xYUD61Lv/y/1OCjHZziJm6SfYpsxPAbKbJ6cdnbcWb8NH09JLonFVCxJgBw305pilvdFSm4Ovr0ESoLVuLGyx14fS0oEoHgQoEli/,iv:5chyZVDhCetojI6MUP8kxckNYWvWZhezsZfD9d7MOqE=,tag:7KHxcUOHXqD7L2JhxK7u0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVk1nUWFpRk5KTEs2dzJu
            YmdnMDhwSElxUUE4V1pRQmJaaFFQRFlRYzNVCjJPcmVhcjRtSzZXOFpjMmhrVWtD
            c29kSHZNdktLU2duSmYwNEZnNk9VbDAKLS0tIGhpT0JCaWh4NndoQU5wUGlpNlhG
            dktZOHAyL3Y4WUxYZXBoNjV6eXNZb0EKpn0jHRcqGej8DnNLqll5ONIQ7oblCmpm
            eNP9WLj+5h65AnKfp/VrjZqn7JnLorKBv7cGzW26nwxPqUT5rGy77g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T18:29:07Z"
    mac: ENC[AES256_GCM,data:c3ZOkIH6WeZALNA1uBwT6l9NYcJNUijAO2zZbG/Itfns6lHUbl4xT6GUc9Qpe4YIddqP0FqHnKNPfzrDiBLeWw7q9Qy+CsmSQAK0FH2Jau007eYQvKfzbB2xIMYCQpirllOHFW67MkSfzIENfbamq+ArA5svAEIQMVbvz0a0y88=,iv:VQtgWWEqlAOkXSbCFXaRHCMI/AnHKwHeI3Z3qoZeVzU=,tag:EkUMq7sZpjItiJFIA//ENg==,type:str]
    version: 3.13.1
