apiVersion: v1
data:
  AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:Pnl7Csh8IGGuHmLCj+rNNEHOWYbgc6DOBV7XvBQMBVzYr1gXmxX4v1cn/ru7Jjsg531ngxxdx/ddHdwmX9XxCZP71Vij0fAff2NGplQREjr+VSA9+AFxHEHrqx32vnaEhA8+8J7oxjd5rl+FhFC0wfSNLshx7rozDj2mUEdRn+ICnZKbMAZ5oY+YfbGiY5eCt3UpiQ0mHG4Upbgz2ocWE+KsjuEhjJt0N5CavVOrQ13V5Ib7LomzkjH3CunF5y0DGdRTAkA1vK/5pXe3Wc9GpwQW6aRKG7tksJ3t4DXcbXkuy5KhbIrU4qXvOz13iEEwdqoCDqbkWiKhYkICbQ/lH+BO8zzBTGljJNA9eyZYuif2z4NhqhjO8BISVr1hUfVhUezrEiQJ8wga0U86rmmGVAyJ9eLA6WDdEboWnpYqL85ekhfhmUwPNSRdJ8VckyQ1BfeYESW5Oo+GWeHapQMOJ1xIqaenlKuEbLD6a1N/NL2AgMK2c52UrExjWGzEIh5qeDkZV9N+hzJjXPIgnpAo7TojjSf3lbG9eB7yfPFTZDBVgmudAP//6NnjxDPCMdPfMoDqWMqMQBZa21ZoEl62/JCG5lJiIIRUS9qyvyj43cr7j4wiD/6VPU8kEJ4qUJaji1yP6N03JhlYN69QMiJmcVXncKlthu3W7PiVTKIkUXpMOxS/sdFwsiA5M1ByrKtes5thOh2rg84MdPy0CV5eYHGXnbYkYoy3/qLnktLPP3eq5pUB+j/hlBTLVJ+xUdGjlPghrogxCnkGSR88uMB1F41CdrYMlYJ6XH1xCCR25rqmOMl1k6CtXD+W9YRR1G75SvzRpBJ+zZislYsQs/kkKEra8K5OpNU3anO4ixTGdGw/hNqdNxwaaTOygp8FNqGSairBZwJgQvduYFkR0pB2lRJQgMAVItgYfe61/4Di63tGBhPwoqXLDyWBE9WnCcngv7koE/YTte/NYTMMj7hW33ck5ipIK2AvcemMEIkPTUwlryiz5tzcSabD0SJhW58RC2z1z05OBzlg8ow4PJFcoUZPvTLv4vlmiqiyQyrvALs9X+tGAi5EbDO5hG21L9d6vc3pYdcigTs0X+0xubHTM6P2VIZ7EMiE5f5iLTQvFLc8H+pJH4B48UNgnNYW1MUUdLgjhYJvX9va6rVtsCuLBW49RttcT5+OFFTyUvF1r6HO13Z8NaOAOGoioHJQufPROYTBpiIJT+rlN8RLpPdOu7ZrTDkQDgjVvPieqoOEvSQFyDOSR7vYX8Snuhvir8EkOtjcsIBUMd2/ORJaQMA2sl0o4B1eKAATuE8R6m+zifLbi7FU/LmPct9sSjHWdB69r5Z4XyNhrDpKwA67Y594LszoImcvyHppsGeJyTum6xDILaVgqQ19sgw1e/c=,iv:DssEBZSSw4s7s1Vrdv0maz4zbt6af5uwmsCEc0ZCnb8=,tag:ny9iBDO6toLbPoyRBJeCkw==,type:str]
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:yUJY2SyCwK0nuS/24KnJmJf+2TLK/CRi5m6MDWRjRThLI0jifMVgqtjR3nrnsOSXRUTSAnKxhuNbkHrveIrIZdyRQtJhChkgogrU5fOiaN4boupB0XHDPEJXn+JDHpirIGsX0PMd6Hg+1zwl,iv:GDCM7klnRHdxP8tmjhZKBzg41Z6wn5ZrVZSj1NMb8zE=,tag:IO4BYCNqPLseNQmb9wqNBw==,type:str]
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"AUTHENTIK_POSTGRESQL__PASSWORD":"ImpTMmIrNGRPelNJLE0kPn12RS9YTjAhWnwjdj5XXFxUJyIKCmdsb2JhbDoKICBlbnY6CiAgICAtIG5hbWU6IFRaCiAgICAgIHZhbHVlOiBBc2lhL05vdm9zaWJpcnNrCgpzZXJ2ZXI6CiAgbWV0cmljczoKICAgIGVuYWJsZWQ6IHRydWUKICAgIHNlcnZpY2VNb25pdG9yOgogICAgICBlbmFibGVkOiB0cnVlCiAgICAgIGludGVydmFsOiA2MHMKICAgICAgc2NyYXBlVGltZW91dDogM3MKICBpbmdyZXNzOgogICAgaW5ncmVzc0NsYXNzTmFtZTogdHJhZWZpawogICAgZW5hYmxlZDogdHJ1ZQogICAgaG9zdHM6CiAgICAgIC0gYXV0aGVudGlrLnhpbmZyYS5ydQogICAgdGxzOgogICAgICAtIGhvc3RzOgogICAgICAgICAgLSBhdXRoZW50aWsueGluZnJhLnJ1CiAgICAgICAgc2VjcmV0TmFtZTogd2lsZGNhcmQteGluZnJhLXJ1LXRscwoKcG9zdGdyZXNxbDoKICBlbmFibGVkOiB0cnVlCiAgYXV0aDoKICAgIHBhc3N3b3JkOiAialMyYis0ZE96U0ksTSQ+fXZFL1hOMCFafCN2PldcXFQnIgogIHByaW1hcnk6CiAgICBleHRyYUVudlZhcnM6CiAgICAgIC0gbmFtZTogUE9TVEdSRVNfREIKICAgICAgICB2YWx1ZTogJ3t7IChpbmNsdWRlICJwb3N0Z3Jlc3FsLnYxLmRhdGFiYXNlIiAuKSB9fScKICAgICAgLSBuYW1lOiBUWgogICAgICAgIHZhbHVlOiBBc2lhL05vdm9zaWJpcnNrCgp3b3JrZXI6CiAgbWV0cmljczoKICAgIGVuYWJsZWQ6IHRydWUKICAgIHNlcnZpY2VNb25pdG9yOgogICAgICBlbmFibGVkOiB0cnVlCiAgICAgIGludGVydmFsOiA2MHMKICAgICAgc2NyYXBlVGltZW91dDogM3M=","AUTHENTIK_SECRET_KEY":"eDhnTjN2bE9iclN6cHpQRWd2R2xEa2hnTU1rc3lEc2FacW9DUWV2ZXlPc3BTVGt1dUdjVUVNdTBId2FoN0hPSE1qbU51Ym4vNkgyRS9uVDc="},"kind":"Secret","metadata":{"annotations":{},"name":"authentik-config","namespace":"apps-authentik"}}

      '
  name: authentik-config
  namespace: apps-authentik
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYUlSRWxleVJiZEs3Nm0v

      dFRmRklFOW5RMDk2ZFhqYy8wcU5saXdDUzNVClo0NmswbEgvdklBalNsc3ZEaG9t

      NkV3RU5WOTBnSy81b1Fkc05IZHg2b3MKLS0tIDJMUUJxbGZmNVdmdzdnNFNwWU1O

      NmV0N1A4L3lxZ2JKUWFWOXdZZkdYcDgKEHqpGVwnED59Nnvo8RJtpKY1v8KLiUdx

      dJTqSiGHZAHBUHgo3EgfHB/uHdJgAk95rW0ub+KEVuTZCHLZxZ6UZA==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-06-19T10:57:28Z'
  mac: ENC[AES256_GCM,data:jmMeIWbP4D52aYFbV4gd5srZ9EH/raWqbPZ+JOICbQG+Mai1sw/T3lqcLilbHyB1P7GgWX1rGPaHHclNtAtk0Rjka2Tkgz/ZRWbK+2Ez5LBUXUdBGii2DHF+KTE2bBmV8Qu7PU6jKXBJwkq2Y/GIbI+WGkvW8TLnov2ALCoXQXw=,iv:rmC8fDANft/GoV9sxxQO+JfYBnp70x7Xn9Av8DsHCJA=,tag:W/mvTRJNeZEdsF9UVJrCmg==,type:str]
  version: 3.13.1
type: Opaque
