apiVersion: v1
data:
    users_database.yml: ENC[AES256_GCM,data:6a8HfXMV6eEzluil9R7bdBqYBy7GAI2Tr8F6g4yn19qU8WPSK2Ada5etlqPBKtbJzf3lc7sdfjXBnOnlKw58S/Zgvd5bspPHn5K1ssUZ3YaOTISnXpzB3cgNAtZreLYjsyNK0K684qGMjggn8fNfoB2wQAE9tgsAD5wYbMT98duztbnx3dh3r7V8STclYshtA+ZhhXNRxyZP9gbPUCjl0doeNet9ll5aNCOtY/hvldiuo9aCFKoiTjHSIWFW7kKRmHu4wQ/bx8NwuttLiz40iutHpi49ygsMjcEfHaFlsf97H0w7StHkB7B8rGse502IMjnTHhBlOwvTZN1LUBB2CIlSq8LI4D8I9gjsVIIWRDY+9+uGIQOdxICN7A/30Cl8bMYzz0rTQRwDv7jMHdl9DJpR/WdPX4zL9kged+dY+9G9rlSTUUClAod0OqthjmpfB2kwGhejoVfL4x9qB4SOS5kimO+zvG02iHJD3R7LINs9ygD8iXpsrEwH0TghEbbfvcMJ/w8NZvBZWsO8C6SNq6Lavs+AkzqM,iv:iDEfXZIR0Cfk0a+xRxZBD02CfUt7t7mPsOzNf0RNCRE=,tag:bPRAaedA41lj88dzLcKIwg==,type:str]
kind: Secret
metadata:
    name: authelia-users-external
    namespace: apps-authelia
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaU54bGlyQmZKYWcxQWF4
            OUZGaG5BR0daNFd6WXc5Qlg5MFlYdEVTMFNFClNIU2JWaTBnMnZYVU51aWRUdm9h
            ZzJlaFNCb0pEYnFKRUN5KzNvM2JZcnMKLS0tIDlVMEowdGtrK0Z6bG5SdnBRdS9U
            T1dFOVhGMHVLYlV2OE1pYTRWYTBSck0KXgndnVFawu8eanu41OUzDsm3WRAlTrAo
            2RQH2RWjoVdfSsd7J4TGgvB15NYRP7kDljmFlsvzzeGij16C5DAABA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:01:20Z"
    mac: ENC[AES256_GCM,data:nsGjLkhLhIr78BOoHqoiJfuTO1XDTgSCa2Cb5Cjve7vAW+7JRlihjTgCsi16Beo9ZLxwyzC2FaSLooc+nq+qRFmYxV3spA2Z65Bl+3/z0hb/ufrKqsZCFz0GcXEnEK5bz3kfJWa6DwX1OTz2mnMdw+fq0jQrtxVUyVLI4ODdwBk=,iv:uDHV10G+ZVqGNsA1KdS0Fh8CnhX4TQMylksJWZBupdg=,tag:JeZpzJldDiQkTvBFuME/Tg==,type:str]
    version: 3.13.1
