apiVersion: v1
data:
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:gFzvjC9+198cwtACWZWIptz4rlA8keXB7wcLZ1l/x7CeDL7NwL71J4jIFs249a0aXO2KjjzH4rRoEOpa2HvAfpTUGzAYMwj6+OxJucFnew64Nd4J7biS/S+Dxe1f0fbal9cYhcB5lhQsqghRNz0eno/YHvS5S2XRneHT+9THtyscz6udHHSHWrd/dP6N++ieTjniZ3Yua5m6I+3KmRAE9dwGd44YKDFCNSdyTG379oXhkj0u8fVsIm6AQb5p9o7nSrKwp1qdXs5ix2py1CwE2JC85dbXW0oLVNetTN8AudcNX7TsmeBlimgzHMSMGUqs/CLoahMTqSxnF2QVPqSnRSys59+ucuAYNEVkSH91gThZv9As0iaSIyZMPYbIHl4R9/Z4F2m2iuticKGykrq6xgFA1fcSbIVD0XqXlrH/bhyqqqJ2TCEDqpDkcgwJx4Iv6Wa1e4eqYccnsZslQJDtp1l/uvH1oMY8IPD9jae326DIYOfRLJUkspZINALKJDiC2UFz5nuuQzFVe0ZwKGq9xB3iKVNjqR16+dSW2p0yuEXOLuGAaJPsnONhnDYQs6YoZ+CzF4ZV6h2EQBtqrpu/M5scV5OsvbRcA2GKsnT8aBak4/akQ+v8Z9YVCVqKClm2a+qHCveVZhJIKHUFL0eva8IZRRy+TURpiJDGFaR0zV4myOjgrW8P2+bFTVex3+ma8JlJn24koHWblxBJ1kW/1pFNX4Uun3c9nnb9X9dlBDsIkbdA1NwEndFbwmqhy+i3uW5P3TAfrhmAeLh3dT/nXS+qEh7DRyFJCjwCZkimmHCSyoYRoMFJz6ZN57OMQymhpsUrD70OFGcgTYL5goZ1707f70qgorAoQ78mfPqAS2gHJVADoTFfFioXHQ7GsdGR72+EtEOhbf0Y3iOtRrfko63QSPJvm8A8vICm/bA4diTo4psZ1B5Bx1/n+u6gmMhHHe/0EYCRp5E4qQ+Mi8KVJXkfxR358XFw2j+H1cR8Dhq1Et0GFvB6hjIlXH6w9CW0ZvUAW2sdPlOCnkiaafAqJWdB3XV04m9B485aF9Eiya9V/kwtpF0VDU06VnYpdMsiMKzRInEMOOfVeMCntIkPWkRJb2A54iaJ2okqUSbVhCu+VAW7QC+tgWJ+eG+gWD2i391K7/xxNEMqPd9LiWmFkyxBe+BOyC3lJtJSBRikUz74mFo/LQ7XW9Sf3QIjpJB38pOS3zvH5uFtym/bOCvct2jDyRxUVPUVQ83OFa3S3fxZNx7lijhm2lrVO4yf/dXNF6jdk2yikwIhDazh69bQnH3PENSBv2NRmSMeJ7Lf5ZvVmGyrQa1Ilxsrf0EwpoVtRDdgqlXf000Tx+853dzLzHeaDpySF1cUi2FT2uzlK8Li7TPI7UkBf8UovHM=,iv:0jyjOqRXj/uHzppmg0DkrIGWGPICCoUH4tS/fRKZueQ=,tag:UWimv6ovXPsNZzlcjssajQ==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:bNxWQSB7KE31eqbrNiOpI7ENSsLUoXtAkR1cp8rXhZXJ9ccKSCQnmCP3Bjf94+g480sS6uUeOU4eEZbQLv5lDyeA0RgXSSebhm3/UaonSFPPgl6icEXlsTIi7mdxt57jZfA6BZonRzIgFV92,iv:cKhnmaCtP65FTKH+OSvnSaa043wAy2n6Xk8SeRyP+OY=,tag:HdMM53pcs2yPJ7T8vTBIuQ==,type:str]
kind: Secret
metadata:
    name: authentik-config
    namespace: apps-authentik
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRkxRa3hLSVQrdy80K005
            TVZlMFAxakZpMVJONHQxcmxUWjZwTkZabXk0CktPbldWMkJNa2M4aDkyenBVNXBo
            MjBOM2hkZHlNQS9qWnptUXJ5SUllc0EKLS0tIFplREV3NjFUck42MG1ZVC9wVTh3
            bHphSXhJRnQzSjlMcVVFVTZEUFFrQ1UK/SzHYtVENB1mj6whWYc8HS9l2lKt74rp
            8OtZI9CxSlMFZyd6HZWIE8jHx5PHokJm35mYwmVCgKqtnhGU2R1ZHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:23:00Z"
    mac: ENC[AES256_GCM,data:6IrxMJ3iu1x+SqOyTqzhv0Hsqbvk+NQ1ZuIdDFe5dyi9hVvB2mdU2O/XUzzEGzyxvn7TEmgXuVjJ4ztM/Ehg4jQU4yF8qtmN2n3zjG6L4oho7PvSwrnYKq1gEO/4/27oCNoOwK6cNER5gJpw4yO3Zc0xs5+ec3ZhPj9BdbiS9H0=,iv:mPKPI/61D6+EZZADXFIT1MeZPJeSNOzzIZTr2n9JCKY=,tag:XXIp2wXrlufEjMPxrzk4SQ==,type:str]
    version: 3.13.1
