apiVersion: v1
kind: Secret
metadata:
    name: authelia-core
    namespace: apps-authelia
type: Opaque
stringData:
    identity_providers.oidc.hmac.key: ENC[AES256_GCM,data:jvagG+fRr6G7WFjEkgJyWtVSIVwzMXrHUm/JmELtVztOWaUfWsPhKYO5HqWHo21h9PG1oEFArF2rgKhLPMNaSg==,iv:+hqHagzmsdpCvZnGl5sk9i2qkCu/5pofkQ+O0yrGb0c=,tag:YFyWn7Vkcj30Tb4IN2xcXw==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:Eg3kKLqtNIqyiSQnjMoaUX/Ytrik1UDDfeF1kz8pbKDKEjZZLHx2e4k4Sydk+vZrAuUjpS+FwdlURmQN3027Ig==,iv:uHYPox0l628AxuGFlWeOxlZ3azrnqxmSWCCdq3p0CMk=,tag:H6cUZ6CQ2zHn16w/Urq45g==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:KxE6Zh8/ovXGCfKY44DYBWXq/hd0ujZAfLqRCSQ0Bz81j4ltBx7/Wja2ENeghaMGLI2C6Gra+/fSk0PLy5k1eQ==,iv:7RUhmOmoQaPhtOTxXdU01huDJcmeL/uURlx4rAjGWIk=,tag:yphyLsmKJwUhvRJeLLlMuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbjY1M1JmNXdnaitjcy9x
            cmNhaVZBdXNGemhkMTFOcGRtV0RsMHpPWHdVCm1OVks1ajZVNDFTMFg1RHhQMm5U
            cXFpNkkvczVtY1NIb2lZcVV3clZBNG8KLS0tIER6Y3RCdzNJWTM2dGwzV3hkUDdP
            TDE3dUpxSXE4NHZKM1ZyUHljQ1p4ZU0KeojRhpp5j/Xwe+wsJn3Wo7XSTUmmq2I8
            KgrSuTd+xShV5dUBad/AwCxOIwRzSaGe9lcC1h0O1y69E0RzGRNumg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T18:29:07Z"
    mac: ENC[AES256_GCM,data:U8x14hU3XPF9e+RJ8DwA0KY8dr4TRv0lgknQ3JK7gK7pmg3UCmBBACP0u/9CxeR8Ez4LtRqgvJIunXjXdsAHvyJUUcfrHYNrEGagU6mhHvCFZ3vtqMwX3L/osGzHE578qq6OKEWmoDWUGbHYgAf8q+kSjfa3IqnYfKep5zY6Mto=,iv:B2uTmWCToLng8wNx3qOWURWajuhtXOzq0o6cUqM33f8=,tag:21+NGjyA4RySOhkPJMKLsg==,type:str]
    version: 3.13.1
