apiVersion: v1
data:
    password: ENC[AES256_GCM,data:RYf+Vp82wrnaxD6DXivKR7L8DRI5RV94M9wZnPFWEjgEclDmTLbZJtoF6Mk=,iv:8on5TTg0vt55e1+sSgFGm24d0r+WLTWKgD6jKaFZlDQ=,tag:hqUQ5RuXLZ030RMsYh1VRg==,type:str]
kind: Secret
metadata:
    name: authelia-ldap
    namespace: apps-authelia
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzb3QxMXhWNUpqbkhOL0Jt
            OWJNT1JraFJqWjFtK01Db21hUlJGQ3dZZmpFCjExWnJuT0N3amtYV1BEVmFxY29H
            YkpjUjB1MFQ4RkpyN1hFUnF2dnN2ZGsKLS0tIGwydi8yRDE2Ykp5ZzA2b0NtdGlo
            eERDaWM0WDlmdXdFYTJqdG1SMW9OWWMK9VquGIu4bei2d+Go7ONn+/9dFZmwqEYB
            WPyk6q3ZlL6BLSQ/si5r6NmhZKdQGP0TRFIG/dOnReJv6SMJBeAJAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:01:20Z"
    mac: ENC[AES256_GCM,data:C4qm+n2758fqbFvHOrXRixfo8bvq/Zm7JDXbvFWOXS+L/2Wx5ifBPkW2xn3pgllNiLNHZyeNoA4Nz6521PgAKSfw8p6E058884yiAFor4O4DJNRVDpgWuqv1WozGjvd3VkbWz6DHv1uGulMkL09YcSZ+j1CwkZG+eEUrwXwfa4M=,iv:xviuZRAXaSmVA+L/Fk0SimhE4JIxKXWhYJYxGq0YNo4=,tag:ShG6p3XhhVHapB8zi3TbOA==,type:str]
    version: 3.13.1
