apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:+1nIfWGdPa7mGRZoEpxOXg0lrUz4s6hUbJJRiw87frS+a3cYymtWTByaB5Mp+YJ7wOKSTtw=,iv:J+u6AloUyoDHAOKecqw0EHBdx/G1AMaRv6Y2mWoqU0g=,tag:BPKZ9ceP4aMQ5tVyCjBoHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZi9XaUpLRHVCd0pUWnFX
            NzM5MndoM3JHVk9iL2d3djlkQlJ0ZDdLL3g0CmYyaWIyT2dOVzhaaU5qUmRSL0lE
            UzQ5NVhYNC9VWis2RjVoRURRb2tJeU0KLS0tIDRQb0c0NU9tN0Y1UTJtS3dxbzQv
            c1ZIRUgrWWpwc3diemVHVmtrQjAwZ1UKwQuq28BmqEo3d/MmqvObqGEbzMqnYjKO
            S940hOJOswyL2CW5pIzpK3EDcC9nfKQVF2+8qnF7u4QZeTRs4z+jzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T18:29:07Z"
    mac: ENC[AES256_GCM,data:Yj1oJqa3fA8OF3aMCFCnhiWwMT+jYpGZIK2VAaf9Z10h8RI1tVL3KTETof2xI9WXupj6IAVUHNtYsP5sW66okfBJYyFd21lFEhbDq7taoxovqFWNYQpz+L63LgnLGDyFAoUo0yTWQOha8csaAbffR0tQoUgFl/nrinVXxzC3Vao=,iv:ZVOHiDDX7YSgKf727j8WAVOQX3rWMwGlS1QUPwpuXWo=,tag:lCFRKgfCmFbvt/07b5qf7Q==,type:str]
    version: 3.13.1
