apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:7HtVWuB4+ITuWXXvESqYUOLZVWFiojx3iPga+iaCaQ5yoFYf0Q6/bJBODrvFy6+iqbS6nYCZbrRi3Tvg+2T4tg2f3iTYVU/5,iv:J2CWRNYjrUtjuZq4nTqPDakCJ4BdKQOJv4BYV3ePRlw=,tag:Q2CkEumNIkflDNwQAButmw==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUnJBWmd6WEs0RTZLd01n
            bjJrVGF6RHlIdWYzTjBzSHRRSWU5cWVsblY0Cnk3b2RKTUVpUGRvZ2JwaFpMSGkv
            V3FhZDFNRE5uUitORnpxNHBTNXo4a2cKLS0tIE5PeENTZmFrcndsZVg1dWxpditX
            OXdwZzBsSEV5RFMxWWpmZCtMZ1dKOE0KZD8ThGycsRU6oQOYhx2k8Gn9IK5jSqWg
            3ElidUZNG9aVT5hgBqUKiDbKSiSC0GKZnMWuZS2OqTHz3Sa2iVF2Fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:01:35Z"
    mac: ENC[AES256_GCM,data:pHGUweps77dEw54DF8bKvUB8hOxlYCcg8euJl/UCpap8Oo4VKgOk/QBZGg24JBEC47vppiQcKbOGwGcR10QEQKS3zfLCNbh8R/7EmgP26xHdbmTO4fpeqPmAlSXMr70/EeLsmVP0hBSe0eC1lelBAFPrMrsWxD8JZp2rYKll6LM=,iv:YRycAY5uJqrVpwe39yg4A6+o7e5gkFvNkx9Gd5Fr2VU=,tag:Rz2m5q7oAFISiDOKdMP8Iw==,type:str]
    version: 3.13.1
