apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:7crgwf327hjxIANmjNR7KdArs4qAIFWaBQdJTpFEDs9a9j4qVlkBTU3N02CowHPZjkuFRZihHacW2RKK2pQau4zkIRjeRbuO,iv:JU8Tr7he355ipFqliVocIgGuK9iitlsZDBHdQ/SKuL4=,tag:4YHDlbzTwaGJyoTc0POXbg==,type:str]
kind: Secret
metadata:
    annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"cloudflare-api-token-secret","namespace":"cert-manager"},"stringData":{"api-token":"cfut_1q8l3ORnsLiENWCFQrFhbxEFwAGJbyLKxedoiyEQ15a529db"}}
    creationTimestamp: "2026-05-09T09:49:20Z"
    name: cloudflare-api-token-secret
    namespace: cert-manager
    resourceVersion: "1830840"
    uid: c7b392ea-d493-4a67-b539-241b6e7be7e5
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeG9JS2I0ZFR2anFuM0xC
            SWdxaDlrMThqc1huVUlZeDcyVC9uRVJPU2hBCmUrWjVISmgxeTNKZ0hVbDZJeGZk
            VWZHT1E4VE1kRmNST1JpNUJvY1BOUDAKLS0tIGFHQ1ZuamtFWnM4WWxDeWRqZHpi
            UDI0WVdFL2xRdExUUERoeDlpMGpHMDAK723PED/xbpEd6VBq+jILI/Djp0SqHvtI
            OzZd23jBqCj7bvAotY2AEAQ1EWs/4hGSRJykP3Oz4OxHPpvmYH/yWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T16:16:56Z"
    mac: ENC[AES256_GCM,data:nd32FVWIQ3b9AUeTdACrIPh7yd9hMQjkSIBafw8w+vVmF54Tyo4I9ym0Ox0QJ8AJSOfro34XB2S9XuiBqPKGKKHQCMfYscpsivh6y8/FRyQP77d5XwhdrRDVVOc3MFJ+JVkxgYORTUa3ZJyXWeN1cvZ9xHOWSzz2IB8IplqBets=,iv:PpPfYI9ydAbASdcbYAPyYH9pblaIojXBfM+Ck1LZu2w=,tag:U7LpSsW28pLWmmrL5IsIGQ==,type:str]
    version: 3.13.1
