apiVersion: v1
kind: Secret
metadata:
    name: admin-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:JKaf9/4=,iv:Ku5gXpkRRQ3xtxr87AgG5iRVEnvd9Z6ZQunBPeLlZSc=,tag:4R52bem1ePj2hXpoHKEibw==,type:str]
    password: ENC[AES256_GCM,data:aSa01FD0r6Ui/ZawdkYF5FPffoeRLNDzl5P+l4KoCfXWS3k1PaHQRrbHGEXo8LbvDVwTRnaMK720UffUDiWwrQ==,iv:AOFlLAyw2wL9FaU3HB/9sZQ931GhPg/hltCzkGPGrBU=,tag:qb17Ty936JMy8cQC+3Ay+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSjBaZ0tXQ0VmMXF2ZThL
            Z1ZwaXZyTkZXaWtML2VUY3hXZFl6YUhIOHpzCi9NUFhJc2tjaEd5T1hUK25kaWZN
            eXB6UktlSlVIU3lyYmJPSU02dStLVlkKLS0tIGVZTEFNY213RG9xMUlHdFh6TEU3
            aXMvZXFaVElQV0RqbXIxdmxERVovZWMKua+WiTNBNDCW5WIY3rwyK2McorYwr3v7
            eZFCCsLe91X31VpopoBT8547C8FNW+WvFNbwrTq54tLFKReZJhVcHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T10:59:17Z"
    mac: ENC[AES256_GCM,data:wgl5PvrS6IvNb4lPNL7jkNxYNDSw81Qy2M8JZEB3xo6FyNpYOb7qieKU+tYNmUbyoHqpZdofSe8kJsV4rfs02xC0mNKuE4upZPTqIHpjax6XD02WfloeOpPLEW981jrjbSH8gGFttxuCwIFysy9nUEoq4PWjqtXA+xiIbTxv3Pc=,iv:qvmp8k9WmZyZCHdrmiDYjNrNl8ydaTID+LZNko+Eev8=,tag:cVlQJeAWYh2Hfn+wqmMJFw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Q3QKfOwCbg==,iv:/hZNjJY41muihsjQBR/8uZDfPymCuEZ6Vpu5Iygl4og=,tag:VXlmKZEiOGPmUmlFtlmcqw==,type:str]
    password: ENC[AES256_GCM,data:iPIkxteN7AQA5+sqz19W6FumAEkAMfatxnU=,iv:ItZd49DWa8FCPfQLxl0wjnTlOk6G+zwDbwwlHykwyWA=,tag:JY6B5dczKFeer6uP0EplYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSjBaZ0tXQ0VmMXF2ZThL
            Z1ZwaXZyTkZXaWtML2VUY3hXZFl6YUhIOHpzCi9NUFhJc2tjaEd5T1hUK25kaWZN
            eXB6UktlSlVIU3lyYmJPSU02dStLVlkKLS0tIGVZTEFNY213RG9xMUlHdFh6TEU3
            aXMvZXFaVElQV0RqbXIxdmxERVovZWMKua+WiTNBNDCW5WIY3rwyK2McorYwr3v7
            eZFCCsLe91X31VpopoBT8547C8FNW+WvFNbwrTq54tLFKReZJhVcHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T10:59:17Z"
    mac: ENC[AES256_GCM,data:wgl5PvrS6IvNb4lPNL7jkNxYNDSw81Qy2M8JZEB3xo6FyNpYOb7qieKU+tYNmUbyoHqpZdofSe8kJsV4rfs02xC0mNKuE4upZPTqIHpjax6XD02WfloeOpPLEW981jrjbSH8gGFttxuCwIFysy9nUEoq4PWjqtXA+xiIbTxv3Pc=,iv:qvmp8k9WmZyZCHdrmiDYjNrNl8ydaTID+LZNko+Eev8=,tag:cVlQJeAWYh2Hfn+wqmMJFw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: security
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: security
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:te0Dl2XOTnd2gS4=,iv:KN6Xv5EVFXlUSFLPxfqJASgrp06ZGfuTvdLcH+qVMZ0=,tag:e9t8PJVvu1aHynVyjzxIgA==,type:str]
    password: ENC[AES256_GCM,data:pYaJI2DsyrIKn5NtMVEZlpQai7AVYN/0dJxlwrkN2hY=,iv:ChKf7z0MXT83g092yIUAvluRqtXYczUjVA/TI5xKs5k=,tag:wzei2x1ip3RZbkLluOBJ1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSjBaZ0tXQ0VmMXF2ZThL
            Z1ZwaXZyTkZXaWtML2VUY3hXZFl6YUhIOHpzCi9NUFhJc2tjaEd5T1hUK25kaWZN
            eXB6UktlSlVIU3lyYmJPSU02dStLVlkKLS0tIGVZTEFNY213RG9xMUlHdFh6TEU3
            aXMvZXFaVElQV0RqbXIxdmxERVovZWMKua+WiTNBNDCW5WIY3rwyK2McorYwr3v7
            eZFCCsLe91X31VpopoBT8547C8FNW+WvFNbwrTq54tLFKReZJhVcHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T10:59:17Z"
    mac: ENC[AES256_GCM,data:wgl5PvrS6IvNb4lPNL7jkNxYNDSw81Qy2M8JZEB3xo6FyNpYOb7qieKU+tYNmUbyoHqpZdofSe8kJsV4rfs02xC0mNKuE4upZPTqIHpjax6XD02WfloeOpPLEW981jrjbSH8gGFttxuCwIFysy9nUEoq4PWjqtXA+xiIbTxv3Pc=,iv:qvmp8k9WmZyZCHdrmiDYjNrNl8ydaTID+LZNko+Eev8=,tag:cVlQJeAWYh2Hfn+wqmMJFw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: twitch-sub-bot-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:7D86TIblQ+XRl1oHLRs=,iv:32u75X/qP+t48ozDhGdYCP10XvdczEXDYYoExCmSiK8=,tag:ye3Y/EdXb+UGbgzIqro2uw==,type:str]
    password: ENC[AES256_GCM,data:2JUjvN1TUzLks7KjyM9wr1zt6X2ni+eVT5y45u4qynU=,iv:CGY6p9uje+N8IzCQ90zWV9+M+cyAMCT66Gf2JM5oJu0=,tag:Ztpi2QGzK4FPJBS1Ir2eAw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSjBaZ0tXQ0VmMXF2ZThL
            Z1ZwaXZyTkZXaWtML2VUY3hXZFl6YUhIOHpzCi9NUFhJc2tjaEd5T1hUK25kaWZN
            eXB6UktlSlVIU3lyYmJPSU02dStLVlkKLS0tIGVZTEFNY213RG9xMUlHdFh6TEU3
            aXMvZXFaVElQV0RqbXIxdmxERVovZWMKua+WiTNBNDCW5WIY3rwyK2McorYwr3v7
            eZFCCsLe91X31VpopoBT8547C8FNW+WvFNbwrTq54tLFKReZJhVcHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T10:59:17Z"
    mac: ENC[AES256_GCM,data:wgl5PvrS6IvNb4lPNL7jkNxYNDSw81Qy2M8JZEB3xo6FyNpYOb7qieKU+tYNmUbyoHqpZdofSe8kJsV4rfs02xC0mNKuE4upZPTqIHpjax6XD02WfloeOpPLEW981jrjbSH8gGFttxuCwIFysy9nUEoq4PWjqtXA+xiIbTxv3Pc=,iv:qvmp8k9WmZyZCHdrmiDYjNrNl8ydaTID+LZNko+Eev8=,tag:cVlQJeAWYh2Hfn+wqmMJFw==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gloria-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6p0maP6I,iv:IMo4XrDpK53HMBGx6QHbBxoKCHB+PU7YzBupDEWvtWQ=,tag:3mH94PpQOwR6R9yTSAtE5g==,type:str]
    password: ENC[AES256_GCM,data:cbcTBCJtqpBZwsJ1t/IrvNAm5C6jxCOo9VvsOp/5Eiw9,iv:uDvcbe/0Odb42cY+/Joj1r3BypPS/F0uZpt7Y7bEKcM=,tag:y7JL899N5Jy0J9IFYhNTtQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSjBaZ0tXQ0VmMXF2ZThL
            Z1ZwaXZyTkZXaWtML2VUY3hXZFl6YUhIOHpzCi9NUFhJc2tjaEd5T1hUK25kaWZN
            eXB6UktlSlVIU3lyYmJPSU02dStLVlkKLS0tIGVZTEFNY213RG9xMUlHdFh6TEU3
            aXMvZXFaVElQV0RqbXIxdmxERVovZWMKua+WiTNBNDCW5WIY3rwyK2McorYwr3v7
            eZFCCsLe91X31VpopoBT8547C8FNW+WvFNbwrTq54tLFKReZJhVcHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T10:59:17Z"
    mac: ENC[AES256_GCM,data:wgl5PvrS6IvNb4lPNL7jkNxYNDSw81Qy2M8JZEB3xo6FyNpYOb7qieKU+tYNmUbyoHqpZdofSe8kJsV4rfs02xC0mNKuE4upZPTqIHpjax6XD02WfloeOpPLEW981jrjbSH8gGFttxuCwIFysy9nUEoq4PWjqtXA+xiIbTxv3Pc=,iv:qvmp8k9WmZyZCHdrmiDYjNrNl8ydaTID+LZNko+Eev8=,tag:cVlQJeAWYh2Hfn+wqmMJFw==,type:str]
    version: 3.13.3
