apiVersion: v1
kind: Secret
metadata:
    name: admin-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:onGFH0U=,iv:7tCDOx3+kJlkEwBHt/KgyEBzydaryx0CeVaBYPw0GBA=,tag:Q3VV9vJjuYYLjOzb81xohw==,type:str]
    password: ENC[AES256_GCM,data:yfGx4OJHdsf4XlZfnd0ikVeUoUge2jW787dkvdGFfNd0U+Kl6fqcB+txPiYEvNTKaWf7XgPVQo7QGfv38PCWfw==,iv:l8y5J5KFiJwtmgf1zUKQU3AQnzIAJU713ngpKkGz+6I=,tag:Nl2kjYv1V7qPU1JGH/qnUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTHdHZ2s4b2ZVc3Znc01B
            d1pYZFBaQ2FNUm95M2F3VElmdHJkRlBISXhBCnlsYWIzTEFUMDZkbTFnYzVlYzlV
            NHNIeWpCMVJUR21oRS9KWUtFTkIvMDQKLS0tIE4wOTc4REUrNjZyWWJxMFNpZkJz
            ekNIV21ZSndISGs4S2xDMlg4Rk5qRDAKFZVxkw+/1kttGaU3wEwNnU5VNdkjiKS5
            Gjy/4Lvc2Bw73ahzXZftqOJCqoyq1pX1ccCs7MHErPwShiD8oIhWaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T11:35:44Z"
    mac: ENC[AES256_GCM,data:qwY3d7scTpP9YkflrHFBs6wge9+iQVbYo9xGmnXipdVakRnefSeepfA8yg7E/iE2/5eyhBYp+grVf0OctZJtGo0+0NCyuyzeap+bAFLYFLOu6d2UfeWgn9kN6nmzww8zHd/Lq025iyR3clKcMFNVVvBHN+pvpPTd1rYE0d/xJx8=,iv:GKoA+IGc5GCNy93YWt8cens+CYeU+ScM3ISK2CYflcs=,tag:YENWH70geEH5D9vqk2i4aA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: developer-tools
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: developer-tools
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:p3WmcZX8rQ==,iv:gxue4n3NuyEV/q7TeLvMOpQtJDF2yELKtl5lEs/2RTs=,tag:619pyFgXSHT+q2SXOX47Yw==,type:str]
    password: ENC[AES256_GCM,data:/5RTV8r/fx9Y/k1ZmZBITtqn/cr0JLvm61Q=,iv:YoOS2aQWn6zO5YzhpRHp3wL0Xj7q/i4znGjbu2f5ZjY=,tag:s+D9N7ot/fxOWBU+NMdzkw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTHdHZ2s4b2ZVc3Znc01B
            d1pYZFBaQ2FNUm95M2F3VElmdHJkRlBISXhBCnlsYWIzTEFUMDZkbTFnYzVlYzlV
            NHNIeWpCMVJUR21oRS9KWUtFTkIvMDQKLS0tIE4wOTc4REUrNjZyWWJxMFNpZkJz
            ekNIV21ZSndISGs4S2xDMlg4Rk5qRDAKFZVxkw+/1kttGaU3wEwNnU5VNdkjiKS5
            Gjy/4Lvc2Bw73ahzXZftqOJCqoyq1pX1ccCs7MHErPwShiD8oIhWaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T11:35:44Z"
    mac: ENC[AES256_GCM,data:qwY3d7scTpP9YkflrHFBs6wge9+iQVbYo9xGmnXipdVakRnefSeepfA8yg7E/iE2/5eyhBYp+grVf0OctZJtGo0+0NCyuyzeap+bAFLYFLOu6d2UfeWgn9kN6nmzww8zHd/Lq025iyR3clKcMFNVVvBHN+pvpPTd1rYE0d/xJx8=,iv:GKoA+IGc5GCNy93YWt8cens+CYeU+ScM3ISK2CYflcs=,tag:YENWH70geEH5D9vqk2i4aA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: security
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: security
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Indr0fK3w/UqlQM=,iv:B9zXSKT8bcusoZca2VXiYkpANM96DVuQ177aWIlibkM=,tag:Y56pgVs0tx43b0blcFtFMw==,type:str]
    password: ENC[AES256_GCM,data:cZDMIahuQXF/ZPgKUHvm4OkiHa9ww+OvRcvnQXQL06U=,iv:gpR5N0FIY8qJ2+dAZpKoh2sRAOXrFSA3FrmxwvVHzuk=,tag:pJ4/mdlSGA4oyd4T3dYGMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTHdHZ2s4b2ZVc3Znc01B
            d1pYZFBaQ2FNUm95M2F3VElmdHJkRlBISXhBCnlsYWIzTEFUMDZkbTFnYzVlYzlV
            NHNIeWpCMVJUR21oRS9KWUtFTkIvMDQKLS0tIE4wOTc4REUrNjZyWWJxMFNpZkJz
            ekNIV21ZSndISGs4S2xDMlg4Rk5qRDAKFZVxkw+/1kttGaU3wEwNnU5VNdkjiKS5
            Gjy/4Lvc2Bw73ahzXZftqOJCqoyq1pX1ccCs7MHErPwShiD8oIhWaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T11:35:44Z"
    mac: ENC[AES256_GCM,data:qwY3d7scTpP9YkflrHFBs6wge9+iQVbYo9xGmnXipdVakRnefSeepfA8yg7E/iE2/5eyhBYp+grVf0OctZJtGo0+0NCyuyzeap+bAFLYFLOu6d2UfeWgn9kN6nmzww8zHd/Lq025iyR3clKcMFNVVvBHN+pvpPTd1rYE0d/xJx8=,iv:GKoA+IGc5GCNy93YWt8cens+CYeU+ScM3ISK2CYflcs=,tag:YENWH70geEH5D9vqk2i4aA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: twitch-sub-bot-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: apps
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: apps
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:tTsB0Ie2CJK1y9/Znro=,iv:dsocoM5FLCkr+32XS+H6RdVf8JrtIqMVquSDxsm9Pko=,tag:oaZUphfCqifEZu4aE5fBbw==,type:str]
    password: ENC[AES256_GCM,data:rJ5qKRM3Zpaf0ahqpxRy1xcgv860cns0SDri5sb1XoM=,iv:8CvwdXW1G7vPYhMizQ21RcyqpRSEp1o5ZbE4dBK/6HY=,tag:vbg4I+pBo9Dlp6GM55obQg==,type:str]
    DB_URL: ENC[AES256_GCM,data:jUSJo2ZuapZQnoPHZbbe3NDfvRnWgd+0PBMSZaYICRIK0iQm4mJM156LOjDhcEL61/Z9AEyxhywmHHAmB6VFYCE86R0X/xoJwFTXuHh2pmmdZHmrmlPxQXOCpA5DaJ3Sw+qhq0nxzS1Qhpka+8o8VRCea7p47R1eMMhHP3CSrjU=,iv:KtnIyuBFLIt78wSEMXL3Fp2t0tlNIam35IuK/yjxy4E=,tag:zCXDqMKBO725v9C8Fcn8rA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTHdHZ2s4b2ZVc3Znc01B
            d1pYZFBaQ2FNUm95M2F3VElmdHJkRlBISXhBCnlsYWIzTEFUMDZkbTFnYzVlYzlV
            NHNIeWpCMVJUR21oRS9KWUtFTkIvMDQKLS0tIE4wOTc4REUrNjZyWWJxMFNpZkJz
            ekNIV21ZSndISGs4S2xDMlg4Rk5qRDAKFZVxkw+/1kttGaU3wEwNnU5VNdkjiKS5
            Gjy/4Lvc2Bw73ahzXZftqOJCqoyq1pX1ccCs7MHErPwShiD8oIhWaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T11:35:44Z"
    mac: ENC[AES256_GCM,data:qwY3d7scTpP9YkflrHFBs6wge9+iQVbYo9xGmnXipdVakRnefSeepfA8yg7E/iE2/5eyhBYp+grVf0OctZJtGo0+0NCyuyzeap+bAFLYFLOu6d2UfeWgn9kN6nmzww8zHd/Lq025iyR3clKcMFNVVvBHN+pvpPTd1rYE0d/xJx8=,iv:GKoA+IGc5GCNy93YWt8cens+CYeU+ScM3ISK2CYflcs=,tag:YENWH70geEH5D9vqk2i4aA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gloria-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: apps
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: apps
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:uHwgaKz4,iv:T6YdkICWBA6lq+UoX799P1TQIKL2nsbdKaBTD66HCI0=,tag:8FMpNbMI7uH/fzWOI7QOpw==,type:str]
    password: ENC[AES256_GCM,data:eRInT5vwvByuA6tDsqdAwuKEHt3Hez9FXMFsgWWNdJD8,iv:ShYXHFPG/ECZM0TfpW1jLkyvdNzjvH90K/VjznV204M=,tag:A6bnmiJcTeArLEfFBQRnng==,type:str]
    database: ENC[AES256_GCM,data:tckK3FSUC6t4cnjsweXIXsH9yior2Kkeksgik1F3O/t3z10audNi5HxD2J+Ayh9yP9fk50MGczcfEhoNKGI2mrWTpHAJC9PDI1GbQUtM6nEsAwOcPSRU9IPrurLgNYfz5YBNJEK6cgFxO6YvnGZr59ijSoRvBDp9+l+mtQKp8s17E7CGE5e//G5A,iv:F7V8T5VuNpEBaoFd+/mAhPYnQli0o4+gmx1jn2mk1fQ=,tag:/YL5qQxJSfYj4mV+uXDPrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTHdHZ2s4b2ZVc3Znc01B
            d1pYZFBaQ2FNUm95M2F3VElmdHJkRlBISXhBCnlsYWIzTEFUMDZkbTFnYzVlYzlV
            NHNIeWpCMVJUR21oRS9KWUtFTkIvMDQKLS0tIE4wOTc4REUrNjZyWWJxMFNpZkJz
            ekNIV21ZSndISGs4S2xDMlg4Rk5qRDAKFZVxkw+/1kttGaU3wEwNnU5VNdkjiKS5
            Gjy/4Lvc2Bw73ahzXZftqOJCqoyq1pX1ccCs7MHErPwShiD8oIhWaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T11:35:44Z"
    mac: ENC[AES256_GCM,data:qwY3d7scTpP9YkflrHFBs6wge9+iQVbYo9xGmnXipdVakRnefSeepfA8yg7E/iE2/5eyhBYp+grVf0OctZJtGo0+0NCyuyzeap+bAFLYFLOu6d2UfeWgn9kN6nmzww8zHd/Lq025iyR3clKcMFNVVvBHN+pvpPTd1rYE0d/xJx8=,iv:GKoA+IGc5GCNy93YWt8cens+CYeU+ScM3ISK2CYflcs=,tag:YENWH70geEH5D9vqk2i4aA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: homebox-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: apps
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: apps
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:XrCPg9YHIQ==,iv:28f0D1RDW8ZycTfO5kFUoChRb5YdhI2R1jy5+Nj1rsc=,tag:14ePxZavJhgcLDRizE+Dxg==,type:str]
    password: ENC[AES256_GCM,data:dpe0grRBm9/YOz0m58J7FH58M2AO5kbkclPDQOZDjy8=,iv:QeqHJoueVDZyAUZd98ZdSHwStbgZQhK2+gkYhEsSEDI=,tag:953SyZtSitLyi9wzQWuIbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTHdHZ2s4b2ZVc3Znc01B
            d1pYZFBaQ2FNUm95M2F3VElmdHJkRlBISXhBCnlsYWIzTEFUMDZkbTFnYzVlYzlV
            NHNIeWpCMVJUR21oRS9KWUtFTkIvMDQKLS0tIE4wOTc4REUrNjZyWWJxMFNpZkJz
            ekNIV21ZSndISGs4S2xDMlg4Rk5qRDAKFZVxkw+/1kttGaU3wEwNnU5VNdkjiKS5
            Gjy/4Lvc2Bw73ahzXZftqOJCqoyq1pX1ccCs7MHErPwShiD8oIhWaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T11:35:44Z"
    mac: ENC[AES256_GCM,data:qwY3d7scTpP9YkflrHFBs6wge9+iQVbYo9xGmnXipdVakRnefSeepfA8yg7E/iE2/5eyhBYp+grVf0OctZJtGo0+0NCyuyzeap+bAFLYFLOu6d2UfeWgn9kN6nmzww8zHd/Lq025iyR3clKcMFNVVvBHN+pvpPTd1rYE0d/xJx8=,iv:GKoA+IGc5GCNy93YWt8cens+CYeU+ScM3ISK2CYflcs=,tag:YENWH70geEH5D9vqk2i4aA==,type:str]
    version: 3.13.3
