apiVersion: v1
kind: Secret
metadata:
    name: admin-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:1PdHtAs=,iv:BptC8+WoM11GrY+3xa41/gtwsPOuiwOZVfJMEE4ZU6w=,tag:n60E9M56XOfCy7+QMm/Aig==,type:str]
    password: ENC[AES256_GCM,data:uny84o33UTix+lIop1B+9JFQ7SA/pT/9MJWV+aVBzsWLiDkh/K9G8l2C8JriJbxHsMlMcS+3hO+cEUGhZMOmGg==,iv:qJTw5la5KmVK0GgB98k1ahT0xFpVss7MnfKI+y/jb+4=,tag:GTHXHvA9q/lGOP7zYJARRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK3FYdS9ySzJNazNJbHlN
            Nkk2a3ZDa2crdW01WGl2dTVwblErZEFNMFI0Cmx0OWRTS0I3Sno3TFlhRkZKd1RP
            Z0dMUjJYRVAzQ3BabmNFYzBTZ2tLTFUKLS0tIDRNcmQ0SXlnd0FNL0dPamlzV1FH
            NWJpY3VrektyVkpCeFExS0Vza1F5NDQK+/KU4VCScq2JRETVjXAWk5L5YsaQ/i7i
            o1cjzuipnsSQlGj/kwEMkX3/bJFBROctmvRvRPml8yDilaxGShi4tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T11:36:08Z"
    mac: ENC[AES256_GCM,data:bePXO05r562dwklhg1Gach+xetZeQWstkrHPaDp/r+Sh6d5k0kBzUlWb/6yW+Fr8gNSAsY8nsP2Hub4gvjj5ZeWV/j2mnWibfrjOOOg2bhvMnNUL439EDwPcUaEoyciRgcyUnCBquAFYwG5Wobf47YuhsWn8YBeVBneF9S2iCN4=,iv:2us83qrrsbsGzt8Lyg4POoVrk1cDaG3hzBtxg5SRbEw=,tag:KIIcZNgJnkWCmMkqy64Pog==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: developer-tools
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: developer-tools
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:mwF1PDaKGw==,iv:xOEPdQfc455miIcPOAuKvEU1eog3JfZXhLfZoD4qxUM=,tag:tJXa2Q0bAA/Oiga4O9G7tw==,type:str]
    password: ENC[AES256_GCM,data:dA4tInsMykYWx/ZOMEj/04GAvlBeuMwzkmI=,iv:yTuyhudlgL3lzl8Ejyp5EZ8wCsG+330kEJNXaMPptGQ=,tag:OJ3/ZvwSN58J0jze3s5M9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK3FYdS9ySzJNazNJbHlN
            Nkk2a3ZDa2crdW01WGl2dTVwblErZEFNMFI0Cmx0OWRTS0I3Sno3TFlhRkZKd1RP
            Z0dMUjJYRVAzQ3BabmNFYzBTZ2tLTFUKLS0tIDRNcmQ0SXlnd0FNL0dPamlzV1FH
            NWJpY3VrektyVkpCeFExS0Vza1F5NDQK+/KU4VCScq2JRETVjXAWk5L5YsaQ/i7i
            o1cjzuipnsSQlGj/kwEMkX3/bJFBROctmvRvRPml8yDilaxGShi4tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T11:36:08Z"
    mac: ENC[AES256_GCM,data:bePXO05r562dwklhg1Gach+xetZeQWstkrHPaDp/r+Sh6d5k0kBzUlWb/6yW+Fr8gNSAsY8nsP2Hub4gvjj5ZeWV/j2mnWibfrjOOOg2bhvMnNUL439EDwPcUaEoyciRgcyUnCBquAFYwG5Wobf47YuhsWn8YBeVBneF9S2iCN4=,iv:2us83qrrsbsGzt8Lyg4POoVrk1cDaG3hzBtxg5SRbEw=,tag:KIIcZNgJnkWCmMkqy64Pog==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: security
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: security
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ONPJ9rtQVSJ//3s=,iv:CxqNoIK3gCyjSItty/tqTdB3hRel1R9EIDDOkXc6NRY=,tag:WgwGHyUK3JRArUYBbHzkwg==,type:str]
    password: ENC[AES256_GCM,data:OgWvMzfP7PeILKT8+Uq8SIhL141dZYABO4u/E1CtgpA=,iv:NDJXCy2RyzhKL120K3++cbma9STL/Ed4FVxW/7500Ok=,tag:8gKKUMzXrpjiPk+eiRUW/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK3FYdS9ySzJNazNJbHlN
            Nkk2a3ZDa2crdW01WGl2dTVwblErZEFNMFI0Cmx0OWRTS0I3Sno3TFlhRkZKd1RP
            Z0dMUjJYRVAzQ3BabmNFYzBTZ2tLTFUKLS0tIDRNcmQ0SXlnd0FNL0dPamlzV1FH
            NWJpY3VrektyVkpCeFExS0Vza1F5NDQK+/KU4VCScq2JRETVjXAWk5L5YsaQ/i7i
            o1cjzuipnsSQlGj/kwEMkX3/bJFBROctmvRvRPml8yDilaxGShi4tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T11:36:08Z"
    mac: ENC[AES256_GCM,data:bePXO05r562dwklhg1Gach+xetZeQWstkrHPaDp/r+Sh6d5k0kBzUlWb/6yW+Fr8gNSAsY8nsP2Hub4gvjj5ZeWV/j2mnWibfrjOOOg2bhvMnNUL439EDwPcUaEoyciRgcyUnCBquAFYwG5Wobf47YuhsWn8YBeVBneF9S2iCN4=,iv:2us83qrrsbsGzt8Lyg4POoVrk1cDaG3hzBtxg5SRbEw=,tag:KIIcZNgJnkWCmMkqy64Pog==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: twitch-sub-bot-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: apps
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: apps
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:cA7nAyFfmPKhSk6HlOI=,iv:ZAfmxz1fjPYW/RfbCTuFMlH/DdY9aLv1E3JUgxlIqmg=,tag:Gfm0esNO2nqNvS7nQyMaoA==,type:str]
    password: ENC[AES256_GCM,data:w/842fLuQ77B1V5SsZmH52Xjd5FWzM8Z462mCQ8RzDA=,iv:2sYFlX6iEBhcXmPDjiuJeiCQgZ4qa2cJPoIWtFkM1+4=,tag:7xYdejblybR+lAHJwSxONg==,type:str]
    DB_URL: ENC[AES256_GCM,data:vV5/3i+ayQucM5xeR7d/yP7GCxJQ+xY4QeRHGWE36kj9mj9COIVj9vN6b3LBfEjXk/Yei5Y3KmAuKdyiP54RhiM1unn7Fn6qL8NolhL2QCNdrmcf2kDnl/TICSGUwWTqgBwCxnEOO4GXF+0MZwXR0D9clAUh5ur3a58UipZbd98=,iv:qHsKCyyFiCmucwh2ea5fegrUML2V6frej3ahrxJLLLs=,tag:E035btHarxnyX90vEJ/FaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK3FYdS9ySzJNazNJbHlN
            Nkk2a3ZDa2crdW01WGl2dTVwblErZEFNMFI0Cmx0OWRTS0I3Sno3TFlhRkZKd1RP
            Z0dMUjJYRVAzQ3BabmNFYzBTZ2tLTFUKLS0tIDRNcmQ0SXlnd0FNL0dPamlzV1FH
            NWJpY3VrektyVkpCeFExS0Vza1F5NDQK+/KU4VCScq2JRETVjXAWk5L5YsaQ/i7i
            o1cjzuipnsSQlGj/kwEMkX3/bJFBROctmvRvRPml8yDilaxGShi4tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T11:36:08Z"
    mac: ENC[AES256_GCM,data:bePXO05r562dwklhg1Gach+xetZeQWstkrHPaDp/r+Sh6d5k0kBzUlWb/6yW+Fr8gNSAsY8nsP2Hub4gvjj5ZeWV/j2mnWibfrjOOOg2bhvMnNUL439EDwPcUaEoyciRgcyUnCBquAFYwG5Wobf47YuhsWn8YBeVBneF9S2iCN4=,iv:2us83qrrsbsGzt8Lyg4POoVrk1cDaG3hzBtxg5SRbEw=,tag:KIIcZNgJnkWCmMkqy64Pog==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: gloria-db-user
    namespace: database
    labels:
        cnpg.io/reload: "true"
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: apps
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: apps
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ydsHixBh,iv:PZwfglqzhTEm0a4wQymnW1yy8ljjS/RyDl2VycvocFc=,tag:VfjFEu3gz6ZP0vCg6R+3uw==,type:str]
    password: ENC[AES256_GCM,data:jPeuVr2VMEXk0zoFqgVLLjzr9Yw50/QIg8uYeSYP1W9Q,iv:NDBBhqAx7yI3TvRaYHuC0wfnSksYPcFuVaQ0xC9jA8c=,tag:LdADQdUDdl6pDfF9u3AY3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK3FYdS9ySzJNazNJbHlN
            Nkk2a3ZDa2crdW01WGl2dTVwblErZEFNMFI0Cmx0OWRTS0I3Sno3TFlhRkZKd1RP
            Z0dMUjJYRVAzQ3BabmNFYzBTZ2tLTFUKLS0tIDRNcmQ0SXlnd0FNL0dPamlzV1FH
            NWJpY3VrektyVkpCeFExS0Vza1F5NDQK+/KU4VCScq2JRETVjXAWk5L5YsaQ/i7i
            o1cjzuipnsSQlGj/kwEMkX3/bJFBROctmvRvRPml8yDilaxGShi4tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T11:36:08Z"
    mac: ENC[AES256_GCM,data:bePXO05r562dwklhg1Gach+xetZeQWstkrHPaDp/r+Sh6d5k0kBzUlWb/6yW+Fr8gNSAsY8nsP2Hub4gvjj5ZeWV/j2mnWibfrjOOOg2bhvMnNUL439EDwPcUaEoyciRgcyUnCBquAFYwG5Wobf47YuhsWn8YBeVBneF9S2iCN4=,iv:2us83qrrsbsGzt8Lyg4POoVrk1cDaG3hzBtxg5SRbEw=,tag:KIIcZNgJnkWCmMkqy64Pog==,type:str]
    version: 3.13.3
