apiVersion: v1
kind: Secret
metadata:
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: kube-system
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: kube-system
    name: crowdsec-proxy
    namespace: crowdsec
type: Opaque
stringData:
    HTTP_PROXY: ENC[AES256_GCM,data:FilyZg70/oUYX7iQRb9IhDb1dEplXK0j2X0913V2th5W7X/D0jg0UXJ/8aegsG8omemEY0WbhLeMAErwQlXRtuB2w6+c,iv:c8CMgXLRQa1u55gRMuCIgY5I0pvTeLUTRLtCcTiUXF0=,tag:rJyCM03DbhWQ8lrnc8TE5g==,type:str]
    HTTPS_PROXY: ENC[AES256_GCM,data:oo9l8qNZ2l6wmfO6OIUP+FRuSe9vEqbD2IDiHFfk3f4bMwv4O+5qYaJmAN8spJb2Kp72XvJ0o/F7E6uZd06ZFVVFHLeh,iv:FEIE3fxZc+mmokTpNgwsvzH0LibS2oKpRtBTGQm6Ats=,tag:XNOfZ6vkst0kwe8usGuUgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdlpXM0xFeXRKYTIwY1p4
            cEIxRUlFWC9FUTFPazI4d0YrMGhXVVlOamdnCnJobzdtV2VpUHNFUldhMlY0YStS
            cUloN1BvSzVnMmJzaUNPZnJNa04yR3cKLS0tIFhEbzFFRlJtWDlmZThZb29EMmdT
            RDc3SlRhMEhsQ3RMcVV6a2JhQ2R5ZkUKdR9vLfbrRRFy6+r7XX/QeJX3ZF5F5tcb
            D4F/8dvO+CsB82s6LY+q+L3LSFZR6dExZDX4kACn9sFzKhvXqdgsBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T10:57:57Z"
    mac: ENC[AES256_GCM,data:rQeZsHFQY5yQFh8e2wIGHDO2/RRSNy8jpc2nP+BLPItBXMljB2uiD3pl38UdsVAv0fkjgexCwpb3/NgsJHnokW6WE10KvVrsbMIu6Vw2kasICUBBA6mKJo7Mvlqz1QhHKAMUdqrnuXHZ+CgsX7p4XtYSFOHSnasdf3imjd0T4wI=,iv:mK7tRvJRTm9kI/pvJ/a98BbGsxc0rdpOaL1ziXYQ+JE=,tag:AE55KgaFPdvYOyKmal5cNw==,type:str]
    version: 3.13.2
