apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-capi-credentials
    namespace: crowdsec
type: Opaque
stringData:
    online_api_credentials.yaml: ENC[AES256_GCM,data:6q/vb8IyzJ6kOWIglsQAKHCTXJu2duX3ouV5FFfwqH0oTJtCsO0FrCpVX65amEZ+UXO1EiwWiLmTQrMSGz+6S66yvPH+5ZHxGCAnm9BiK4zujU1Km3WS0E9IzdSAcdAIJv/D0uBE5RuLEPua3MIHJ8szQuODvaVCTB4LfgSfBs2A4C6VuNHf7spAY9EKnlp7PG6lZP4Pm0ATuIV8c1cnRal8,iv:w+8uNQgv+uoBTmcpzhOwSpMfDjaQ/wpWHdC/DuTB0/o=,tag:j4dlr1sTys5uP0BekTFG1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UTlTV1JXMVE5dzBUbHBy
            Z2IydTJYZzlwY3VDYVNMZjE2Q050SDhnSTFVCmVrME9OQmRwN3JiRU1OZFVjaDNN
            NDlRQmhzeVU3aC9keW04TWE0bTlYbW8KLS0tIGY5ZDliS0xzZnVHc2pjdnJLRVpo
            Y3MyZGJXZzF0NXdQa0tRa05YdUxhVGcKZsZfG115QzNXebJXx/AuIqlHvKW8cd9R
            b2RfLWt6YpomO94/Ug8lKswwvzL6typ2G9jDEYUOAXqckjDU7RyxeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T17:56:17Z"
    mac: ENC[AES256_GCM,data:59rv1Vx8yM6XqMsp6nyWTFnoftdk58hqvA4wGxLYtI2b29evTAS+5oHxiYPMLtW/tDhnTpLn7EQ3sogPobbNWa6oe5CTTG+5x8Gi/G5MkZS00VjKTTBwXa40wFZ/7BpzjyDKF9NENhDuEeycfAwydYbJza+HvUOybGFakQoZEbY=,iv:c/vxRD5WI0khU4fM3HEY5fJ43PfsxcdbBYUaQIkpJ0s=,tag:gA4mxzFpWT8fg3BEbzJm1Q==,type:str]
    version: 3.13.1
