apiVersion: v1
kind: Secret
metadata:
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "crowdsec"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "crowdsec"
    name: crowdsec-bouncer-key
    namespace: kube-system
type: Opaque
stringData:
    bouncer_key: ENC[AES256_GCM,data:ZUc/kQBBHxH95S20GoschMUSa52x7G6H0gE6jMot1aoKfDSHvATiP6YC+w==,iv:YrplcK2mIMmzHLZImCCbDXYQRf8pRuv3P93cZEtFpEQ=,tag:a5XY/yB002F3EocAA2PFOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNzR5TWJOVlFlUDhKckRq
            MUJwb0J3YnN4eDlmWVljazg2RTBOczJ2blNzCjFVdnQrK1haaXFUUEM1WmJ1R2NB
            U0pEbFMyV1pEMVNMQ2pJQ1hJdnVQWWcKLS0tIFZPRUlPVXQ0NmtYbi9LN0libkdY
            dWhhT2VnOVQ0c1prcDR6K2pHakJlY0UK2SXsbePeg5+MWM6F6y+3TpytaXWL8s7O
            f1uuP6cc4FBm5/FtFvU2vvi/6PJP4vH4wjZvIG4ECIv1caIZPmmAzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:26:46Z"
    mac: ENC[AES256_GCM,data:ijUhfOlS+2G//ugG0YPhZXUzFtzo9WNc3uXe7eytjej5mPPfRJyKSmY5x4IOip45URdokj7oPGDVbFZYD+aesTecODKZiOfSEaFGjm2gkt0szR7R9EWfHTCL8eAhGTT3GWYXITPp3N/nXkbcslfxwq1WXr7YAsOHW2tQ4Prvuqw=,iv:Dw0Bz73SGXN2ISef1jkNzsQ9JCdFK85zlHCPAUTRz5E=,tag:3afcETDaLHqZKNw/rRG88A==,type:str]
    version: 3.13.1
