apiVersion: v1
data:
    NTFY_TOKEN: ENC[AES256_GCM,data:sDlXBZAAHTE6HHdhQZRVdM4z0jJu+SKHuzxgDouQdelpKhVab6dEPJxCOSQ=,iv:H6dSm1fsaw76iS9Sh4/tymR+uURYb7F3p0/Fj7FSaHc=,tag:xYUhjJS1wf1HSZ+lBPXSjw==,type:str]
kind: Secret
metadata:
    name: crowdsec-ntfy-token
    namespace: crowdsec
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZThRYjVDYngrYW0xdUZJ
            SDhzYitDczV1TW9wM25wQWtOSkYrd25TbVdrCmgzRnRlNXh4UEtWSDZacXg3SUhs
            eTV6Zkc1a05aNkF0dUJWMHpJeGxmdGcKLS0tIHRoV0pKc1FMOW9mcFJxSXlSS0Yr
            MFlVdEhpZWQ0dURNc3EzMVJ5Y1BuZW8Kz8vL0gpC0iVTT/mpAWQp1xbCD7PaXGrR
            VJ4EzmFgGpuCqLHVZhQu1K5XweWek8+crElyb3cqw0OGvjYF2oUPAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:01:37Z"
    mac: ENC[AES256_GCM,data:0f+x/tEJhJ7E03AwwnpnWlqcu8SWdC3zwEWF6QWOnVg6Jtq+zC1m+OmAZurMjSQaLGdB4WBPZ7aXf+riZ3okZu7zu1qjP7KYPNTQC2AklO/8QwvsoegvLa5PFgLmQWvRGGFjobp2tyAC8XLLDAj6BpU4tqz9PG8a3AkdxrpqwcE=,iv:yPNOrsfvD5q2rSZ0U/8CONDTwLcPzwxECxq3Jqgds9E=,tag:u0wrO0kphKERcOTO9wPRRw==,type:str]
    version: 3.13.1
