apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-proxy
    namespace: crowdsec
type: Opaque
stringData:
    HTTP_PROXY: ENC[AES256_GCM,data:aM1GrYpTI5gQryO+dT27d47LW8X/IJo1vMq6kCT2z25RCgGEKUu2wC7lim06/B1Oly3X5c8sA+FGT6457V+DYbP0sTT+,iv:hcOkm0xh4iIrWexm8p026KcvsoC9GsviGXNkfHUa4XU=,tag:8xaOxJCG8OPjQr9Vo5xa+w==,type:str]
    HTTPS_PROXY: ENC[AES256_GCM,data:IM2U45l78Bzz4OiDFhsMTS+jZfvVBjlfzc1p1TZ5LmeFCoM3xYN/8JR9yuvTGbLF534FfMNqMFF5sOMBZ91WvnVVX3P1,iv:rektmOxZnMIFUoA2sfEyejlhu6v7cgETyiaUYAyjlrc=,tag:RssGKR6YmIRg2EOho55Lew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSmJrclFZNjVkK1VqaG1Z
            VHFxYWlsZXRKUmIrUmtpdXNIQlpUZU9pRkQ4CktpM2p4OEJiRllhcEVLOXl6bENO
            amd1SjZYSnVCVVgzSHlCcnFOSkFRRmMKLS0tIHpsVnFWdk5GYzhyWHYxRmFVNEVl
            VXEyS2pMcm93ZW5NY0dXdEF0ZjJ5akUKdNqqS3YTI7i6sF2dTGKkfr9io5YoYo0z
            AMBVqqVowJiwZfu7aWgjfWncqVwnANHrtq07pLD2gabPBLl51FvGmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-05T18:14:24Z"
    mac: ENC[AES256_GCM,data:yzNHnKsNUjIETkCoZnlzzc9Q3fanSemnwtaJVqOsOiggzV6OR6B91dfYG0o5B2jcGV7lrQgQCY2Oicg2RYbA9qlRYRSEcoHGF55gARtnZQiLH91RdZnDnjWdZLoBmaxaLQ7QH9f7FMUwMe4UtYjJaEai451tPenB9K9zxyM+6H8=,iv:UTmnja5ADwjNFj4BJ+BhKC4OEKBtzODGXxEd4Cq9Xok=,tag:ixh7ZKhWtFGg38Wwy9srMg==,type:str]
    version: 3.13.1
