apiVersion: v1
data:
    ENROLL_KEY: ENC[AES256_GCM,data:bGUdsCZw9eiTeaUNXA2Mtn2fG7okSFzh1sJBWn7TEmUZ2lyC,iv:mf7M+dyqzfSXLtwO8mqlMLMk6z5+deIYIRbX7Qu8v/A=,tag:SCnusGKBLtMYFL/42VFjYQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-05-31T11:26:15Z"
    name: crowdsec-keys
    namespace: crowdsec
    resourceVersion: "1759223"
    uid: 4185afb9-8ba7-4c8b-94cb-0e3e86610c06
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZFo4b0FBa2xncngvMGg4
            TkNBSTVrQ2tJbXBOcHJDN0dPZHArMnJ3OFIwCm5mVzRRRkhMTkJyckVYaTd3eUhZ
            N1VrOTBZVkFWS2lMM1J5UTd0ZkQxaWMKLS0tIDIxMmZSMXBFWUE4aHAzeGp5Q3Ir
            UlN1Y3JSb1VRWVNXVGlIYStGU05FK0UKGVZum2bMlPDFHXLxjgNz+o2XFvzaq1wW
            jFGG4DZQaggdrduZ5zTAQSqeI2VoBO3LLqgKu6LKvRKOtmMFgeMGiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T16:16:56Z"
    mac: ENC[AES256_GCM,data:v/DQpq4qkh/F14CPn/AfXM541AL5ImnXmodCyMuR/ig3ZDyMLYW8jMR3y3Em+bSynKhosNYsb+sTzuh3Si9Vs2diMu5N8sCbNmhcDngSANn1ArAkvFgcqrYdOZ25wKrlPDwzGqcimYfwvAf+i8II8CcmV+PrJYMUuJG+h26vChY=,iv:jis5r7qFPXHsaD/rmD+ZprrIM6gAUyUfYEjPR09bReo=,tag:qOpVCNDe2qWAueIV1/4BAg==,type:str]
    version: 3.13.1
