apiVersion: v1
kind: Secret
metadata:
    name: crowdsec-keys
    namespace: crowdsec
type: Opaque
stringData:
    ENROLL_KEY: ENC[AES256_GCM,data:kUkBAPqJsRHghFj/rV9j3gmFBiEVScW3aQ==,iv:El4HnveRXY77ZSKtpiBYcRCi+71SwENX1DoacmYVXV0=,tag:PruQxpDUK3aP4PtmkygzwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRTRXOXlTNkpTQ3V4b21x
            QzFFcXpDcFlGWjVKZndqNlVRcTlsZDUrb3cwClRQd3hHOGdScUpPOE90a29IaExu
            V21LYVBSczg1VkdqcG1JT29sYVlBZDQKLS0tIHR6WUVlTmEwWWoxbjJvdWxCNkhi
            N1p1K1JhaTJodWx1eCtyMkM4ak9iWXMKT9Eud1TeWqhXmcLzOofS0AVIbem8l7ea
            hNCTjx6ZYV6fkABF0F1mVPaDOC3mTyU1iz4SO2JXMvTTFbvulmommQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T18:29:07Z"
    mac: ENC[AES256_GCM,data:aYzR9YuknzveaFFLfRBogg558mN3Ora+CJ+JY5szdKyFrAwhCvEM0OPgZtvXkct54ewRh+ie3Bo3s1bn/29klWb9rdRWw0SI/tVmAkUdm1Nh63YKHfwPtUSRR627ffUbHSnzx5UZ4JRn4axg8AsCkN8A1yBQKZt0GBBLh6xWQ/4=,iv:FhjqZ22iZujmTrV6ulKXhe5iYgcK9ltRCHGsGbnXwVM=,tag:LHNgnv24oRp01uX1Cn8PXg==,type:str]
    version: 3.13.1
