---
apiVersion: v1
data:
    NTFY_TOKEN: ENC[AES256_GCM,data:anNjyt9YuJEIipn54GV+W6aJx922X5H76Kr1vt6RMc0WTzqf+YLokUtSM8Q=,iv:8w27GOMYF5CYOoPC5PZo7BbNaUhOcRh3o9pjZzd7i9g=,tag:Iq/uZ6L2hbuCOmrL9KR2dg==,type:str]
kind: Secret
metadata:
    name: crowdsec-ntfy-token
    namespace: crowdsec
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SjJRK1FqeDJtQWw0NjN2
            cjBQdGFCYkRjMENZV0thbG8vVEF3bFFLa2lvCmloRUtwRVQzRE5Ec1F6V0IrQmdv
            RDcyaUY4T1Q5WEIvT3lkTjdpU2RCWGsKLS0tIFBoc0lVWUpEL0lRc3dIS2lSMDNO
            S3RwMUs3R1B0SzZiWGdIalo4UUNiU0EK2LZcKe1ChIk8/Gg8jI1o/zKpf00f9eBb
            FwPzZwWK/d6gQ/pOO5ki2ms7vGZNWTIslas2VJIyLsTQ6lwwUKeIXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:23:00Z"
    mac: ENC[AES256_GCM,data:SLGSdx/8UT8l3YbX7zMOmE3+hexqlM94g6w+HIPC/vz6nWf+bM9fdjAhMNerlKkpV2gomeMezGfkO4W21iIEe4MjKvChsziPPYIr1wf9K/EUsEIlGfoITQ94jLKNS4o2GSdlHBwCYTA+gaOKhLhirSKI8h2lCvtoF+xKZDSB5/E=,iv:ecotVuJzGUN6mIWkfWH8W33j+hSnRAA8Rtepl/bEmtg=,tag:sthgkXu2j6OdTdvCZZyf3Q==,type:str]
    version: 3.13.1
