apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
    name: zot
    namespace: flux-system
data:
    .dockerconfigjson: ENC[AES256_GCM,data:GcWGCSR2wfo0mqRs8IFXpURt8W9RDL4ea5bqrt/qHmhZNjuCMsmpuK6Z3OxfutvQOdR9+2WZDf495oEaJzX1xS6zb8CG+REBhMEJPsUQSqfG+FppYV8JVdD5TyREYzmNs7K52b7PH/DKvI1ff7RYzAg1xgRCe0eGF08lNw9vG0k+Nd0S1aAbVO/nmjbTXGoPjtYFbhe66EYXVZm3R8TYPknmUeTlETXjZCwWZpetnFo052CkdOzFtyxuC5t7BqUdr4N/y5BCZJQXDLfVqm8J7F4CKt+EfXj1,iv:1LbkXjfJ6MnYN4a6CUspU5B7syT82CARonRuJfu4CVY=,tag:z3axRqG/J0w50eiOgACJ8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUDQ4dy9oYzQ2d21PbU9j
            NGczdDJNMTlwcXJBdExXbDNpOVFZRldZb3prClNTaktXdWlDNVJmNmdDWk4yVVpk
            Tmt0cWhDVWcxMkVqWVNOcXo5eC9XdzgKLS0tIG5iWnZvZllkZ1cyRTBsRjM4SVly
            MXQ1c1V5V1JZejVZdXAyWWQvd2tVaEEKICJ+aTuZRFuhrdTA+hDXpVoRfIpCbNvv
            wnqrzTQXdYxlVjgb4jyzhwOxf6MJUem/rrodS+kHGWzINg94sYJ/lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T11:01:19Z"
    mac: ENC[AES256_GCM,data:WwFlfYdRiNzJmJN8fA5fYL1teysspEFc0XQwpYKEfMI4y6leP+z0tR4/GboOkyjR9vB8dylpyBb/tINhUusQFjSobGDlO4vuCLBbUsoww6mTugZsyj98QHvCVYjF/YqDPp5y9mxe8zXH9CDIMMHDxC5SkYF+ClIaTkcUxOx/Bpo=,iv:AwBsyxFi4VSGL6tOSKDUzCKOVlxj2KB4y64G4twnZao=,tag:jIb5xcZAFzeqgAVAoogw6w==,type:str]
    version: 3.13.1
