---
apiVersion: v1
data:
    key: ENC[AES256_GCM,data:YJ21oDadkLg0eOWm,iv:r7WZoOaPAnDEin9hlFsQTdbB/S2BtYpKkYNC5eo//sk=,tag:WEwTAqAe7Go8cxlq399RaQ==,type:str]
    secret: ENC[AES256_GCM,data:EiMqW0DK5EmUAhkKNeXRcwaNkFZ1L4oXtJe/PT80NqfDqQcSjR+F+4vCNNr09Id4ug/jTPExnN//jTc0tZm2kd0k9/tmA5c2xeRP9xEibJCqa3cXnp1stA==,iv:OZLWVCdcJMB5smkbR+cvjuwdAwzjb/hMd1fh/uLqaGc=,tag:Vpt6Q0oJEOw7J5RPXjs+yA==,type:str]
kind: Secret
metadata:
    name: forgejo-authelia-oauth
    namespace: apps-forgejo
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZlBWWW9GZWcrMmxqMFJm
            Y0lJVXJLSkFmV3ZRSkNvVTcya3dxME5MWlFvCnBJSDlBS01vNjlxa2IrZmptbXE0
            T2NSbkRsWVRGZDZRZnVUVjlKYVZVNjgKLS0tIDAzNWVNTGVqOEY5UVFaTUtySUJK
            UnZsYXlJWTJTb2VqYW1rV3EvdWgrK00KlprzDYWF4SyAnz2ZWj4h0E1jHzzkbMOF
            v9dD0Y0vHjJYapiKqq2FeH7luMPt90atYHv77mG9ce2Z8keLnsgTTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:23:00Z"
    mac: ENC[AES256_GCM,data:Q8h77k6Ph3zG8WXRvYw4MN2iO/LBLQE1Uxg4WTGjZtTMB0yylBnFCXvLp4q5SfQuGrg9euGWweBkLMcYy1MWayfdu35LoMVZ3M3jfJK4bJFz3hMO3eEfHkKZV9yQ+fzAQxcMIPU72DbVBPSqSq8wXCIGn7X3/Fn5OBRZl+mH3gs=,iv:L743e155w/RPHAtTytjuCfDOnEE+iTtg62wbtDxAma0=,tag:807Hkim5XOzYcSQ0qdpnhg==,type:str]
    version: 3.13.1
