apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-init
    namespace: apps-forgejo-runner
type: Opaque
stringData:
    CONFIG_NAME: ENC[AES256_GCM,data:EgjAn19GOCWWq44=,iv:xMiZHkGVaeugE/fdH8wzAYCngeMz4SQEM/usWiC///Y=,tag:sM6jAXQdV73xy8m7rAkg8g==,type:str]
    CONFIG_INSTANCE: ENC[AES256_GCM,data:I8KiGjCFI0GzCN65lDNG9ZUZZ0QPtI6/2H/YLH6L+nn6Uu186M1DrDEpgJ1eK6duzgrIz70IMw==,iv:IUtSA3MxKwNJuLamv3IkghKK0bgTm2J3bpeB93mEdmc=,tag:n6NahGeUU/H1Zwlq4zwWUQ==,type:str]
    CONFIG_TOKEN: ENC[AES256_GCM,data:0iIVaskOMEALOCm3PrfEscScBa3Ju00pTwgRJBdqXl2P5yytMZ3HdA==,iv:vF/yuaTmYH7ElxAPER28IoqNf/J4AuWfw7hEKPISAm4=,tag:bwkjikCkXfEUFsmV12sN7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMEtaWGVHVWVBdkdyYmZs
            dHdaMHV4UjFibWlDc2dSVXI0MW9RZ00xdG1NCmZEd1NpR2xpZnZBc1hMY3I3R2pP
            aUVsK1pyZUhCdFkzQUdYeG1zZmdRc3MKLS0tIEZRcW1VclRNcmZDT3doa3Y4dlF2
            cXJUVms4Y0NWMVRNTEp0WVIxMTBzOXMKBdLqrqfKoitMN/t0E5KiSX2EvlIyQWaE
            ATmML5EAO/Pqrmg04qMfVaTVWUCBtnrD/yDF9Qv2c4G9k5IashaVBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T16:53:39Z"
    mac: ENC[AES256_GCM,data:bdbU9xfCra4bV/4KzY/Ym/6/I8K15ZqRh1aZ/ZPQryt6XHZ0ZIt8gZx6E2i/QdMSOATe3pc9b/thj7vxcX/JM0G8EcL+5eSlkgwmMUmzuD+ip4z5cdWIieTxJIzY1uz0JC0kddusuomnT0DHCVawWtKUZJkdjFe5k4FE0ChRcAU=,iv:jg+Oa9W8sGjRgJwBp/CDxCd9jiaBNsTYod+z1/3M2Z8=,tag:uzTO9sYtzFARlrVL8KlKrw==,type:str]
    version: 3.13.2
