apiVersion: v1
type: Opaque
kind: Secret
metadata:
    name: targets-creds
    namespace: forgesync
stringData:
    FORGEJO_TOKEN: ENC[AES256_GCM,data:A0Dxq4QOvHLyzgNu3ZLaSjkTF45j5bKpZve4Sh1YgCdt5dM4tfmzNA==,iv:3Z0yYWDRXpZtcdmlpwmXKrtGBnUG+ANIYPdiCRTMseM=,tag:7DtyTfvXYf0o6KpXqiNdsQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:LdOcGdsN66Ts/QcxxjkmC93KGJQrv0Zjz8+/yh0NQfSKCUzGEYx8h5VQJI8yfJ0C+KbQl5HAL5AG7jOUpkm0ADpgyXIeV7znWdhm4AIjnxnU1AX/BtmQOjurjKRW,iv:0/2N3Z7Fpn2k/wU/7CBSN0HB5Qg4xGlo3tLQ3xfwmx8=,tag:AuVx2gb38p68kbn6oi4VDA==,type:str]
    CODEBERG_TOKEN: ENC[AES256_GCM,data:sgyZm6Y2xPeRYufCxkaZNg/Mp/fa05TiGJH0UbeZOT3+optv9JkBjw==,iv:nQlZbYhoiyAijnIQjDtmdDcdW1MTekT3rhXaoVj0350=,tag:a8jMVHSqErxHCivT93qrBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNExFdXUzUFNEUkFyRHpu
            Ukp5bWw1WkI2bWV4YVVPOHo1dUFkSXVtVnhBCjBKZ21hSWZFeStrV2JJK00vTGxJ
            WXpyY2g1dVFUS2QwaytELzdWRURpdzAKLS0tIG8rRTVRZ2lDQzR3S2xyUXVtMEZn
            L250YXltTXQyZGI0bTVmb3g3N2FSbnMKxZspe61P/Ov5DVxHNHx0Cy/0xfkoV57C
            xGMzkjpYxYjNKUZduz70O3FGK5b0bp7VU/Q6qqnbUkR3vEf0GKPCCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T11:52:45Z"
    mac: ENC[AES256_GCM,data:mT9jzYdtUPEqGr36vBrDozVQF5fm6MAt1ThYTKzNYNXAgFppDXTBgQauTwEXjo5oN+IOryO+ykrmWd3hzDII4Ssve+GHBg1aXEjJPKFYxoyqqX2PvS5Gb/0viPgJwHHwDSLZRPA2JAuHb39rgvVC/6jAD9rFyTQWUr3ZIIQZ05c=,iv:YUrTAwnaIizeYPdymyGbhkAQ8wKR+Omsa7+x8ZoOLkE=,tag:CRmsKJnH9KH3S8dUmVblcw==,type:str]
    version: 3.13.1
