apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
    name: targets-creds
    namespace: forgesync
stringData:
    FORGEJO_TOKEN: ENC[AES256_GCM,data:A0Dxq4QOvHLyzgNu3ZLaSjkTF45j5bKpZve4Sh1YgCdt5dM4tfmzNA==,iv:3Z0yYWDRXpZtcdmlpwmXKrtGBnUG+ANIYPdiCRTMseM=,tag:7DtyTfvXYf0o6KpXqiNdsQ==,type:str]
    CODEBERG_TOKEN: ENC[AES256_GCM,data:sgyZm6Y2xPeRYufCxkaZNg/Mp/fa05TiGJH0UbeZOT3+optv9JkBjw==,iv:nQlZbYhoiyAijnIQjDtmdDcdW1MTekT3rhXaoVj0350=,tag:a8jMVHSqErxHCivT93qrBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNExFdXUzUFNEUkFyRHpu
            Ukp5bWw1WkI2bWV4YVVPOHo1dUFkSXVtVnhBCjBKZ21hSWZFeStrV2JJK00vTGxJ
            WXpyY2g1dVFUS2QwaytELzdWRURpdzAKLS0tIG8rRTVRZ2lDQzR3S2xyUXVtMEZn
            L250YXltTXQyZGI0bTVmb3g3N2FSbnMKxZspe61P/Ov5DVxHNHx0Cy/0xfkoV57C
            xGMzkjpYxYjNKUZduz70O3FGK5b0bp7VU/Q6qqnbUkR3vEf0GKPCCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T14:15:59Z"
    mac: ENC[AES256_GCM,data:W4FfPzQoaXLNoi7cgf8j3+O7kpWsdAM9oZ5tqk9JH1hz8vBQaM2YZo1MeeDzlrCYIyDWh6byfwUoVZ1+toMP/QJCBqNYDKFD7o14ENuhQZqimVg/L/zC5GGLdgPlDGAQw+tK6Y7TAu9aP3kyWY0v3O9hysKU26G4P7Nm5Vtzj8g=,iv:miVOWK0TUWeTiy/cqrMM8Lwf3vygkBVPtjGSKZKNn+s=,tag:1kanXFCsr84xJ8/RlXAn4A==,type:str]
    version: 3.13.1
