apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-init
    namespace: apps-forgejo-runner
type: Opaque
stringData:
    CONFIG_NAME: ENC[AES256_GCM,data:EgjAn19GOCWWq44=,iv:xMiZHkGVaeugE/fdH8wzAYCngeMz4SQEM/usWiC///Y=,tag:sM6jAXQdV73xy8m7rAkg8g==,type:str]
    CONFIG_INSTANCE: ENC[AES256_GCM,data:I8KiGjCFI0GzCN65lDNG9ZUZZ0QPtI6/2H/YLH6L+nn6Uu186M1DrDEpgJ1eK6duzgrIz70IMw==,iv:IUtSA3MxKwNJuLamv3IkghKK0bgTm2J3bpeB93mEdmc=,tag:n6NahGeUU/H1Zwlq4zwWUQ==,type:str]
    CONFIG_TOKEN: ENC[AES256_GCM,data:QvjFdKTEaxnz4TFa+hENOXWEaS3KXjqzyLMqq6LqqRCqmA8D2ENTpg==,iv:T07hYjkYUzDQSBM/8O/grVV1rV+//SyKIg0rKB2tjUM=,tag:C/4gCITiY4ZkBHIH3i1AJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMEtaWGVHVWVBdkdyYmZs
            dHdaMHV4UjFibWlDc2dSVXI0MW9RZ00xdG1NCmZEd1NpR2xpZnZBc1hMY3I3R2pP
            aUVsK1pyZUhCdFkzQUdYeG1zZmdRc3MKLS0tIEZRcW1VclRNcmZDT3doa3Y4dlF2
            cXJUVms4Y0NWMVRNTEp0WVIxMTBzOXMKBdLqrqfKoitMN/t0E5KiSX2EvlIyQWaE
            ATmML5EAO/Pqrmg04qMfVaTVWUCBtnrD/yDF9Qv2c4G9k5IashaVBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T16:59:57Z"
    mac: ENC[AES256_GCM,data:/jQgaNRBuHg7qjyIfya8paQWGPQglPOj+lMcjwAyHr87kz0iJ/b3Jp5W0r1JcAdggkKNtNYlxR+DzF5IuhP6PQlExiUT+N1V8kG8oCH5+QCSDrZNBTDIjZgHUPtP8mWgF3WGDSeG6n3TATH9HyhqQmkJPXGIvLesgqxEUesc/Cg=,iv:vZx/kBaOt29EKTlrK3wVXw/+fU2q3H2e/YnEws0M3Og=,tag:jNFAPtjmuNPwJSRY3z1nyg==,type:str]
    version: 3.13.2
