apiVersion: v1
type: Opaque
kind: Secret
metadata:
    annotations: {}
    name: targets-creds
    namespace: developer-tools
stringData:
    FORGEJO_TOKEN: ENC[AES256_GCM,data:fZN7xz0r3Joq02bz8rO6SdTtOQvdnu+nwYRGLfPDdKa3eSZtdp7T6A==,iv:i/c7pJhFi/UjbzFs2zGNMrY4+LqLyF/50kbEzk0dD1U=,tag:f3sO5giMxJivTT9LCmqQ6w==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:DBbi7EUhUjNGL4zh20eAa3t9KFrf7CKNrbVukgytpMBRag/1bn/xS9zWfYoPuBwK3JvKLjmKmiYL0AwNE/5iQ1rKVs5wYcqkuzOnJtzx3BFSYdRECHZnuhudXCXw,iv:C1kAuEy4J4Imx5Sxch59/zv4J/EJz+x1lIH80MdTTvE=,tag:lrltihpPGXCTgZX+voVO3w==,type:str]
    CODEBERG_TOKEN: ENC[AES256_GCM,data:9kbF3Lp78J72DM0ZP7kLigLVfVLKGS4bs5j/h124ICXiG40tLapleQ==,iv:OYvml+dhhSMEjEBDJnszhLVo0sE9ndHgMngzsO38nOA=,tag:qnpftp9KOlutAIy3Phahtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNjBUVkV3VG5GZXF0dWI5
            QUF4WXdRY0tjNlNHWFlqbkMzRFEvZDRPNVRJCk9HOGc0SEVxbVVDU21mR2R5aFlZ
            L1A5WUNkenBpbUNjMkNMR3pFZk5EM0UKLS0tIFFyM05ZOFV4RVRqMkJZM0xrMnpw
            OWM2Rk9EZmdFMlBzWm9WOGs4bDNGK3MKQe1mJbRuituAJzDp3QCkFof9fyZX+qIP
            RnT+h6YqS/q0MmRse5Z4XhPAgirFKlLVWtP5fEHX/Kzv2jSkZaRXRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T10:42:24Z"
    mac: ENC[AES256_GCM,data:/Cx/cKDLJN933U3GAfiYzlIqEPS07wAAvSly5YEcmu04AJBf/zVpGfTTldWWksZlRaa7wTJUCOQl5kXlPhsqooHNnnh2QAZxbAZd6s7TylJL65CEAnEp32dEzWOQQGfV976GMRfqmo7NAb7nH867xcn/b9ADZwJTX65ZmEFltkI=,iv:P7338cBnV50MztucF0GuE0kMLM1dBcZb7Vev6FRHcxw=,tag:EpvOI/auIeFHKH+3BJJ5ag==,type:str]
    version: 3.13.2
