apiVersion: v1
data:
    password: ENC[AES256_GCM,data:02hn5l4Lv47OiAtmJwUig1nNPrLOn33Jcp1QZiCQhM/SQKbAmRh+ijQuoVs=,iv:Q+RbrXyzC+uwUQ/vvaMxHL8p0WpkmVFw/N9cESdN6sM=,tag:n2MTWjbKL9a556+DnkUJXg==,type:str]
    username: ENC[AES256_GCM,data:s5mpNydQrARHiX5mmg5zuA==,iv:gNvhTCLy4wjUnTbUXufOrNemx6RuTwAUW7wnw/kmk44=,tag:gKRPWIgqd8QykrX91MD2wQ==,type:str]
kind: Secret
metadata:
    name: forgejo-admin-external
    namespace: apps-forgejo
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVVNPcTNEdDVBNWY2TTl2
            dFZjMFBUdVNRMVNmUk5XcTIzakNoNys3VVZNClpmTFFTVDRlOGpvaWxiWm00cWhN
            cDdGVTBZVVQ5ak9jL0VoM01nWGJEMHMKLS0tIEV3ZWN3ZFJiUTBYaGIrSXpjYWRC
            WjVnZEdWQmw2SmxrMEJJQlNIK1dCaEEKd4sDv5stiVgdTO2QFBsEWU7QCeOZ6A3e
            Zou/kzBBaBvaeUm5s0vQ53qkeskGGDxbzGjc/zFK/e0TSGZ5Kf+/kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:23:00Z"
    mac: ENC[AES256_GCM,data:x1i/dIPhU84s5VjA7G/uf0jbjqWolZyY4mq5gWcoO2ykDYsCMlAvQSJfOkCm3ledn3L27aHI++otRdOCSLt8rHeTU9sca4klBDa0vvbtn9fqadQQshxkrmAPl7esH5zorno3vH8Ep5e71XPfO+aQ1YRUwY90heiokwxzRFB93og=,iv:aj3ortFFYjn/mSGX1VXR2CpPFkjfRBUTskOE/KcvV74=,tag:PSccfxhULiwAvPbZvC2r7w==,type:str]
    version: 3.13.1
