apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-init
    namespace: ci-runners
type: Opaque
stringData:
    CONFIG_NAME: ENC[AES256_GCM,data:Wxb4Sbvz/Ysunf8=,iv:AFDz6FSyph6wxFkt1ENARN0t4Wr0woF4EQ11HIVluh0=,tag:hLLoN0E93cJeohAUFCHxPw==,type:str]
    CONFIG_INSTANCE: ENC[AES256_GCM,data:Lgl8VC78DKxCT2d57CF2hcMnNQkQLBR2nm0BylprYNFQ5LEx3/pyHGLzuBA5GMeYzDlI/YxaQAktmw==,iv:EI/8yQkSMKXyTaOz2qevEAITYrmbbpE/hsVZtryXjso=,tag:zW0EFimb3Lqy5PLDLS0muw==,type:str]
    CONFIG_TOKEN: ENC[AES256_GCM,data:MI2i47mkQyPyYmL4spIf1ice5QuUkK9hJnclr84ecB/3AvVZ2kjfbyz4nw==,iv:nIpDhrgHTVDgNQy5RAxe8R5Aj7YRBDui+0XLOOgdiB8=,tag:OKHqAVvgGkFAN5JwCOmmaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNzZESStGR1BCSW53bmtn
            YVJaVXdONGlDZEdBS3k4VFBnR3JoZENFL2pZCmZKMmdQL0k3TTlxTHB6VXR1V08v
            NmhEQXlPQ0JPNWpUQnlydXR4THRYRWsKLS0tIHFINW5OcUhlYndpQlVxUFBFQWFI
            dU1zMW5QNnpjOXVSTTR0WG1tNVZJc0kKL6u07e2bwLURRroF+3PrNzBP27pa8BOh
            7oZEnjXKqAqEkJRtJbYQh6MW188eupEOaEtNay0O003oDozr8C2I5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-29T14:07:24Z"
    mac: ENC[AES256_GCM,data:/74+8HkMLlt3ZuYL4hpJ51EqyEkVEKTzf2DrhNAcx/t/xauxQwjiW/lFElhJjHJuIjvySjfIDisvqNkHKuiLeZb/3iSRan/XgocFcLiKZYbRgWaZ7+vRMP8zc5n2ldbAZgvfTofYRn4k/NvvHL1KUxM7gNc7treIRjDC3gwL78s=,iv:MnubImv3aYg2ARrSM+iMkBhAU9MjnDG2tHbgfnUHBKw=,tag:b0T9q3dhfEOcmNsfHPceXQ==,type:str]
    version: 3.13.2
