apiVersion: v1
kind: Secret
metadata:
    name: forgejo-authelia-oauth
    namespace: apps-forgejo
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:YXaq4ymAWA==,iv:E+m38dDAsgF8sqfy+UQWCIMDiHEj0edM/mpw99SHaRA=,tag:jNO221INHQRagjrdNbFjYg==,type:str]
    secret: ENC[AES256_GCM,data:sqvXqPk6omG/jPpXmUBRYLAlxmXMcRmMXQy25nZZfhHxQ6anvL4ef9J4tT7Gl0vSqhCyd5VrSuEMi36OqzbazQ==,iv:ir68IvXQXD8bbfTaK9RzCqbuwJqRkJK9CoJsMvC5Clw=,tag:N7Fbx/fm9GK7bKawDofu+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMDFCeHpKKzJhYkY3TkNQ
            bEZxaVNvS0RrRmJUOUE2RkxsWWNNUkVseFVFClZGb01HMWdRZmhOaWtXVXYzb0pj
            MEx1T3QvOVExK0NhTXdyc1lad1ZkM2cKLS0tIFpJYjdZbzdHOHNWN1ZlQTcxZkVN
            ZFNuU0dwL3F3Sm5JOW5XMkZFcWZCM0kKDgQCMAIgJeBDeRfIBK4AaoFIBDMCeCsc
            ceaAX+HQmlTcbLFJ74k9cKvP/T6fLhYzyFnhMLGLfl8YcvdNcemFJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T18:29:08Z"
    mac: ENC[AES256_GCM,data:wtgBnYsycW2K6fUiTFD/vteyolF3zKV7t9J0OTv4+JPgLpVnPTu6SkpKG29K9aXX/c3DF8fzACJouScozBvlfBtqUMjuGMd8UWnCvS5+0urM/iA8EbTCrlYkCTeXfuhZMDxY7rL/MCDSoVdml1HnJZkwiA6FTWLbHBo/6UFRxFE=,iv:0bv6e6O5Liq9RPkX/VbumjnEqVpA4zWy9Kl5qI4g0Jo=,tag:MUohHppMyN+JlwaRPUrVpA==,type:str]
    version: 3.13.1
