apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
    name: zot
    namespace: forgesync
data:
    .dockerconfigjson: ENC[AES256_GCM,data:7BwxKVAKPt3dNDgBcXor7IyH1mfK7+/mX1zLtTXd87WJ6cDOJ0E7lCe/eRTnbPfn5SRlKhC5PkcNiFKHFPXUXtQA5PNv8RNMuxtXLWswjtN2+ma3zaSiQjo0erTWz0ouXBsLjJDZehkD8jxRG0jeL02b0Tg3Il8bW3ZMfgLlFF5VGRqGbP1BQJwkoe5ehMBOwsuERI7qYWX16lyVZoVAM2OSxpwQl+k6dM7UEXwbTOWEYJfP9BebTeZeXnLgnOd59Q4puMLMSYmtjO6u6S8xOsSeGH78FXLF,iv:ELuKMITBbp97C1pP+t3bNsQ25GmtaC0otmqfl54v45E=,tag:d5uHRC2DzaTuxSSWkfNReQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMFFjVUM0a0h0eERvUjJz
            SzVCSlFTVUZCSDNGRXdERzNpeXJDbGM5UDFNCkdUcTAvdWhocnVlempEWlcvTGly
            TzlMMGdkT1FsbHpnbHFmUmExdnk1SGMKLS0tIEdHSnRITFNKR3Q2TXMyMUhlTXE0
            Z0MwdEtiNmw5bWttWnNLQnhDK0tmSTQKAqUq0PQvdHe7kOzb0aDcemtD5vx+QivR
            NvrR10h4VUwXb1niJeYS/wuedZnqeL/o9TqWmf8AkDGwlKltya72tg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T13:58:52Z"
    mac: ENC[AES256_GCM,data:LX4mKGZ/uH6aP1+TSddLpuZCvOJ0EMgt/MF78IYquFKmcB3vypI/llh0PWEmE79w3gublLdkh/kPPIfaOSw4499BMEIKynFgRmmJDm+hiIRpTLBVIeBl66RCxO9m0LQBwqqZ0DMLEoryXuq/FJ0A/ul9Z14jME7Db8Y8dhJjlFA=,iv:h55U8me7bohR86txk8TNADhvI3AeY0jv9quATWgbxso=,tag:qUnp3MUbA7s8KWpB6jJR9w==,type:str]
    version: 3.13.1
