apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-external
    namespace: developer-tools
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:gzIbB6dNiO1imMDKf9dsXMcLmHYZzXBCHFMU0NYTBfU=,iv:80rWwOrqFZHhNSEeUHOqWsgPvRWU4EFV6qPeQyfgk5M=,tag:vYm8v+nOSYFAuWLqx6epfQ==,type:str]
    username: ENC[AES256_GCM,data:pJxotJdGROxyYG4=,iv:OnwGMkA+/VNinRCiWIIZJ/NmOy/a1pACq8WIwnlTVa8=,tag:7uP63giR6L5P04FycxCNtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSDFObllER0VIUEVOVzk1
            SE1INEhpZzVKbmJGVGRmNFNxOTFmQkIwTGtRClI2dUpCdnM1MCtQMHJtQURmMldr
            VDFoRWMrT0UvSlg1Z0ZZL0pCdjg1OVEKLS0tIDA0WnBPMk5SU0RlMlYrQlYwRVlQ
            ZTdXYlFIajQyL28wbFprUDI2RHBiQVEKS1DLNcJ/OzLbtAUks2wrXQP4rNji+ZFh
            TAQdeRfsP/9m6OmjeHeFuVGBts1PxccSiZyfW7wG6XXnCWPJonN+8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T10:00:31Z"
    mac: ENC[AES256_GCM,data:Eyr6iaoo7NGQ47rX0z770y1ZCMMKF3hiuI8PNJDnIr2FuQon1kX+nb2TY7H+mTL7xJwxMfQY3CHpm6nP+ZFEKqkdWUn66eGOrGAp4zOpoRu/frJiliJK9eu9roUiyqb+kKN39faObE9nuxOJ7q7lbU6ASprfU2j9Cd6SVsxq06M=,iv:YIzd4GbvH4AL6yCKPs8kbhP3lhhfelMxwQcrpIPjZnY=,tag:Om4H9MbGRpDMHP6XEYcOwg==,type:str]
    version: 3.13.2
