apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
    name: zot
    namespace: developer-tools
data:
    .dockerconfigjson: ENC[AES256_GCM,data:/0s4LZASEsj80dmMV5/osQs6rjttG7QLticIjczFhSSKBKli5HfuJ4In/QV3LSHcn1egcF3YoyOVrL/lW/C+MF2XxC3Dn7Pqh0IRdHpggRub2hfT51nzOEgEjytVlrVOzOzeanupyNFv+5ep6K3I16LE7tqAUdCjAhFjaq8kSE0/l7JB6HVssW1pB2uqUWrsJMSR838PTl0EnmrYE/ONGAJPnJrbI+hl/CDtg6qLiphd+dRtK4yOhqFN4NZ2KiV1JUzspDVTqnqlW50M1HRpqNh//wFthB2l,iv:xpkH97F7alRLLGNt/52AB7ZYJs0K0vzCDCNoNQmPpIg=,tag:VgOQ3W7OdPSi2yhnYpBnjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMzFtc0FvcGZUQXFaejY4
            T1RYeUZKMUFqWUhFOWIvUXhrSElQTERKMlV3ClJLWVRIU091d0pCQUY2VXFxdEda
            RTFpdkhzNFM0aVdQVGw0UklmcFNSVlUKLS0tIElFNWYxUWw3V0Vkc0pDR215Z3l6
            bEp4ZmdsSmI1UEVrdi9WdGNkdDlRYTQKmVNNpRynr4cAlDdKn8KZGHKbiUr0Ud+0
            khsHZ4T3s9qfsa8wgJnMvQUMMFw61//Nh73RYGnp98vQvR3At6tdhw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T10:00:32Z"
    mac: ENC[AES256_GCM,data:/HC+ONSg0//RhZs9Pe3uArj+LKEQ9Zyx4K4sU8OzBLEBr0VYw1Cn2dDjgoEsxtOTIpVcxmfhbxdGNQGrXquCEJaQwVp4GPXAvl83iaFrQ6s7U0Ilxd/6tFl6/jTX6AM8a1daUiWt0UKarEZtvoKFtu0GULqi4MGjv6F7emY0Els=,iv:NT70zfX0mqnDgYVEkeonr82snSowhTsIGBgOsHfDFMM=,tag:eWnGHSDUg0W87tuKHMFdbw==,type:str]
    version: 3.13.2
