apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
    annotations: {}
    name: zot
    namespace: developer-tools
data:
    .dockerconfigjson: ENC[AES256_GCM,data:S46VCpEGPOejYJNpSjQ13AHCjc1NW/c9TTARKVK592uD18E6jexR9bQoB6unQRvgN+rIfKvRm2rRJV2idohbKahOW6IU0SgOdr8VjC9ZJu7looaDfFKDdEba/OX8Gx3RUUWEajLOGlcpeoTBbuTHU+v/qHPZ9TyxU0HXGnkyQ2t0QiGZnjNSGL6du1c18C4jVOKxNQ63+9CvRaUYjLld2OKxpGctPZyee7RIEA8yShufUqgGc7jSo4bZlzWGQTvAh7pgHhahNNdINAk/zgZVoe/vXmCJxs6q,iv:igIwVDCy1O7neyYwI0k/mXor4w5Kfkg/kV6ruS535ek=,tag:0yQ+xE761IgU8u/S7ztoMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeDMwSWphaldETW1HOEQr
            QjhXeURhcGh6QUpjTVFXRkY2N0VQTkVQcjBRCndlSElzdkVnVDU5dHhvb2I1UXZN
            M2RIcncyZFBQK1JJcXI3S2F3QVVSYm8KLS0tIG15ZUE5VEtybUxMa3F6OG5oMFlH
            MG1STWpYQzhhZys1YmFqQTZ4d0pMdncKtuRE9fcHoWCQwtK442iqHG/JJRgL4aUQ
            xu2q3bJaigtLtWBIPk7tlufa216tpUyj7o6EzARdKQqOykVWO0bJCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T10:42:24Z"
    mac: ENC[AES256_GCM,data:buBhhFJh0xvC9XevzDkT/gq1EcPacunyKNrvmng2Sr36OWAl+vywH9Vg58HvbPRstsGcmxcmE9y1/0+Zy9nJwxzpBAFm4qSRtc3WZEanh3ddHv18i5QFGcnjiKmQKiAvkzaogpSdS0o93u8fOcDZvyLNgZKImFE8ycTRC5CxOPc=,iv:oYMC0AVcfEi4CEpQVNkWF75RD6g/JEyoR1jWggFnT2Q=,tag:9Cc0klrhSV7oquSg6K5KXw==,type:str]
    version: 3.13.2
