apiVersion: v1
kind: Secret
metadata:
    name: gloria-config
    namespace: apps
data:
    callback_url: ENC[AES256_GCM,data:hsJIQUnWyrKOPztEkMCm0MfyOviy1XxJ0WPxNQd902kb9sJBh88=,iv:w86xi/RejzmcKe7SeHsUWZ3YU87gPKj5D5YIR99fH18=,tag:pZcQv/BIqcx9ooBnt1EqrA==,type:str]
    client_id: ENC[AES256_GCM,data:Wuj73z5qyCd2O0IWL4/M6pgjnWqBwmV5T1mWG3v7,iv:Pk3cYlJK4F8MZQViHh4iUGTMJAGqhziTY3S2NHoCkoo=,tag:1NHSXEThHlev3fyoOtIW6w==,type:str]
    client_secret: ENC[AES256_GCM,data:mHMvwMuGQnnNdBdCu4D7yP4OWJ96V82RJZ2cmFJK,iv:R7aKzQLSOScqvmlYDwjz7DwYgUf8CyOkUEKchWXOuXI=,tag:+NWssh1PhvXR2/2kXmjQTg==,type:str]
    database: ENC[AES256_GCM,data:PStRVuV/lo/NbI9noriNZnCJSD50Z9688empzqZC35t6i7EFdx6h6D1732tj2dyixMO1J0vYAAdD/CFgrERtTIwPRVZcjwZ3neKJqypXrtBdiHL1JRbi1cV5E7J98tasOLVea+bBnpxNKB5CtwlJkWRQxuyUkL/dkA==,iv:8kuk6jgkzLyVkPcPLUPz1meQgwQFYFrdNZfcvvtPnO4=,tag:fnZvtam7vTxNjjhGl9o2Ug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIckVxNVBDWlV0cUhGc1dX
            L3J4NVBHcm16RmJ6SklnNjNnRkVrait1K1ZrCk1SNVkxZTR4Wi9yUjFSZ3Y2VUZv
            TWlKcXZFM1RFKzAvcTVJU0k0RzhWWjQKLS0tIEg1V1dvaExQZ1dBanM5Vk1EUHNq
            dDZUdm4weGYvYU54M3RaTjlUQzFiUW8K6ERGCUfJZyal89F57+KRPepMRlq3hg6K
            v6dkkZNlaD3YDE0lFSVBHFhtEKH9TMHqKjvonuTuTfJsloKNZHEJOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T06:31:34Z"
    mac: ENC[AES256_GCM,data:xEO5sbtsQEqlFto6ubfwzMMj/dvXa2dyH2rFgqCCrXJABXrlgjKM0gWZB1r77u9kXJwL635K2nQtFMOcLkZzjx7d+3vXB4aMfQ9ywitnFLm0R4JNfnPMxC3VqqrLrytSKafxWvx8lZdIi/OAU+iLKANvrT6OI6DUhz9VK3CclrA=,iv:4VLkXDwMOfiJ+nLhs6a+D7iQvPBEO1yhV+9MkvQt8Jg=,tag:Hygtl15dGcn8nYoPPVrPqA==,type:str]
    version: 3.13.3
