apiVersion: v1
kind: Secret
metadata:
    name: gloria-config
    namespace: apps
stringData:
    callback_url: ENC[AES256_GCM,data:ZYuisarPQKogTX3YaJlqHL8EtplzeZ9PHR2N7AW/n7T2QKA8g2o=,iv:0WeS1NRr9Ud2aph5antwnhiwLr5wYWNTOucl2vJ8MZQ=,tag:UAZI0XPaJcPUHgAtpLz7EA==,type:str]
    client_id: ENC[AES256_GCM,data:aE6IGcrWAARd2NW+E0AZoirZVtUgP3T+8uBqau9i,iv:Vuv/O3FKXb3O4hy42yiVmAJhGz0kjrVe6NrOMDmt2Dg=,tag:QwOU8Yh/m8kgUPKJfiN6iQ==,type:str]
    client_secret: ENC[AES256_GCM,data:WgurlrrJ3ErC4tuNgVYGo3O22y4dXXJHYjdWGLXz,iv:DY+LPEv2hSPnoLVhCRsCGaIPZZsRK1DsCPu5abZJG44=,tag:e67ZeZxwWU3dBikDRtKZFA==,type:str]
    database: ENC[AES256_GCM,data:p0iv6rmH950WBvmgwMUVC6DGky7wSs6YnqApfllG2/70+j7uguU6qmu0w11qmC9fTJEYhYm56gr04FnA6hc1+IUGgjO2ruqoRoA78BBgP4oFMSte3Bi2jtqRkm6/gApUGWZ8oiJ8ZQRgIMYsa9RuEhxKsxnNou3nRQ==,iv:Rl30/ozQMh8J071TJPGVnaABi7vwQs8UDn7bRJG/mVQ=,tag:Pke//sqp8Z7zxUHtBme8Gg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIckVxNVBDWlV0cUhGc1dX
            L3J4NVBHcm16RmJ6SklnNjNnRkVrait1K1ZrCk1SNVkxZTR4Wi9yUjFSZ3Y2VUZv
            TWlKcXZFM1RFKzAvcTVJU0k0RzhWWjQKLS0tIEg1V1dvaExQZ1dBanM5Vk1EUHNq
            dDZUdm4weGYvYU54M3RaTjlUQzFiUW8K6ERGCUfJZyal89F57+KRPepMRlq3hg6K
            v6dkkZNlaD3YDE0lFSVBHFhtEKH9TMHqKjvonuTuTfJsloKNZHEJOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T06:43:44Z"
    mac: ENC[AES256_GCM,data:h3zDfwgmkHmWz9xTm87jM+sj1FdsKSSELtixGmvzwTtrUFgkQg4WkjWFviv5xD8XU+Efcu4zO4kGs3ZkeHUHNFrda7N2SCV9bunV7depREgUadE+QkpMk1DrqZyrr+oGWHeCXOwZHZNxpHFMxj7WhTX76eN3VZirPFV1EPisUIw=,iv:fDBBbu5naKrSuursbj1HV7J9Bo2ACWXSOYu6FOuV8wA=,tag:ZFZOBhfeMPycJSpbxbaBAg==,type:str]
    version: 3.13.3
