apiVersion: v1
kind: Secret
metadata:
    name: gloria-config
    namespace: apps
stringData:
    callback_url: ENC[AES256_GCM,data:hTDof3C/EUPVMEiTSGziXTP4Kg+pFDlTtzdjeaGngIw2jr5URJ0=,iv:xbebwUpx8MdOmV7ywExov1x+BbCkWI40Ta/qejkuT8s=,tag:Z/ffoA+BIE+NLvxRbk6K6g==,type:str]
    client_id: ENC[AES256_GCM,data:K05hvSuJKPLhn5rtJcUfooG7ZlJSWtsrseGIHw67,iv:c3qP5ba8jb8+j6YPkMk2aQWMI+KfQpnbezVoQ7ibfQ8=,tag:W5vQoktp04K+3Xc/iXG2Hg==,type:str]
    client_secret: ENC[AES256_GCM,data:3QcB1w79SvIGUcPiKfc+BXwdGUSQPRiWYcukVLHX,iv:G4iRvcXOnjPpIo600ULYk3w924AZyfm/3LOv3UShQq0=,tag:Bb3WrjrTDwZpC19pOI10Yg==,type:str]
    target_channels: ENC[AES256_GCM,data:MSocZHk=,iv:cP3qfkd9Y6inFzJ5saB3yJWX6zllbqeNlq5xXXr/U2s=,tag:r1lNviBS5K3OaHVgHF5DNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByd2NybHBtSTV4WmRZRjln
            YWpna3ZTZEJZUUZkUHZZVzIzbmY3VzRiT200CjI1RU1pMW9xc25JbklaRk5FYXdQ
            WHZJZEtNbmdxLzRycUN4ZWxFZExYRmcKLS0tIDRnR1dGVXZQQm9FYStpVVNFdXFj
            bXBrQVc4NVFjQnBLQmxBUlhaNW1aZTgKYQa7acCCWTYFjUeEtOY/+IlyNHgsb1iQ
            wWfNYPumJ6Wjczc9chVsk4rdTdYBMar0UKqZQWVVTyBcxufGIaOKug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T11:36:08Z"
    mac: ENC[AES256_GCM,data:485nVRJKW6uP9AecaN0T8KlaAEik0fd0cYdR3bN9HTT/sisWNcNQcSkqr9IiocFr+x7L6Gffsu9PnxTL30mUj8fNAh8aWGrxWODPMQez2INbju64SyxxMLLKoRS1T5UmCidB4qG3WeNBwkYlIvKRtfyeKV0rsbs1wyk+fB+9QTU=,iv:yWB/DJ16+EpfYrDeCSYAnse9wjORo2rhE9q/KpU1ceM=,tag:g920/OvyzhwhYqk87kWUyA==,type:str]
    version: 3.13.3
