apiVersion: v1
kind: Secret
metadata:
    name: grafana-authelia-oauth
    namespace: apps-kube-prometheus-stack
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:sLSZsw5MOQ==,iv:UN2S4LVQn0pQfhpYlYfQXX4kJlZi7NvMG0DHmk2S6IE=,tag:OaUCpfSs+zN45QU3nZhGKg==,type:str]
    client-secret: ENC[AES256_GCM,data:RMlCt/WpQ7sGJgT9MBb7sUNwARYgnWFRDZqOyOn1gWYrVpegYNeOjfVZ9wh+XPXb66sf1kiL/LoKvJVu8CCUuA==,iv:m0rPL9xWwHzLEJnsVBMcGYH2CSle9wt2/tE26VaatSg=,tag:mCGF8wuu0NxDjiIKerbm2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NS9sTE0zK0NvUU43UnJl
            SDZQZkdYSEptS3VaQy9BN1dFOUlGT1g0WUZzCjI4d3FIQ09yY2FVL3VaMnlNV3JU
            SnB5NUdkdWpNWVhmTzRoM0lUWW9Ra0EKLS0tIGNSZytiUFkwRkVIdXFUNExzVmc5
            QldzS0dHeE11ZUVhdjJldE1HdTE2QjAK3DEF8zzTBqgpID91TzhaH58DQLX1h7lO
            PS8lUzCZ3yJ1INOtVEQXVCi8+vQCVw09PO1tYFJBxr/qpCD2XkJduA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T18:29:08Z"
    mac: ENC[AES256_GCM,data:ayHCtunvEGzh6Ro+FBI2faf5EybMpGQtvF/5mbHGcHFdJjLGTa2bwpBagV3HywrJ+NbI5mUtiUMDkZgq9T/oV/i1Ch76XNCkrj6dfuS2U+MQPwS4BBmzheszLLjxU4KBtbimEFoqGPxXXoIKukB4TEoo1bLQaDQkinGc8Cju/SE=,iv:6tbCdjcHhLfkXB0Aw67MhmY37HKwMFhWyPPL1ZRPdPM=,tag:ZJj8rLQVDCJfsXqJGDpE5A==,type:str]
    version: 3.13.1
