apiVersion: v1
kind: Secret
metadata:
    name: homebox-secrets
    namespace: apps
type: Opaque
stringData:
    api-key-pepper: ENC[AES256_GCM,data:1lS4TWkbOxJ5LQWvZIQNRl4DK2NIR/BswjE+7AhZl+ELm7KxD1xBdz7l7MV7Y38DX+hTGGk63AEEUpy1EQfc4Q==,iv:JGcC7KedzU5KkxZQi95LEz6Lo3QNh9rPPC4QqUJL3O4=,tag:/akpZ8sjkb5z9hzQFUlNWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSTk4ZjRISndEeGgyVFky
            dHFQOEVKRjBjdi9wbGhEWVNidzVwZ09NelJjCjE3NW9WN0s2MVJ2MTNjV0lMSVpB
            c0gwajZJN09QUjdJWWovcEZ5Qmp3R2MKLS0tIGxFZ2pIUkRTQmNHajNUR1pucGM2
            NTBwSnJ1Q21XQW41OFhaYmxPMnFYZG8Kl5RvyGLj3azH3OJWpkrrX4WNZz2460Tg
            uQ1lZT0UDktCKVSfbhJLMaDxnLExtCrseF3H/65PMtuqMiEWNucLtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T12:02:03Z"
    mac: ENC[AES256_GCM,data:+WvkUWxvxbRuWWFMHxQbpJsElbPPTMJ2fGgeHGxFeAAxZoS4dabE6imPPm2mdlJdVWHmr8H3F2BzITJxG8zlm1Wlt+OpHIUAzzaFKJ9C8Q67iPsZR+AobhNJCTKDm6llQSk8r0uNGQT4oCKRbBsELo489Cei6SQN9kUPJ68tHzU=,iv:4gsfOvvNw0rnj/K2OjieEEDTYd85Gxo1qx9olzrs97M=,tag:S7MD1M11wLAnVNYh2ir85A==,type:str]
    version: 3.13.3
