apiVersion: v1
kind: Secret
metadata:
    name: homebox-secrets
    namespace: apps
type: Opaque
stringData:
    api-key-pepper: ENC[AES256_GCM,data:6kghGO2VlNJX+7F3X7ZSCy30U7rCf9bB734WIi8PeA7WnyKYiaQsI9NbsNybHU6CvffxubX0OAvmixaitwJOjw==,iv:3upS3nXU2z8pvpLWbVzS+rbhX0h5JfpW4UpSHph8s50=,tag:/KXbTi/3NjUhOEPKRkSZCQ==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:4CW2jsSyYHwrT84DUOJYanEGBPQ47m+/dIfgNqQ1BGwrCRf+Klw2iJol0QSQCIJa,iv:U4C3edqNkCnHdxyGlTcBqYEd4wouLJ0eQv6LOcBK994=,tag:BV0LK7JNL6bLt5dXtEOqFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1clhVbkRIdzBsOWNsYkUz
            QTYwdUtlSkM3YUxURWw2REJVdEVEekZDcERrCm1pRlpxYlNYc0lVV3ZNeDdjTXFW
            YzVPZnpIVDRDM3hlaXhvL0FUc1RSeGMKLS0tIDk1L2RZcG9kQ2xDeW4xMjdneEdp
            L3gzejFGUFZLQi81Y0dPcFpHQ0ZxcWsKsrNrXo2OLiMjl9dSIjrPqgwJQkWVbXdZ
            mi/M62BnHCzexO/4rRYre6r9/BQMR6sTQHJfcRFYDZxX2TpSZxQjTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T12:14:25Z"
    mac: ENC[AES256_GCM,data:j5/J9eVCxUflTIgjkI9pse4PizUiYXK7KWp/wxgJA+Te1WTq62Lb21xeOJ/ZX7VLQVIBfFU2VP7V/dAyWy0K8yPZcqdO6QT+id6e922JuhMNZDr8eo5aXc0rdrnHQ32jSVLJQKzwIp315VMukCOtvX0ZP6I/kGsucOjNzsjOADs=,iv:cG3bngtVqZLxVYxkWVMk1Kl73di+n7wKHonXOaLzu0A=,tag:OV9KTCYtPPvsxouQzyFxPg==,type:str]
    version: 3.13.3
