apiVersion: v1
data:
    base-dn: ENC[AES256_GCM,data:AcGTjYifwyzMMwKxko/lQ37kSqQ=,iv:2N/jKUT8kWLu03f6ar4DogMeLRxWLnGQV7BIJHsS7pU=,tag:+XqLMMUZNu0F93yktvr2Tw==,type:str]
    lldap-jwt-secret: ENC[AES256_GCM,data:LLWPmJ02UzecTcsbQLkH2Hrx1WSzSYu60Y0CMZcswU1Bf3/XEwW6kZPwujebv8ezGzhmrhzRyyxW7FevzABgEh7AMTp7+ZcLrc9iWYLc/I8McMLTsrTCrg==,iv:nuV7pQq9Kabw0TjavFCoiyQXxIG0P9sLbMdTX4bf4tM=,tag:u57qmyoaE2QKzqVHwZO+Xw==,type:str]
    lldap-ldap-user-pass: ENC[AES256_GCM,data:V0jDr+CEo/NybmWl6IEUaMfqYz6rypUVe1QQ2RHRjJpeq+/cIYT0gfMZeD4=,iv:wfuSqECTNTZDU8UPS/84VH/FJbNZwHidmKYtT3ZozwU=,tag:3x/Vq5UQbYZzqb2v+7poTg==,type:str]
kind: Secret
metadata:
    annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
            {"apiVersion":"v1","data":{"base-dn":"ZGM9eGluZnJhLGRjPXJ1","lldap-jwt-secret":"VExNU1Y4cXQ1MXBXZmxQZkxRQmFjcFhIQkVIMjkzWGM5S3EyM0ZkUm4xZkZ1Y2NrdGZTWHpHdWJvVERRMFMwKw==","lldap-ldap-user-pass":"bENOL09TSWpmTlBRRHQ2eVFXZnlEbGVNZEJQcFNNWis="},"kind":"Secret","metadata":{"annotations":{},"name":"lldap-secrets","namespace":"apps-lldap"}}
    creationTimestamp: "2026-05-29T14:30:42Z"
    name: lldap-secrets
    namespace: apps-lldap
    resourceVersion: "1617482"
    uid: d0681782-031f-4c16-a026-657eed199a51
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3R1ZQVGNtTDF5Y2dkd3JO
            bTRaaVBnSDJlZVhtU1BERktCY2Y4Y3NSWEZJCnV0alZwZUVxN2VrS1F6QXhBdWJV
            cUhZTmZndVRSNkZ3dWxscmZjRkNWNG8KLS0tIDc5Vm9LeG9iTExQMTFSSnhoK3Qr
            UGQ4SldlVmVjTXU3WHF2TFdlbVVGMWMKj3ARUk0sEEo2Ly89bP6DNZT9ZMKciTVk
            zEXY3LC10xsdOR6X/XcO+b5DkCXNueUxht2ZAo9dBpXiW9xeOu1spA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T16:16:56Z"
    mac: ENC[AES256_GCM,data:+yv88Awv1OIhFIRtagUfOI6ZFZbDKmOIYQK2KsdIjuPEDDJCH8yhh/TSsyrFU08N6oXpP34leaCGSJSpHdouD1szEdKam44T6t8nRbjjXMfZpKoXzjHtg5wZFmx0diK+bcD4pGzwW1U3+pSExl/ekq3O86iNCYZ8UN7oCzsNqFw=,iv:9iAR+aFWTAVxMYvFf6iGe88ffUxPDTbHmJymoFiXDpQ=,tag:/slY55+SKrDoN969D1KhwQ==,type:str]
    version: 3.13.1
