apiVersion: v1
data:
  base-dn: ENC[AES256_GCM,data:jvLz+wvtf+flF140qBLkBKxyOgU=,iv:G+LiRdMFd9moADSnVqgRqLInhAgw00T+5EYbD8+hoDQ=,tag:nsnAWW3Ztrs0l7gw9yztjQ==,type:str]
  lldap-jwt-secret: ENC[AES256_GCM,data:elEjQoY7B6+zppkBXii0ihCXrCUy96fHluzLlBWNzIVmRyWeDhp1g3/7P4ZrfxYh6vOs0K+qVpCIrc10f8uGGkHTyOBaIZok0qSwYOxvi7Z1eBHQn2lPxw==,iv:HrsvZK4ZPyzLMwnmmx9zXyLnQ8Z9NVK8zM+1YrQ4kOw=,tag:I0X+SAHtMoTRVlNHPasilA==,type:str]
  lldap-ldap-user-pass: ENC[AES256_GCM,data:0thHe2aA9w8adi4EQapUn/bPmllTUYKjOXQ9YzQNiPk1zkliTPhNqVvCPe0=,iv:OkFGRLMTylyIEt3GFmOJPiT9Kqo23I5XtY9wKhNsskg=,tag:G1V1BECZlwOtP2gNZn9nIg==,type:str]
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"base-dn":"ZGM9eGluZnJhLGRjPXJ1","lldap-jwt-secret":"VExNU1Y4cXQ1MXBXZmxQZkxRQmFjcFhIQkVIMjkzWGM5S3EyM0ZkUm4xZkZ1Y2NrdGZTWHpHdWJvVERRMFMwKw==","lldap-ldap-user-pass":"bENOL09TSWpmTlBRRHQ2eVFXZnlEbGVNZEJQcFNNWis="},"kind":"Secret","metadata":{"annotations":{},"name":"lldap-secrets","namespace":"apps-lldap"}}

      '
  creationTimestamp: '2026-05-29T14:30:42Z'
  name: lldap-secrets
  namespace: apps-lldap
  resourceVersion: '1617482'
  uid: d0681782-031f-4c16-a026-657eed199a51
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYUlSRWxleVJiZEs3Nm0v

      dFRmRklFOW5RMDk2ZFhqYy8wcU5saXdDUzNVClo0NmswbEgvdklBalNsc3ZEaG9t

      NkV3RU5WOTBnSy81b1Fkc05IZHg2b3MKLS0tIDJMUUJxbGZmNVdmdzdnNFNwWU1O

      NmV0N1A4L3lxZ2JKUWFWOXdZZkdYcDgKEHqpGVwnED59Nnvo8RJtpKY1v8KLiUdx

      dJTqSiGHZAHBUHgo3EgfHB/uHdJgAk95rW0ub+KEVuTZCHLZxZ6UZA==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-06-19T10:57:28Z'
  mac: ENC[AES256_GCM,data:jmMeIWbP4D52aYFbV4gd5srZ9EH/raWqbPZ+JOICbQG+Mai1sw/T3lqcLilbHyB1P7GgWX1rGPaHHclNtAtk0Rjka2Tkgz/ZRWbK+2Ez5LBUXUdBGii2DHF+KTE2bBmV8Qu7PU6jKXBJwkq2Y/GIbI+WGkvW8TLnov2ALCoXQXw=,iv:rmC8fDANft/GoV9sxxQO+JfYBnp70x7Xn9Av8DsHCJA=,tag:W/mvTRJNeZEdsF9UVJrCmg==,type:str]
  version: 3.13.1
type: Opaque
