---
apiVersion: v1
data:
    authelia-bind-password: ENC[AES256_GCM,data:9hM54w6GMMKtOYg3gHspdNu3hXIBLrp3fBABgOOkmdIfezNmBX2qT5R9KR0=,iv:MiPYD2aN+UxlvHCBcY1VfY/+qx51n+W2h9CbYJN1/tk=,tag:fzkoJGzaZKaDu/IZuszn7A==,type:str]
    forgejo-password: ENC[AES256_GCM,data:/QhOIVgkhAm4lTnEcmoilpOYq6JG3K+oYdlR4pSwFfIQZZ/BnyKIqlFEzzg=,iv:arBUAEHziRFclY63yOoHKFxMKKybHG5kvD5CCqzwem4=,tag:GBGZCBlXkXUk1HpPAzWWug==,type:str]
    nikmosi-password: ENC[AES256_GCM,data:wGSlnTwv+XWhEcZs0l0Pf12ndfevByVbFPdNuTY0e0xOquaLvqZiVhtVkY0=,iv:U0N5TMC5CW14chqUQNRLdAgyJSS1yU/+1soXMz2qOqo=,tag:OqQzAoxO8nopJkCDRZ0hLw==,type:str]
    zot-reader-password: ENC[AES256_GCM,data:7Ml0R73SB3bmdbA+Z/8kHEOb7II9PSQtS3ABu1erU+jt2TWAkN1eo4K0b40=,iv:dwcCE7Nk+89AnuO9Uz4NCz1FXbN41gOpOiNjUYahdss=,tag:NszXAMjmQZmt1UFuMO/iSA==,type:str]
kind: Secret
metadata:
    name: lldap-user-passwords
    namespace: apps-lldap
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISkpBUXhuNFY1M1RTcDRk
            a3g4eDFiblJUU0Y1U0dKbEdiZnUzcHFVVTE0CjNueGRHd3VlOFZhdXd6bmd2VjQy
            cWJpWFJDYk80RGYwVWd6ZWNDd2FPS3MKLS0tIFNhblFWbUxGeHd0TytlSnF5OVFH
            S0Z0YjQ5TU44SkxXemNMUlp1Z1FXc1EKjGU90tVdvC/adr2cLp5fYOgyIixpxyRr
            G4ZXzQghxrrAdTytmhiCULSyiFlvpqXNt/xtOZuMRo1pdxqzyaxU8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:23:00Z"
    mac: ENC[AES256_GCM,data:VNU+SpUZTQ4cdVyffzhIkXZf1r6zbIqz4Jz6A67U2BReJBXTLRF1qD73cWWsAIga9AGJi4YjlbiUw7E9S4M+XIF0ytVT1SX7JrgsU4EjxmRRKDc0q0xbTvjNyNiZQPHOCpBGKAWeULYcvDErpiXPomDgwUkCBw3R2Av/IgOC6Lo=,iv:btfz7F/aNVUjcdEuXKE8VtG0tYWKNhbeYXn1vEOEe94=,tag:8DZUNDq6Dm+lbjN5pNltqA==,type:str]
    version: 3.13.1
