apiVersion: v1
data:
  authelia-bind-password: ENC[AES256_GCM,data:PzCTwMSsAeN8ANqeawpNFKA6GEUlQc04o1/PA1lgkNePpvtlZ+H7GLmxpRo=,iv:2HGe/eze68/emrhHhVArbTSIoVp2+aAjF3R6f3R7guo=,tag:iq7xMh2s2onwnD/Z9/WiBA==,type:str]
  forgejo-password: ENC[AES256_GCM,data:aZFKfpc56dwZY1mX1FSyoH6Rm/GYLdSHVWqB9BzXe1j91vVFe51g11tuLe4=,iv:AgWdHmJiJ9EQsoF7i4ENSZkFjdXWTUgYk6Z3b3LZf4M=,tag:KSeeW6IekAzRVMNK5jBtYg==,type:str]
  nikmosi-password: ENC[AES256_GCM,data:92JQWU0AfF2S0yIVmNkpTmR2Lf4psrcUqvybf329TtqcDp+nIgKlVAVo2VM=,iv:Zj2+Y5ARrx9rvHuOmLRzsuOA+X22RO7ecN1tovRihPU=,tag:H+vyoIk8zmqo7IZZgiRf7g==,type:str]
  zot-reader-password: ENC[AES256_GCM,data:/Ee26FPPvUQ8HH2soAP4pUFUREp1AU3PX5fuQwwjB2ELYPvIp+VcVJFuPnU=,iv:4ojJg0NkKT1V8mnG5vRKBaBjc/4ciehNs7Wp9y82lE0=,tag:cWRAFdRqzbjsefJ03slEFw==,type:str]
kind: Secret
metadata:
  creationTimestamp: '2026-05-29T14:42:10Z'
  name: lldap-user-passwords
  namespace: apps-lldap
  resourceVersion: '1621101'
  uid: 1aedfb4e-886f-4d0e-94b9-0199888efefb
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYUlSRWxleVJiZEs3Nm0v

      dFRmRklFOW5RMDk2ZFhqYy8wcU5saXdDUzNVClo0NmswbEgvdklBalNsc3ZEaG9t

      NkV3RU5WOTBnSy81b1Fkc05IZHg2b3MKLS0tIDJMUUJxbGZmNVdmdzdnNFNwWU1O

      NmV0N1A4L3lxZ2JKUWFWOXdZZkdYcDgKEHqpGVwnED59Nnvo8RJtpKY1v8KLiUdx

      dJTqSiGHZAHBUHgo3EgfHB/uHdJgAk95rW0ub+KEVuTZCHLZxZ6UZA==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-06-19T10:57:28Z'
  mac: ENC[AES256_GCM,data:jmMeIWbP4D52aYFbV4gd5srZ9EH/raWqbPZ+JOICbQG+Mai1sw/T3lqcLilbHyB1P7GgWX1rGPaHHclNtAtk0Rjka2Tkgz/ZRWbK+2Ez5LBUXUdBGii2DHF+KTE2bBmV8Qu7PU6jKXBJwkq2Y/GIbI+WGkvW8TLnov2ALCoXQXw=,iv:rmC8fDANft/GoV9sxxQO+JfYBnp70x7Xn9Av8DsHCJA=,tag:W/mvTRJNeZEdsF9UVJrCmg==,type:str]
  version: 3.13.1
type: Opaque
