apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: security
type: Opaque
stringData:
    base-dn: ENC[AES256_GCM,data:YobSA5A1nh9agOP9AoKi,iv:Hjvmol4af1v4+/1trwwBumuvsDwpLJyPTTVwA1QL/bk=,tag:eVVKUOf1r/rx0YlArbpItQ==,type:str]
    lldap-jwt-secret: ENC[AES256_GCM,data:ZuAz3/4UlhbbycCoL8QRoBKNyqoxYAChPHA4TKolrXZQlqYHpcuIWb9IWPkkG46cy65UNc7TyyDvWPheKeDbvw==,iv:Xd1tcNRd6IdPqIXjeBqk/jfkQw7iT7hsWtFVoCScI6U=,tag:0nfN+wgFLFVeh+GOy1dQjg==,type:str]
    lldap-ldap-user-pass: ENC[AES256_GCM,data:lbp8zBNvHOVYINMKUXHKh7WhFyH4NSS+9YiVIkZKi84=,iv:U1mS5j0bEpF+iJTC2cTUtsiU5NuBlZmlHM9wIAeBsnM=,tag:TPkStXbdrU+6ufHzPCHE3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWlIxMEw2ZDRjZ3hVYWtu
            M1dyZTRuL2lwUEtEakhVT0VhL1FsalB2K1E4CmJncFdJLzZUYmQxQ0pjK3VVNXAz
            NG9PcysxUGRxSWVuOHZRVnVXYWRETW8KLS0tICtySGMrNjVWNkkzZG9DNDZDdWFM
            RjB1V0lQbDJnWlZuRzhMMUtMUzh4ZmMKqkvkLqktfzdgE6oMxbb5NQRTRizpc21b
            4NcIBPuGugmUjuwnW3dnxV8FZtlJ3AFcLo50d1Oui16CnJ3uM8cu5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T08:39:37Z"
    mac: ENC[AES256_GCM,data:z2xfuvHKN1X4Ec5AjeGMAbiT/DDWK35C19taD979EOInM1veMEG6vn0z/zyQEfwzccT0daU/FITt0uxMAclSC5TDSZcQJ3jc3XtSj59QSdczBM0mDCIQ2wr61VnhRmWdppB9fJtiCa0ktDLkD4kMb34JghYvlzSMa4EJyx+vSbQ=,iv:nWs/EKTJbfEPwN/73meonSjBYMTmkTwPAQEs/a5RIX8=,tag:/9xMO8fvGsO3M+fLvLX9UQ==,type:str]
    version: 3.13.2
