apiVersion: v1
kind: Secret
metadata:
    name: homelab-ca-secret
    namespace: networking
type: Opaque
data:
    tls.ca: ENC[AES256_GCM,data:HirkeIIgEtTSCPQRH0BqyTMetuzHhATpSw19hn+glcRT+fTaocjyy4Srxk6Ge3OUfxV+POSvMXX0HCt2Ml6sKfgrADy6HCpGUzwAo0NS5oQmOCpR+e1nY7Ppem2wf0M7Ql38Z/lQQuyTHW89RIX9ZguqEfh+qo3onv45yhgzMPJ9koQJgH+g0tmgxNThvorJwqMNKVxjhXuOa/q+FQf/vFnq9IRxE7KW5ydiAYSbe5W6SKXHjJfby5dE1Vbn+rzNATW+2VbsIkKtCZ5ezz6+me2YQZnSKUzu2WwcKu+0UABbbm+khSH3DpWXwa9+hhYO08qM7hPtvViRf+lp+mZd0uT4+G4SKNFFwsc7Epxlmk/SgVTbLWI2tgyu+eSq/lx1YOXL9drx8wXlDqs29Ps9cFmNnAO15A2UsUommlxj+9o0D7YWan44YJicnrhdAGRxF/roPopzJIgxbV9t7tustVllfOyoemrMnQ5MPIBkXRN773jW3AX3FeNLWfbF2RE48KR7Bxjpr+wm/b33B1bD0Rob2ftgK38Z8bucw8ta7Go7x8u+UuUOpAjuWlqebICIFo39eeWUNN774tfOOmU56xhtpL2uz8C35P9jw5KUJ+yEgDfVU7OIQTOSqa9yYE8fuEyjp+OlicA0MQi+qdEpk7iF8/1yizSKwpPb6XHfzn4nuAPXuYCdf9u+i9EisFgLkB7u9+CRNzsY+uXQaat8KOcHI8FKPGhSXcViqCgI2qkx6U7y1CkZhWlNwvdvsdTKzzKMt70kg6PVxwKJHtMszBrAIThJ23lUv/l8Dd+PsAwdW5+SoCCzI/zWLxafPmBVQbas0KuwZhPWycqGSECFZmEjvET6wKMuP+9sYAlLvj7C+wBV49ucVP+UlNDV9MWjgP0299LmWao+JKri+wsiiN+Q+IJ2tiK40gxzc9gdsJctfxIM/H+gWuhKGd7J6H5Qw0ZyolXbShkV1Tz1leMrbgspewU5,iv:f7BXdmy/q+XYTjB48NXeqon8ve/s/gjPjgDEWqs8yWc=,tag:e4OUvopnP/dYyCoVNAjisQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRazJEdUJzRlVxVnBVbkFa
            RmdxWmRqeWxISXpBcUp6VS94K0x5anhvdHhNClBobi9DTzBHNkhHd3EvVVJCaVEv
            eFpRTHpldWloempadDNzRUxCZ2VJV3MKLS0tIEVSZE1EZ2FxQnEvUUFMTGkydVZD
            NWt0REx1dS9Idm1qNmR3bnRWMWY5b1EKD2pZSPhOYAzMSUYh5yCmvdjZcUnIqFVC
            yG7HgWrHXsCDnz7d3+T1kXS7ZZqK7afYxMxBLLNKKci25pLfYGowcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T05:01:35Z"
    mac: ENC[AES256_GCM,data:A1dAXp+PX32zhrg8U/GQo2OFLBrN8W5j/B0/RVrG+Gcz7GGO22zZZJs3E3AlekYGbiAxXY16NgiaQTW3oUj9MhFbXHEFr5ViTrgcpToQxiyIxCPag2Ew+RYkNKrZkw6IMC4RUHkrCtZNAKLGc6UA0AmYEBAL6AONz7C/ETN429Y=,iv:TjGy7yW/srhMiyxSRsgcU2Dcv4/3AaxGUOvCCueCpOA=,tag:PKxjjZCfOWubCAubzegzLw==,type:str]
    version: 3.13.2
