apiVersion: v1
kind: Secret
metadata:
    name: oidc-credentials
    namespace: apps-zot
type: Opaque
stringData:
    oidc-credentials.json: ENC[AES256_GCM,data:0fkvBlpfD6YoYV3QWXKKZ5sx+xBjOy5y/OBhojxRSqQhf7nxJhqIe5rapdKEDALc2x8y6JVbHHXjZADHm61wqQ1/6Lpoccg0prnALnV8t2qtk5ViETWPbscsz8ouizzf/26YkmhGJLneHkL7Kxw/pbZ3uklj7wG64xzbg6DHfzeLlZXmCQc7B7DqagCoejNuOALfyrmip/wlsjZ55aR9qtyt1KFkVJBF/lIgEue7IZ2Fcd5nORpWfj1E2niRJYzkTCzoUn456Fpu/xvjq8Wy+E6YYQ==,iv:yM5hPD/jIt4zRuLuyEBCUKceb6T60ujXdVZsV7Ai+0I=,tag:+TpK67ZSmnXUbS8c5I8yYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dVplZHpIdG9XVk82bzdM
            ejFZeGJWQTdGWktoSkk4d2I2V1ZKT3hNTDBBCnJiZEhZMUNSMlBIQm50dXdrZzRq
            cHM1dFllRGFORUdyNFFwdjdId3J5aUUKLS0tIGZhMjZUMG5IUkFDUW50bGp3R3oy
            aHZtNkNLQUFvU2RaNEpRN0ZGOXdzTjgKPyk0H9EQoEaxrhjTbmZs6TTANZ0mYJO2
            o+E+5d8NxxOHoAlsxdN5kYlrAif2O5SpSs+yHwldikjd+C1hFsI+Fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T18:29:08Z"
    mac: ENC[AES256_GCM,data:a0oSvmG1cC0fQDlPNX6vb2lf1u+VAWV8norfJBGFqvgJ1YePVvM06KHawLHGJAKtGUPfCRU5wY716FYze6onKVZ9/u7DT14lXX6ZttqW7s6Ew7FR0aoS/PwgNuIEdTbJapvn7KE0n14GONT3n92RRzRfG0uik8DAGaXA1epiZmE=,iv:5Na6iP6Fl6hozx7dFs4DKvGdwUt2Y7NmNSkG0HRVnVY=,tag:ItGIFkNbn8qpQ7YFK6T82Q==,type:str]
    version: 3.13.1
