apiVersion: v1
data:
    oidc-credentials.json: ENC[AES256_GCM,data:0CRw55AWZafHWe1uhv5jH++0UAhXiUXDwFTrcpbe6IRM0Pv81UJ9U7Unj6D45T4c9JqA7mkz1uB5lTueIv6hwABROZSuDrI9E2sCqO2bNhgBuuGVMZRartN4foltdOehfrXwGHDVbhYyjIfA9+SmdrhIm3W/tPeGDvIeNTqBZ3YH/9xEx4F9MX1QcLKE/OrHYt+e5PRwsS5kG/9f2CfkLNa0dzL6XsfKn4RclF9S1OxmebCLLFmsqRBw/Zto1Q7Sx3awIzBsFwsEYFhKOBHl2gWDUIqIRlDLJJqkUN/cgEB56F3SRwN3HIwW7xRhha+8Nnu3UEO7hreozqII7d0/vTVLmentXnhlmGbyhlNOpsgGSde7xbjiVLncdY0=,iv:xbiUig68FXF0rbAUsBaMFmjAB38C4yLOH7pQWfJVt4M=,tag:jw+Vzj7kPbdhTsGPuqJyQg==,type:str]
kind: Secret
metadata:
    name: oidc-credentials
    namespace: apps-zot
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbCt5OVYrd2RlUy9UdTRl
            TVFXSHhrTFNlTXlwRDRUVnlZb1haNTM1S2lBCmhKaVR2Qis4Ny8vcDBEYzZ6dnda
            eTl6T2NQbDA3TVh5aUNaTXcwbTE5ODQKLS0tIE01akwwTVFkcEdPTnVLMktDS1Mx
            WFE2R3Bvb2FLZmJLaXpJaDlVUXdjZ2MKpreros0xnlLz0vWHKacE8+ZN34nb6aZR
            J7YRnu3gMPqDoWi12vbmVKV/bWEre3U51KTL+zc6H6KPvRtWnMjCvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:01:34Z"
    mac: ENC[AES256_GCM,data:W0XUuFgKQ43Q3elAmFM3vBr4OgmT4/rpHquTb56IE1oP1rqjyLIZKXotrfPzt6J3cbf+yw5q5BgwvmkWYf7yG7w74Rx/e0ncPdi+XugB2KFG4wfYtLDe56tssSxcgEt0anPA0+T8RK6x77XmTBJ1nZGgc+CUkAFvRv75gY6z4t4=,iv:Z+p3xOvoxZHxse/wZcikTnS9brGvIzktBgLfSULNPBk=,tag:/WH2cYMQgMsk2C7baTgTBw==,type:str]
    version: 3.13.1
