apiVersion: v1
kind: Secret
metadata:
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: developer-tools
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: developer-tools
    name: oidc-credentials
    namespace: security
type: Opaque
stringData:
    oidc-credentials.json: ENC[AES256_GCM,data:c4e3ygU2Da3VUWFAAKZksJYFVuTHNnhN8ewh9Ck5nXsduKswGK9n99kzaRz+NoepmcJr75wTxjhQWCfRfE2UDw/wIx04MWhfpUj62IMizE9RPqxedFbv5tMZr1dRxOgTcawx0UYdOy2Etsp5m0AjmaAQaPWa98t6U2FgwQqJ6q17/wHdgvW77VGgQYMnIjOGltOMIqfu4JYbc2mO4VM5h5iHhvwO/FrTOgm/WZ1xDEW/M0vJrWWcnT5WFeQweTCzwHwjkJ97WKPe8CK9kA6kIulCNg==,iv:sNgx+gygdlTjYfh1g8qGKLherxYAQwUivMtwZN5wp1U=,tag:pQKpJY9qwLRLHk4MAj2Hpw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb24rNTNONGM2VUtUbS9N
            YjN2U1hGbEk2cTNtK1V0SGhtdm5icWlGL0hNCmdmV2Zvb29TS3BrQTlBRFEzeE90
            d1pRS1pwMVdLcFFHTDZzV3VmTlVEbTgKLS0tIG01UkVEYVJJbWxwNStJSktnL2V5
            SDVJNklSb1dFelk5ckhmV3VjcjYxcWsKTuL72uBHVPr1eLaO9nLCJp6UmP8VY3Yk
            Sn/52p8zcFec/eWjDRbcEXZZigaLA/gckiTzvjvPi6a3c5iBT1rWYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T10:00:09Z"
    mac: ENC[AES256_GCM,data:zcyQvk15c4cK6t751ajooB1CxlkWrZD8oS68JW8o0YA+jxIgH1/Hqq+ykkYGWMizyPRvFH8Mof50QyjzOIymezszNZRIHFGlP9NyOBk4NrjtbhEgb27dkJefVXjTf6kv3M5Bhk7W7iTayBY84p/NxsMwY6pPjaLSymxB8tVpvec=,iv:/HBiDiqw+hflxoNlRbFmuUla/DMVw4dI2oJ77lQqUfU=,tag:ZZv0hd5hvlMkcfS7icUKhg==,type:str]
    version: 3.13.2
