apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-default-password
  namespace: apps-pgadmin
stringData:
  password: ENC[AES256_GCM,data:dQfbqStvR7W7CQzKwuimbdF/3C2eiFjuK9T4/9W0pSU=,iv:GjIkKOl5MyVQO+bzORYPC9Gy5R8DNtg1zzsA5X9yIAg=,tag:H9XJKnMvyE71LJM66Of30Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QTNhNGxUb2RqM3B6akxl
        MWYydnBBaDhLUkgxa01NOXBxQTdxenVlcVJzCnBwUUhYOXE0VmxPWmk0WnQ4ZUNP
        d2JMN2p6VVV0dzFkbXc2RzZaT3VLMWcKLS0tIFlBQUNOYnlvVnRNdEhOV1NLMkVI
        aXRGa3F4REtmVXhiT0pPbHQ4dUcyc0EK03DU+GgCuly1ECKHLqfVlXPZpbBE9XG0
        MpZwlDXaZntw2Dp3ke31ed8b17QOQcMa9TKDbkmYTVn9DFmJIWFwTA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-21T17:26:28Z"
  mac: ENC[AES256_GCM,data:lBW4cjJcxVYtPFLwCtdCQ+oTS4zHWGfPdGqVbIziK4lCFsUAYih8nzgeB0bMhr8d+1Mj39397JBaXiueyEce5r5VPxTrNn8HxrjVYQBt9g7ILsex3y1PamW7DniXFoXYy/qieCBGy08uk1+kuNWiOSCTu9kHn0QNybwoxxgfRqQ=,iv:2TVSfzBON5HBDCD10DxvTb2mBgPf/xFOz7K7DLo4/QU=,tag:seZ8+FueXx2pK2/t9knnUw==,type:str]
  version: 3.13.2
