apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-default-password
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:/vcMq6m/NtQBuZkZJDbSLM5g2pH6KD+TghtK7QOeVG0=,iv:/oycMULEUzijmzcLpFvZGBj9QG1pwV8vVa0pRQKf0Bs=,tag:k4ZbAaF64N4eSyieDtpk9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNWxPeDQrT2prc1VvL25t
            RlQrWEtDc2F3aGZaWmJxWkJxYklWWXZxS0c4ClBCVWZUamtvTmFhWFpJNGd1SEN3
            TUlrQnBrK3FGMDFmRUtPTmc2czRZUzgKLS0tIEtPbVBTRGF6Z3V0a1NBVDlTaDF2
            VTBmU2l1eE5Da0VuUWluZTlpVVF1OTAKtnSOCrc4n1Treq7qc/F9aRU4XVOC8zUH
            3nhdBUJoFekxbDXdd6S9EG7UMh37d7mxuUOy3hRRePbG6nLrHcamRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T07:42:45Z"
    mac: ENC[AES256_GCM,data:2Md7KAz2t+cWih3JLqjj3j/vPjAsLL/olRM5Ef/m0RfPLV7jDoA817YwdrHkjgWRO0ldMF5HoYsp5G5mVDONMK0l/XVpwbmFc+P8wSQXCcq8Z4A3PC8DhZSDcPz0dIjgg19m03bx2U4d2HRNiXQEzLTS1su41UWiquzEvb8zvHc=,iv:TDxs5B6rCq0kRMBvlAbww7fTHbD2xkvSpNDSFSwcm+g=,tag:4qn9QDOUAs44mxTaSnPwvA==,type:str]
    version: 3.13.2
