apiVersion: v1
data:
    web-config.yaml: ""
kind: Secret
metadata:
    name: prometheus-kube-prometheus-stack-prometheus-web-config
    namespace: monitoring
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucHJ4V25IaVltbTdnaE9G
            d01yVXM3b2lCWlprWlhRdXlhL1ZSNmhMMHdrCnF1Znl6VmgyY3BiM2kxSEV1NTlB
            RVpISHNEYjBPVHZidjZlalUrWUNDZzgKLS0tIGJ0bU1EeHNiRGFEQ1dIUXMxcnhV
            UC95dGlIazhTT2dzaWovWUhsM2dUR0EK5SnTjddk9qUTyuuI/2N1JSWx/ElFzXC2
            /MxLz7ogF6ilGomndQtHRtOt4fJLg7DK4w/GPtzsW2CQSXabxcgprw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T03:45:35Z"
    mac: ENC[AES256_GCM,data:Vj3QSkP79Dtik5V36Bhofvq3pDDmMmFRgpgBjfx0ZYItW2W/N/zt8DNHLxUbx8lAgzn5nfLfIads15hacsNVXIe4p6aSDwm3QyyCIQa0B/Szx9Hc01n8TiKHKt1V+S4I7Hhm17sIPr1GHbFi3lg4ke41FnnRNkf14hRLkWbi7Nk=,iv:LR9BOB/GhlnF2aqDn2g5AqgFKR4BkhdwLk0/xQYl6dI=,tag:si4+y6JwfyksTgLYO5Sx8g==,type:str]
    version: 3.13.2
