apiVersion: v1
data:
    web-config.yaml: ""
kind: Secret
metadata:
    creationTimestamp: "2026-05-28T14:50:24Z"
    labels:
        app.kubernetes.io/managed-by: prometheus-operator
        managed-by: prometheus-operator
    name: prometheus-kube-prometheus-stack-prometheus-web-config
    namespace: apps-kube-prometheus-stack
    ownerReferences:
        - apiVersion: monitoring.coreos.com/v1
          blockOwnerDeletion: true
          controller: true
          kind: Prometheus
          name: kube-prometheus-stack-prometheus
          uid: 43afb989-0cb7-445f-9873-dd1fa68eb772
    resourceVersion: "1544778"
    uid: 112bd3c9-af6b-496f-8e60-d8c9c5d04bc3
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweEpheHl2SW9NNytrM2hm
            emlEZGdXSnY2QmNKNTBJREtyZlVWRldPMjBvCmhOT3pLQlFQblI2OURxcnIrd28y
            NnpKQTh2dEtUeHcveHpUMS9aczI2QUUKLS0tIEVxZ3hZbCsrZWdMVldGZmtZb2pm
            TzQxOWZjY1VYM3ZnSklZTEJQUElHYlkK9asUqR8sLOG+A5gCU4Gx5NAg3IN6F5oV
            8QckIl+LFXr6AbTiozxcKvuzWGUG9cXVS+EZXc1pqGJTkDpb3hnqRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T16:16:56Z"
    mac: ENC[AES256_GCM,data:DvM5xVLJGeGHueRv0q6vBRScN0VJjUwmpa+5D4yoxFPmZ+oXGpTUfjddQZqf1MeyXdLVNZNgH1mZff2uEKAEYrYi96E89vrvVZVACGNhzgAPtCJEeeoZXhGqKcbIHK8vMl8Rom3VlAjmE23aScXOKubyrpW2m0SC8aPqjQt4JL8=,iv:Y/n94hDsbKHbvqaA4iE+npVSGqd3lg21S3guMuHElZ4=,tag:LeJnXCePW7kE0ltwYvpehA==,type:str]
    version: 3.13.1
