apiVersion: v1
data:
    0_apps-kube-prometheus-stack_kube-prometheus-stack-admission_ca: ENC[AES256_GCM,data:3lP2RarOw6xX1eAxUgjCDGBZ6D6XN5k8x7Y90M20D3B36/A+LLYC843hPE4bEoyGKVMJ2Y7fKlM5VN7PrzReqz/FoDmVc14wQ6MsDVeHA1C5TDlsHJErmdgilhNY30ToW7oED7heeBVfHSQjrb/AcfAcEbV5T1sIaUZaT67R4osmYElBYEmFFAHYgI4w7SemFuZfd5TjYMaMal/vESv0CP9+zSSxdYlkrgz5hSzxV9eMDqpGbw1HlIROw9GrU6PvJzydvY7Kb6qmuab8Cx2j+oz9zXnpZsxKyMmOK+zwAOsIGCgxRd1JVFog9btA+NfjZv/FKpkgI45Keniqu52pn9HLPsQF/zNm4zdNrwVATqqaoENBLoHnNa2iXwmt9fuPweqhioqgIEVR781WIs9MAixZrc40gKB99dFO6oRYo6/vkB9p/LgwIQbxXVXyXY0Tb3Ay35Fp0Jb3b133j9VCIw69BRN5yIOT8E4TQiRPsiaYobCXBb+/4k+a0fuyd9B0paTWswZqAxpen6YzLdLzHKQoOpkRS1SaF62chORQVj+IaePw0+lRlUaQJzIbHpFdByGgLjXt/hZA9vVOHpz1awq4C3EwoE0/4FWjk8dQHkZWev3EybkUUeYxbNflzGQWN97o2Ts+aJEynPh2lDOZGMq+o6RLzOd1OtWhdVo1/tzRF/A8nplD3xpZzeQBI39evJRvudDgpuN7SxhrBG5KYMjjsRZNG7F6+SgjMpXnPdUJ6edSWsvoWsWU77a+vPMNMrvYJekvt16IYaaugvbDKtk1dpgSKQ2KYyW8ysBYIHmBXjwko2Nq3uEYwQ8UiDEJINwZYEpbP0ANCRKc67IH9geSp8TCmB8Kb1wQAtAL0GiJDxE0eQuTAmQbxLcOHzV/L0nQlGZQkkmSrpow70tsH6XiLNkP5ROjQWpuBxNIOFYhZVtF9ce7TLWx/d5ePSdBYRX26Vst1lpd8WHlt76GlugIiChSplKliT9xifqJzEPyUJ7g,iv:UIU1HMbrGgWiEtAFQ4eKn9B0wVPu8T1VPGdTUqoNIjQ=,tag:sxKihwdexeI1lmjYXNkr1w==,type:str]
kind: Secret
metadata:
    name: prometheus-kube-prometheus-stack-prometheus-tls-assets-0
    namespace: monitoring
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NHRvZEcxMWVZcWpneENj
            dzl4NFBYbnh5SHpWVVJmTzV1YjY4cTl2VFZvCi85UnNxUVM1ZU4wSm1YalpHUHA5
            aTBDMStiZ2NSMXQwSXNkakJ1aHFXTW8KLS0tIGx6azcwZHBBSGVYYlFTR3hYalhY
            MzBYUnRSZG1pdHVMeTJ6d3ZGU2ZNZFUKKnr+iwGWnWGdZZx5ZKUuIe05tU65sckP
            SvSpe4CAzZnuata4uFlbdcU9F/9wrSDk7a7bUCejIcwlKeV7jG2dMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T03:45:35Z"
    mac: ENC[AES256_GCM,data:oRM3ECV5mliCfSbes4KifcemsGzjgsk8QMdLFxg4P6R+238EhyUTZr/Ygclf3Qf3sJ7widFiJNZWoDfc1ybRzw+yNqk+iYx8ov9fbPuW6HUIzkrLjgnZ1lCOujwvwkNlJOr/ob1kaAfAC7w1FoXnlpZIT7fd+HLhSqFuPHwZdGU=,iv:lbMGO9yUi+sYEAor3REiOAwMQeJFv4xqP4TmTGzy1S0=,tag:tICKkjVXABoKcGLAYdu/Qw==,type:str]
    version: 3.13.2
