apiVersion: v1
data:
    0_apps-kube-prometheus-stack_kube-prometheus-stack-admission_ca: ENC[AES256_GCM,data:/1PskhUMTgF/t1pGuM2AO7+zwduYXQ5L+8qmSSOeUPNJVe/BfsEfYboj/lUbCq/2oQIwbVVltEygGegNxg/t/Ll4nrKRHyIkU9b5u6DVwJpBLH2CfAuEdZ54tSuaWAQlB7F6A1O2iHqAtmFZmSN3A5Y0pTd/NK8cm7MtGJDL7GB5Efj5zA7JNKWn+DqNabXHkP55FUGQkk+KQloArFkI54yG+Bjn54ezZumlqSswPSqQDB6lbdl/itedFbpFrf5C6O9XMFPYbWAtJvcnJyw0UTMCPFU0yiR/4WyJPTAv3oA6+vppwX77jdWPjnMLYfJxTiR4eCOLAqnHC9vqJRk8Mi0mU2XpkA8RFp+NwrLyrlDTtLb9ggqlB+ewiRJoFWpBPqKwPZvtC8nJRo/2FbJayMn7Rs8NU/eLXCbguMdc2ks4m0AIQ4X/blWS6DwX3DtlShc6Tr9SrHniS5qIYeyy6aavum3Vvtvhn7v24petPB8Al/IW5dUI3x8oyU3xugoUqLg4p1eV5XrLRm2nt/qLEHLfTjx2BhDUCW0AD0RGiucGahE326LRBlJRCxoayOFqUQa2VG2E24PRqiDxeNxz73wWkV2cFWOyyaH11OYXDvGwclrkSULD5vICPwRjmthmoVl464HNThRbq1Ap5wFtBLSoN42uJVheDiCmotev1XIF40bzkKmopf0v/q1FwX+jOHFB0l/pKZtB3bPtERP4K8rf1zuBma0VExTtK7YGm9xAGfFE9ypPIjB6rTuI0ZSwooTPfVwAI2hr4CfgG5oaOd/KdvT1kjnq7MKynvABsfDe7f6qv8hmRofO4dYXEJkPy0zno4Kk2V7Dq9LUGsNgDPLKtxcOu3nKIRfkl8hXwJoqcGlvRam77ySfnjFQoAHhacB3KbQ7cO16t+cpEj3v6D+Xu8LreLLbtuznD3G1XceOTJrUbjj5RrQsnUA15t9Mt3TuT3lNk10JCCprmT6GGdQkka82BIY5QrQ9PbgUJr/ZPRLc,iv:MxAtmSVbJA6y8EC5ABS6yd8F92nGz9EwDgx/TNxleYw=,tag:jcxhlvjFbMBkN5Ui+Daxew==,type:str]
kind: Secret
metadata:
    name: prometheus-kube-prometheus-stack-prometheus-tls-assets-0
    namespace: apps-kube-prometheus-stack
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa3VJNTljN0V1RS9qYXZU
            UVRWTUVVWnl3bFduWjUrZ3VQODhLelI5TUVVCjZvZmREYWY3OGpoRVA3ZENIYmE0
            NEpua2tnNjBkT2RyaVUranJJaVkvUkEKLS0tIFNBM3JRNThCYnl0ZE9KWFRXSzJk
            NkZOQzM3QUVJaXR2L3dueWhoRVgrcDAKQ++tFGSclrX6Uq9qjt8fhcBvL4/+v4Vf
            V7HsH+PQ7jYhvvpoDpGkwfEvgXQAPw4K0IRqz601f02eF3bMGm3LBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:01:24Z"
    mac: ENC[AES256_GCM,data:mHNhzQ0f0nSDaFuVUJjRQJKmSe+tr9mqgeCR6BnbtxBBnzuGEfQ1JOx3bgHGzuw2nybjIWIt00LFV2+shMpjgZ/TMTyNvpNZrPsCVRQUzd32KUOUmGd6klwkrZV7Bxjnf9ngBJnEw13dF5yfVe0Iy1g007v+TFvC9ytAOjcME+M=,iv:j1BTMPBVLgzEfiC+Awz0UfJCjrUG7ajEqTY3q22erA0=,tag:6v40SWq1igqcg4Q7pvf/iQ==,type:str]
    version: 3.13.1
