apiVersion: v1
data:
    prometheus.http-client-file.yaml: ENC[AES256_GCM,data:RnvzqZEy7zQWp+MIbLwlfRX/KB47ujYPFds4dOncm3k+OAgNzwxazNvrXSfqVeMjSk0ph2gmAww=,iv:+EhYnzQe0bdH5VJS5QGNv3RGaUqKYJUbD0BXNheAk04=,tag:uSxRbklk/8LCLjLvgE6gMw==,type:str]
kind: Secret
metadata:
    name: prometheus-kube-prometheus-stack-prometheus-thanos-prometheus-http-client-file
    namespace: apps-kube-prometheus-stack
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT2JibDB4TEdHaWVxSG1v
            V282VEh1NmlObGZqWFlXRDd1aW1vMElENnlvCjVlQWlOOW85VUlBV1pHS2RlMzd6
            RWxaR3hvNVUySmo1Z3BJNDZkb0tBZjQKLS0tIEE3aGlad1NaaFdFRzVFNzZRODVu
            ZVFuWkpsYjNZYlMrQmI1ckdxZ1hJaW8Kna1AHA4qBwLXZY7FWTqpdf54/B+lG0k3
            tCDWaM5FFiFEb9AWuvGa6AkK1mHBbt64MuZ+uEoWhtWxA/661B/kXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:23:00Z"
    mac: ENC[AES256_GCM,data:ZaoM5Y8cPso8lLs9w+ZS13bvLiorje3ySh5ZrpLcyGp1bzdb3/cRYSX8gOuglI07EBSXUP87Q6FbKULUYlYkZ+OBbhpyRhIG+uXYvU3xDxDKxV+d2dx2NmVcKfsgvoZLJ7tEfDGDmujzfihxYYijpeP4Cu1JQhfVRbfGDbltds4=,iv:n58N8FEFyj1Ft7HN6ucCS0mih2yUrjhc4hPfXsQDIl4=,tag:DTAtzXpuOh2RkugyEhMPtg==,type:str]
    version: 3.13.1
