apiVersion: v1
data:
    prometheus.http-client-file.yaml: ENC[AES256_GCM,data:c5W2Mz8OCcSwexs6rxKiUrpSDWLWHxtyhIfMTirzMqB8vm/E0nL3Z8L623LrPCHqCV/DwzE2CrM=,iv:p74w1RbR6rLYO5DgMqk51Bk34zS5k3AATGrthyKpWhM=,tag:vPrzqlfJDNcsHCEk7xilkQ==,type:str]
kind: Secret
metadata:
    name: prometheus-kube-prometheus-stack-prometheus-thanos-prometheus-http-client-file
    namespace: apps-kube-prometheus-stack
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UTJzck5DdTBFK045aEY1
            aDdpNVF3YzdhdXY4NmdzanBjU2FIYUZveWpBCm5FS1doMTVqMkkyQ1M4cDJKVGZF
            TjhwbkxjVEVPSlpjUWFmK081Qjl0WjQKLS0tIDlQais4eTlrV3dvWGozSVl4aU1Q
            b0ZUZ2E3Z1AxM29ENEFMRDF5aXlRSEkKw3Rl+LsB+laQgF6QJKDOLAOFTzhA+yBW
            Rq+UhRpa2A7B+ZIOO0W8Kjj24BZHeoS8486KTjsI8bIf3eesRp+U5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:01:24Z"
    mac: ENC[AES256_GCM,data:e8Y0dubpvkG/thhG53EiARra6FMQzc8Z8W1lkuqsr1OSlzB2H5XwqeryFzp5jpJgpOd7tXR+lO4SGz376P8HfsnPLKOTamx7A/EM0vhY3odcPO8Xn9Cue1B5IULYYtOtDjWv22AVOduXafsqQl2NyTZBzSpKDY9aBSKBeLgt0KY=,iv:+9DUl0ddwLC9/J3pUERHEHdHU4qrjYsUbsy/g9FWy7w=,tag:kI1E/GChfP7UXTPIcLr1jQ==,type:str]
    version: 3.13.1
