apiVersion: v1
data:
    0_apps-kube-prometheus-stack_kube-prometheus-stack-admission_ca: ENC[AES256_GCM,data:XyFWRS7gwGq736St4/1ku1AcSiD7SBYy9TqyLrukQy1m+c8MGm93wj9RyDwpF5k2AMM10eDZAJJFDcJS3VjzNB3gwdy4G6zA9RIkBon06Kjj3zfb8ULvNpQckF0CvQWiEnN8oPrNu+MyjmVa6Vto0BurnC+q7MY+TC1ITRoblQpSVnZWYIDmP35IUsf6qf9j5fXdrfWDBqXV+cLhCjeyW1dDgPxAN5AVMK2QQuEH9HEhrdssESW93becamU6dV7e5tVdPrxBNR5kdx22bPkArG+T5RcKFaTdCR300A11mWDwZnnnr0cRq3RzBl1ed94X0Fl982sVKicjhI4Is+6Ei1FTQqsQdjlDYhAabwymJqIwj7mkZAkYXCyPAyHhiuKgNr4tPuqyRyyhKOOqaCEDNlXeZECKBLvh0F5nG5u+KYQBsga2iefLu9g82KkT3V59lXWWcsa+h5T1uvOwx56w9ZTI1BsouTNdC1ZNMhHYBIIyTeobS0UUQ9rsTU00PLTPLN30TfhRRA1ZXUB/wB2ofj31vIHYHW8gVTyGaEjSxcnvzx9o2ja1VaU/pQ/JK/ufcCae60tirfHSYPxvj4eHzGp2qKh15LhWdVeYaS1bWPooOONbpAma8e4rMMwdvghtaOju9muFFw+W7KzfTV5bDWvMm5MUF5bWZxm97XBED3W5NQj18pfmu92/oj/HQJY+Lriv/TXAjQpFCHZoiqB0OMTVqdlIjl+u21J/HTKH+rkLtyWW8ybdcVAMLYX9cPhBuZtdgBrsA9Eyv4T0kOYOsBULLHQFcRGvifgj9atxFYZ3pjI4AkOy97inW+ohdoL2h/V/Ss/LVxrXGF/KTJMGqlWbelbnFmPAIyQuCMQt27loKx95nYXeCCTdbjuvh711nDpk4FsMuWX9MQkqvTH+LhQqpcOqQfbL5aYPKZL/eGXjX+d4xIZtLU8G/zVCF14SNP4yt0PldGvMqlqYuqeDLa5qbgRPjCc3OID6dTo9ZOEiLnsZ,iv:kMacLmUw6RzfvE4anwynUP3GCIeY6oZinbi4dtH9+aw=,tag:WO4u5khV92KTVhAUSHLg6g==,type:str]
kind: Secret
metadata:
    name: prometheus-kube-prometheus-stack-prometheus-tls-assets-0
    namespace: apps-kube-prometheus-stack
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0T2w4OXhLdzJHYWRpVzd2
            MGtCMnJLM2JTWjkyWk5uaEVYZUIvNWI0aWtJCkR6RkFKOVoyb2xySk9DS3BqZG9w
            d25hUVBvcEJnbmk4Qnl0SVpYYXNBbmsKLS0tIDlmWHJWV3ViSGh0OFJ2R0pGdncr
            OXI2N1ljRm12T2VqWWdQUm1MYmJzSTgKjLKF17hlMM8i43bApWkU+9GFgem82Kuu
            lttMa+e+gmnbWEVVYHmEjFXfjjMADkwtgjEnIc/keINKuNqTtCIPcA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:23:00Z"
    mac: ENC[AES256_GCM,data:wqO/kPUlBOv/pX2KtR2GhD5es9mj6ERrw2NrddL1cSe8YTdYfj1KfFq7kJynj3MTl4pEYCdTTk1tusIXEmu6jrwB4iSewZs33/5yNVfjY177KrrBvYM0c+uKlX5rYXEJGh4XFX5+BfySS0aDj+MTyRKQVPh0G6tm23K8K+dG29s=,iv:WR9YgkNZ5SGUQMWa0j2TNYLPSDm+aOqQqDbmeR20Gzw=,tag:vV9YHMS/psnZBHTESkp3Cw==,type:str]
    version: 3.13.1
