apiVersion: v1
kind: Secret
metadata:
    name: renovate
    namespace: developer-tools
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:bylzwpMTMoABkHFKgc0YpWr7i2zw8WcHQvdOR0XpkTnJRUdo6vwYAg==,iv:30RyF/1kv5+LEIF3Pt39dhG+zwUfQur9EEV5AoKOCGQ=,tag:pNwHHTy/MgXW16xrASu0fQ==,type:str]
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:wqSS9CT01MR8gmG6eb7NmwI8uqW86Pz485VOJTqB5jh0XcUgvaeo7fmO3jMCGpSAxx1zT2etAXkMdkxi1lMeg0GQN4W4qNC68kq2JaIp9H6TpbpX9vRbvuMvy2kV,iv:n3/pAOzKCgKogFiHhlDYRpf8e+iGPz/NWm9H+MANeXA=,tag:ipJvW98rESb2Zai0DjNT9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByait1L2ZUOGtuZXBhcjJM
            NFlsZGJsZndudjNlOTNQeGlMUVAxZnZrMmk4Ci9FM2F6elduZ3hrMlBlQkJ1dTU5
            c21DUno2N28ydCtWSWFwc0RJNm9SZTgKLS0tIDh0NDE0L1hZbkxjV1lFZW5XMzBq
            Y2R4WklhSC92Z2pBdG9wVWZ6WDdSVE0KkEG3wXYzCwv8Fsh8eBF1jLNEhkCFepIh
            NUbM67Ux7NxXtcXSJTjKddC3FU7oKTrUVFQQ8HTslECengvLMAaYQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T10:42:04Z"
    mac: ENC[AES256_GCM,data:XmAwVrYK9cBi/gUtgyAtNnfy+dED8wdPENRBDS51+nDKjdE4u/tDJ6XTuJfjQxn7CR/nzy2K4cKBS2e7UjBUUxV1ClMg2tQ9wIKxmsOS+QIbDmU4/bT830++Tc+oULkDRs4UE5A7hRRVf4/WCSUDyXya0RIzcsvsAQKbD00r9zk=,iv:xx43aGJaldFw+k/LURboDdBvS2yRvj6NHMuctzxop+k=,tag:Dfgv1476ocXorRx54Q7vaQ==,type:str]
    version: 3.13.3
