apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:J8GsJYxQvFkktCa1cWkLYseihIMQ/xXxKwEosO3JEszM818RhCn6G0W5ioCtFVhZloesNKFK0d3dNjMDmgG0YCfkDuwkAmosGkA3CYY6SuxuZCUpfNjr3/hisSouMGTPa6hAAAAcs6uHw7vLWepje2vmZv0tozZBVO/u31jLcqNo4YdDVKBI4fFKPqH9u+lsqserayp8GYJYF54GHboaf06LU22HqaDYxyTW7bacEwOLq5jXrj4IkAH3o3xfcz6XsAPRHL1Hb8ZBBnnE20tCrETOCuMsTJzDiKc545ZkexOpJdakhLpyqAXabnMA2FOqJBAP0TyFGMrKND95,iv:7DgSvBx9KBWRWkngQ3oMQuzHb3kVfYiuy3FJVx8aU+A=,tag:pDxUddk8rTozzQkoz2qCyw==,type:str]
    identity: ENC[AES256_GCM,data:6aapc4POUTRtFGfKFQhRsMt5u1HVjxhNRnB3RJt/3+eEzZYG6r9+gz/kstUCKz0AWsKU6OE4V6gGg7sWz8ez3zbM81J6b5TKx21noz/8LH3W4PsN9/1dr1imJXyFN/o8eoOulU7rvlqo0a95HooDOSAhQnLCO2FRExrznr/F1tkyTmti6oKrXma+JHQhXeYcpoomVILXeJmtnCAznn1r+GkF7kpdJCKBbdp7pywNTXWJvHcp+jmGfjs+5NC0LH4qWnfLYztQQ5Kg/Zpq1GqC+X8fXImImGaQRz4E+6TtdfFSLJ5S0BIBxydmqVtcWUIYLOyEcbj5IjXEBn5F,iv:tRqUuMrEmRxx3q9Wz9NjgDRMyR4AvMInLTRaWwpSMVI=,tag:teoWlflWugC6qCRyYSlNRA==,type:str]
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYSsvYit3YzBYRituZVc3
            NUxWVEI2MllOUDRpTyt4UGIxRUJNNGFnZVZjClAwTmNQNXhzOXlEWFBBeExlTDFl
            US9rNzdYV2xaaitub0JlNyt6anJsNGcKLS0tIGVQREJTK0YyQUdoTjhVN1BvUE1o
            Vi9qek9VeUxPTUw5QWs1eC91ekE2R3MKX5A1XaZ/S4u6padS6OXO6GF/Ksdk6SCu
            2+3z3ftFisxDxRNcRl8VXGyTIg3MNYy+yxxDzGjEWzw7iw4Zae6OLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:01:37Z"
    mac: ENC[AES256_GCM,data:PItlIHL3PsrNfCqHHwkfBaHxjUv8k2KWHU1xOlO7ql8xRg9BHeUMKuRsavBfkNBM5Ax3s5yRPXJ+wp4ku2wnKB+Wtfzu4nWa2aMMFGwoFDIKNW9i4VOjnxG10nnTEfDRNSNqy37WXvY6hivKYSVW7yqwZKEJwKg01o4/dHPRIew=,iv:U39Exj3epRK1aV81rnvBM7L1xvywRL87KFmeyRw6MKE=,tag:SZO6UpylKhrA6uavr47nuQ==,type:str]
    version: 3.13.1
