apiVersion: v1
data:
  age.key: ENC[AES256_GCM,data:GhDgzMjxH8/4rOJRxUHCe4zjCdF7APABv/m6hVIqSmj6/moYxd+h7ErlBMkqMmW27Nbk+ejGintJNPaLYccxNy786QgOfVp/7g06b5BebLAmHb7MntrRNbVtKn6Q0n8/Ads7oEKNCmmnz5m6K50g9TaKzXxLFKqJSqY0+VsdEtcqjWlMpXsaBhPK93eRMN6JMALc97o6I1cE/x9H4IpYvyh3Q4RWlxePfwED/vMxHRVQd6vFov1RYVevU2P/tSwVo653jVzTbTrVEv6ZpHB70F/SoyyQ5Vxb9beb1qPGKCyS6w1f8CriQO/ifBEE3slkKVgbiXkUoFmrmBsw,iv:PDDd/8NnSPrsfMi1dA1yKHFtIfGhqVN7tvTHPPz2jZU=,tag:/CupNPXPLEMqh25gIrxusg==,type:str]
kind: Secret
metadata:
  creationTimestamp: '2026-06-19T10:34:33Z'
  name: sops-age
  namespace: flux-system
  resourceVersion: '3044578'
  uid: fce95fec-808c-494f-bdd0-8578b0907a1a
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYUlSRWxleVJiZEs3Nm0v

      dFRmRklFOW5RMDk2ZFhqYy8wcU5saXdDUzNVClo0NmswbEgvdklBalNsc3ZEaG9t

      NkV3RU5WOTBnSy81b1Fkc05IZHg2b3MKLS0tIDJMUUJxbGZmNVdmdzdnNFNwWU1O

      NmV0N1A4L3lxZ2JKUWFWOXdZZkdYcDgKEHqpGVwnED59Nnvo8RJtpKY1v8KLiUdx

      dJTqSiGHZAHBUHgo3EgfHB/uHdJgAk95rW0ub+KEVuTZCHLZxZ6UZA==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-06-19T10:57:28Z'
  mac: ENC[AES256_GCM,data:jmMeIWbP4D52aYFbV4gd5srZ9EH/raWqbPZ+JOICbQG+Mai1sw/T3lqcLilbHyB1P7GgWX1rGPaHHclNtAtk0Rjka2Tkgz/ZRWbK+2Ez5LBUXUdBGii2DHF+KTE2bBmV8Qu7PU6jKXBJwkq2Y/GIbI+WGkvW8TLnov2ALCoXQXw=,iv:rmC8fDANft/GoV9sxxQO+JfYBnp70x7Xn9Av8DsHCJA=,tag:W/mvTRJNeZEdsF9UVJrCmg==,type:str]
  version: 3.13.1
type: Opaque
