apiVersion: v1
kind: Secret
metadata:
    name: db-creds
    namespace: twitch-sub-bot
type: Opaque
stringData:
    DB_URL: ENC[AES256_GCM,data:9LPFEqjdAL+e/hUAy/GTI9HSonCdWMV3R6vpeuQTZ2In+afuTeb8cmXeEHlOqdxk8d/lpvgmZdP/VqKtlI1voZ8BToez0MhtlnteGL66sfb0C6eBG+xP6B5BVyCIuAT+zkPiCad9V+sQ+xyr7BgdrC3ihwDKWgEkisKp,iv:CTVTqLfZVCmQZTLaqBZ5BN1fIVrk8YvKC1X9LnTcTOM=,tag:P70JyAr/78HruHG6UJ9iKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVE9DSlMxSitFcUdNdUNF
            d2ZnMFR3MU9GNlhOVGdyZU52OUlDbWVxUGlrCkJSSVAzeVJOYlN4RDFmbjF5aHdC
            TWI2OW9QZ0hia3l4Qi9pM09YNlk1VkEKLS0tIDRBQ0l2WENEUk5tMDRPNDdmbTZJ
            aXJPZGh0RmpuWmpSYy9BUVloOXJjdlEKnxsA0KRKBH82EaNa3E/m2gPogrVEnu6H
            7bpyAUIOaCV4vCB77CpfqrOxEKEXB/ruUIiv03gQVyWyJe8viqUfrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T12:13:19Z"
    mac: ENC[AES256_GCM,data:J4hI575kfaM7UUsFxpEpVsJ4/B1q8bwYtlIZOZ1tRNHjQkxiQKOLsbwHyvyxceHpn0BGZmi/hKiweM5KYsPV9abmSUoJC2PfDocJexCuJY1Qtgc6/TlWhIcRjhKk3nS/wDHPXJBjov52dPHvZGdMwL21Lk/EPOSK4XlK0Zeg5qw=,iv:BDNRhAf80knxyfsB/7knfAc5r0wVKlumMU+8uU8gqvc=,tag:T7Pn30koqEJ4P5oMXa//NQ==,type:str]
    version: 3.13.2
