apiVersion: v1
kind: Secret
metadata:
    name: twitch-bot-creds
    namespace: apps
type: Opaque
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:ZsNVX3T9sR+7h45K9QBD/FSGHEzPMYIp9amaMajQy3Fsf7mbs51BxteWIVtjhg==,iv:hqke7/ShhYfeSINeqUIJ2EQL+FWfIl6oWhKShqBgBCo=,tag:3rv3bbzyXTh/SBjEiChMBA==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:qTaRklwjAn1f,iv:g7EyKDdtXLxGcgLv3sQht4+Ig0DzirTFNUHOZows+Cw=,tag:B4FxioEMjadVlYdG9CxCuQ==,type:str]
    TWITCH_CLIENT_ID: ENC[AES256_GCM,data:7hR82zlNVALFdhx4Dtzl4ik/f9hgcgsU688f3+cG,iv:yI3w40HTgZ2CIhYUUpqZZFdvHXcnG2kzSZaJOr8UzDc=,tag:/maKhUbuDL6MWfqhux+N6Q==,type:str]
    TWITCH_CLIENT_SECRET: ENC[AES256_GCM,data:R8Dao5O+gIOAeoz0q4os1PEAXK63RXvS4dd/2sgg,iv:KD5eCU5TAb6zw6GG6xvC1IQLAWWpzkjhHtb2p+qIlFk=,tag:KvqWPFMRHNYf2fBWfVuR5A==,type:str]
    TELEGRAM_PROXY: ENC[AES256_GCM,data:pGpULCVWh9WBtaI/rC3EYE4ujQWjB2ALD6b5,iv:gnz9r1/NvFxR9PkTZvmoGfXr6XyTmAWAb53fPjIyzxo=,tag:2jTfa03+7AhguhCANP9AcQ==,type:str]
    TWITCH_GQL_CLIENT_ID: ENC[AES256_GCM,data:HjVdkSl7c8zEPRu+byiEbCaiZB/Tk4MMiSiLHx7k,iv:DjvwpZK7S4CaVdlrXHxGXFEMXqFAn/45cVtqbiN8qQo=,tag:nmI+4bDQx8pUJNc3Efd0jg==,type:str]
    TWITCH_GQL_OAUTH_TOKEN: ENC[AES256_GCM,data:O9eUB4y5aN+geeEi3tqN7w/bDn+ZsIQq5fID7T+G,iv:id1qDyZPmaojXWOm7DMN9OdehH8JJtOpBbLs94KkqZ4=,tag:PyosWvzo1wtu9Emsm+b0Iw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ei9PU2YrbWZtd2hLTC9u
            VUdyTFVWeUxqOWhOaG05NUVGL1RnYXIzTXpvCnZyN1BONnV6M3lzUlVGRGl0blFE
            T2FlM0JpZk1oT29LeVFhQXFhM0lyTVkKLS0tIHAxN2tyMlI2K0NMN0xCcnlzKzlr
            OCt3aWZXYU1tbmhOMW5ZMm8xY3lTc1kKGcer4HkdsGR4oFuUpp4mH/h+3BbiflIL
            2mdAyafl3XFVeHOVTAHq2t8JyXlaDJVAULUwir4ac3PhzMAVcoUdOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T16:58:05Z"
    mac: ENC[AES256_GCM,data:Hi8qFqabsDM9NcW56H2+Iz/rcaRbaNd2DVuebxtkkWcgXrZE54Hu8m/OQ6S+GBKkxIYRCngwJaAjodxVj4MiMS2zgpjciA2gVsgkY8rQqmRCEUpZCkpVLjr9Fja8gF2uMeF90Vw8zGjUDY3DPgrceFPBDOIVBrPlw/yuiY8Qr2w=,iv:J4F00qwlvN3Z84iADFhtLlbqXUSMXuXN6anJ1X0f8Jg=,tag:Kf67MmgYwTDBlD9I87EZ3g==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: twich-bot-db-creds
    namespace: apps
type: Opaque
stringData:
    DB_URL: ENC[AES256_GCM,data:U5WFrokFHejZ2v0PR6vT4q76IsoTeZgPMu+BEGLELg7CVbgO6FEnRTSWNbDA+bedLXa1Lddc9MYwCBYVCbJqSZmohMnLcO/0zXSe0yyH/sA3WhQjldlJg9fVQOgKiTDqXAsh5p2f/DmnBcWRB7BZF1l+WtEWRFuuN2UL,iv:vYmcMjdC0uC2PKMDsSFK7GU1osyFkhEghVwZ3wBafmk=,tag:Phz4dy3mQdWPxqB2GOR23w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ei9PU2YrbWZtd2hLTC9u
            VUdyTFVWeUxqOWhOaG05NUVGL1RnYXIzTXpvCnZyN1BONnV6M3lzUlVGRGl0blFE
            T2FlM0JpZk1oT29LeVFhQXFhM0lyTVkKLS0tIHAxN2tyMlI2K0NMN0xCcnlzKzlr
            OCt3aWZXYU1tbmhOMW5ZMm8xY3lTc1kKGcer4HkdsGR4oFuUpp4mH/h+3BbiflIL
            2mdAyafl3XFVeHOVTAHq2t8JyXlaDJVAULUwir4ac3PhzMAVcoUdOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-07T16:58:05Z"
    mac: ENC[AES256_GCM,data:Hi8qFqabsDM9NcW56H2+Iz/rcaRbaNd2DVuebxtkkWcgXrZE54Hu8m/OQ6S+GBKkxIYRCngwJaAjodxVj4MiMS2zgpjciA2gVsgkY8rQqmRCEUpZCkpVLjr9Fja8gF2uMeF90Vw8zGjUDY3DPgrceFPBDOIVBrPlw/yuiY8Qr2w=,iv:J4F00qwlvN3Z84iADFhtLlbqXUSMXuXN6anJ1X0f8Jg=,tag:Kf67MmgYwTDBlD9I87EZ3g==,type:str]
    version: 3.13.3
