apiVersion: v1
kind: Secret
metadata:
    name: twitch-bot-creds
    namespace: apps
type: Opaque
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:ZsNVX3T9sR+7h45K9QBD/FSGHEzPMYIp9amaMajQy3Fsf7mbs51BxteWIVtjhg==,iv:hqke7/ShhYfeSINeqUIJ2EQL+FWfIl6oWhKShqBgBCo=,tag:3rv3bbzyXTh/SBjEiChMBA==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:qTaRklwjAn1f,iv:g7EyKDdtXLxGcgLv3sQht4+Ig0DzirTFNUHOZows+Cw=,tag:B4FxioEMjadVlYdG9CxCuQ==,type:str]
    TWITCH_CLIENT_ID: ENC[AES256_GCM,data:7hR82zlNVALFdhx4Dtzl4ik/f9hgcgsU688f3+cG,iv:yI3w40HTgZ2CIhYUUpqZZFdvHXcnG2kzSZaJOr8UzDc=,tag:/maKhUbuDL6MWfqhux+N6Q==,type:str]
    TWITCH_CLIENT_SECRET: ENC[AES256_GCM,data:R8Dao5O+gIOAeoz0q4os1PEAXK63RXvS4dd/2sgg,iv:KD5eCU5TAb6zw6GG6xvC1IQLAWWpzkjhHtb2p+qIlFk=,tag:KvqWPFMRHNYf2fBWfVuR5A==,type:str]
    TELEGRAM_PROXY: ENC[AES256_GCM,data:pGpULCVWh9WBtaI/rC3EYE4ujQWjB2ALD6b5,iv:gnz9r1/NvFxR9PkTZvmoGfXr6XyTmAWAb53fPjIyzxo=,tag:2jTfa03+7AhguhCANP9AcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ei9PU2YrbWZtd2hLTC9u
            VUdyTFVWeUxqOWhOaG05NUVGL1RnYXIzTXpvCnZyN1BONnV6M3lzUlVGRGl0blFE
            T2FlM0JpZk1oT29LeVFhQXFhM0lyTVkKLS0tIHAxN2tyMlI2K0NMN0xCcnlzKzlr
            OCt3aWZXYU1tbmhOMW5ZMm8xY3lTc1kKGcer4HkdsGR4oFuUpp4mH/h+3BbiflIL
            2mdAyafl3XFVeHOVTAHq2t8JyXlaDJVAULUwir4ac3PhzMAVcoUdOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T04:38:16Z"
    mac: ENC[AES256_GCM,data:H9tlSk/T0lDGZxPUSMSWLeiWYTckM9Zpf7nVbEPe+z0dxcvvct372grUfDJKf9UugkkJMjJ8vp//sRgZgGTqTxgVf1LZKHM36JaUMpsuuJWqJ2Nhg4PVR1VXFw3mDYOE4v8aDQzT44Lsw1Prnm8Tn30Q8AafOnfTZYmSJrif+g4=,iv:TR2qZRwWUckINvs6fZ6BJoXmBOUT4FC7Rj3Sex9J8vw=,tag:RPQnTue4o15lvJENNlOINQ==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: twitch-bot-zot
    namespace: apps
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:P8pLp+uIa/KyrAL9JPpZvfkx8e/+iWjcuVDuLPOrlcJoXbF+OPqHuvbuqf7r6GIY/YmA0TxxaBSUVceunL0ZuEfy/RMBuE6ieCcuncUY43wiWcy81qX4n7OlJvA38KGBs+fpPbysSBuROHbDIURDoe+oORK+4Dm25ZN0ViEBPbgkphYfnMB7yJYpYpbltOQTPgW7WTOzrV8liHSZBl1JfltFi17Tg5miAikm1pTIOJo4wdmn3AKV2IcjQT0lXBrEcK1+71UirbGJ/cYpA3sf3n8Y2dK20l2AqXU+sFwcm9XzaO5xdOXNlFta51oXTL0j,iv:2+JabJ9xrvj6GcIfJwNLnTguOOK/Z1TrOQAjZvIl7T4=,tag:UklN5vHpAmOsXavcV0lbGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ei9PU2YrbWZtd2hLTC9u
            VUdyTFVWeUxqOWhOaG05NUVGL1RnYXIzTXpvCnZyN1BONnV6M3lzUlVGRGl0blFE
            T2FlM0JpZk1oT29LeVFhQXFhM0lyTVkKLS0tIHAxN2tyMlI2K0NMN0xCcnlzKzlr
            OCt3aWZXYU1tbmhOMW5ZMm8xY3lTc1kKGcer4HkdsGR4oFuUpp4mH/h+3BbiflIL
            2mdAyafl3XFVeHOVTAHq2t8JyXlaDJVAULUwir4ac3PhzMAVcoUdOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T04:38:16Z"
    mac: ENC[AES256_GCM,data:H9tlSk/T0lDGZxPUSMSWLeiWYTckM9Zpf7nVbEPe+z0dxcvvct372grUfDJKf9UugkkJMjJ8vp//sRgZgGTqTxgVf1LZKHM36JaUMpsuuJWqJ2Nhg4PVR1VXFw3mDYOE4v8aDQzT44Lsw1Prnm8Tn30Q8AafOnfTZYmSJrif+g4=,iv:TR2qZRwWUckINvs6fZ6BJoXmBOUT4FC7Rj3Sex9J8vw=,tag:RPQnTue4o15lvJENNlOINQ==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: twich-bot-db-creds
    namespace: apps
type: Opaque
stringData:
    DB_URL: ENC[AES256_GCM,data:U5WFrokFHejZ2v0PR6vT4q76IsoTeZgPMu+BEGLELg7CVbgO6FEnRTSWNbDA+bedLXa1Lddc9MYwCBYVCbJqSZmohMnLcO/0zXSe0yyH/sA3WhQjldlJg9fVQOgKiTDqXAsh5p2f/DmnBcWRB7BZF1l+WtEWRFuuN2UL,iv:vYmcMjdC0uC2PKMDsSFK7GU1osyFkhEghVwZ3wBafmk=,tag:Phz4dy3mQdWPxqB2GOR23w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ei9PU2YrbWZtd2hLTC9u
            VUdyTFVWeUxqOWhOaG05NUVGL1RnYXIzTXpvCnZyN1BONnV6M3lzUlVGRGl0blFE
            T2FlM0JpZk1oT29LeVFhQXFhM0lyTVkKLS0tIHAxN2tyMlI2K0NMN0xCcnlzKzlr
            OCt3aWZXYU1tbmhOMW5ZMm8xY3lTc1kKGcer4HkdsGR4oFuUpp4mH/h+3BbiflIL
            2mdAyafl3XFVeHOVTAHq2t8JyXlaDJVAULUwir4ac3PhzMAVcoUdOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T04:38:16Z"
    mac: ENC[AES256_GCM,data:H9tlSk/T0lDGZxPUSMSWLeiWYTckM9Zpf7nVbEPe+z0dxcvvct372grUfDJKf9UugkkJMjJ8vp//sRgZgGTqTxgVf1LZKHM36JaUMpsuuJWqJ2Nhg4PVR1VXFw3mDYOE4v8aDQzT44Lsw1Prnm8Tn30Q8AafOnfTZYmSJrif+g4=,iv:TR2qZRwWUckINvs6fZ6BJoXmBOUT4FC7Rj3Sex9J8vw=,tag:RPQnTue4o15lvJENNlOINQ==,type:str]
    version: 3.13.2
