apiVersion: v1
kind: Secret
metadata:
    name: twitch-bot-creds
    namespace: apps
type: Opaque
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:d4zV/Gjr41p/mQTXusQoq4P1XPi5NlHtpkfqFcDvT3BzGzpMOd2R1/lQTqs1Kg==,iv:gLwNFulXeDL4bsqtAtCt3zWNJlZP66WVI1i6VIShSJ4=,tag:7Zd1oH2aM5i6laCN2/BA5Q==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:85lsVcSDQnZM,iv:+su6drwMw95FbaEZLnyFmlAYjgVXV55iSX0P6cwAuQ4=,tag:7D9XltZ9LYayg95mD0D68w==,type:str]
    TWITCH_CLIENT_ID: ENC[AES256_GCM,data:vzagYOnKhhsr+ElqcQ7BVtdzrnAgEFN9iULYBZp2,iv:4LFkrVPH53zfhTMD1SvZ2dc99FzgyJ5R/YyxJtgsjfE=,tag:J+EfaFNGJz3k9GLk/TRWoA==,type:str]
    TWITCH_CLIENT_SECRET: ENC[AES256_GCM,data:zf35XH7/i4AhhJou2A3yFWQy/Azvnqe4CQg/yisd,iv:ftyFX79HiZv8mE3WrZZVUPEAv+YC6H0755K6ZlJP5JA=,tag:mHd5kpXkita1B6uI0Vibiw==,type:str]
    TELEGRAM_PROXY: ENC[AES256_GCM,data:7Cmgk4uEVtEz7OYdYuoY5je6vNSVBd5CI5wa,iv:KBwW67uJ+tORsGsTLEherc1Ja6hgNRsFhY1E2BGDdl8=,tag:IfbF9/sT938elqslmvH3qA==,type:str]
    TWITCH_GQL_CLIENT_ID: ENC[AES256_GCM,data:/JcXIhAwuWVw/1AexmncgpFKpLFfnwYendknp/0i,iv:HWS1j74Vw58VyAPfhpTkVuZjrjzDtYlBxFIwdEMaCm8=,tag:uyHtcR9padB5DrtBSQHpqQ==,type:str]
    TWITCH_GQL_OAUTH_TOKEN: ENC[AES256_GCM,data:bv0704boVJP2ioE1uTJWon6i++w2OBGxHVQ/lxPl,iv:s/j7PJ1QpZ40lXfp+WYi62a4qW2GrsOcqyt+lGlxMpQ=,tag:1W55SrEm39i8EFvPgFsmTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUjByU1RJM0ZPWW1lM0ZF
            VGJiaTVqZ1d1NmVHY0lBNDBwTC9MdjNMQ3dNCktEN2kzRmpjSzBjMlBxOUVoWlho
            R0JKU1E2ci9GbXg3MlF2cUt0ajhNQ2sKLS0tIFJGeVJNaFdsMlJCSEVwWENUcHJ5
            QS9hYXpUVHlFYjFPVG5MMXp6QWhzM2MKn+LGcq7kqAkWQJoINHLBNwHvveODLT4S
            9zV21kMo1VdXJbHcICVGLcnZkX08/NZwQvqQbOi7K0v4owXu1hsTnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T11:36:08Z"
    mac: ENC[AES256_GCM,data:tVAyYKrnfKcv5a/+bg0nCgBGReSBfTTCTII1ueMlS7CweJ09NyC5T4tjnWUuH9KdfhofPVRiyviD6gtflOxPMb26tydA3M6vt0U+RTL35rju44rXuabiYX42iRllWM3Ho8GdsYsS63txgiV3G7KH0uNYOPMuyP/qxVBcEn0v858=,iv:FHL7wL1AJNq1coliVQjfZ1ocWFETL7psLiNkDKG//Rc=,tag:712KSv5aOPqI8wAXukQ/Vg==,type:str]
    version: 3.13.3
