apiVersion: v1
kind: Secret
metadata:
    name: zot
    namespace: twitch-sub-bot
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:sm4euUmswf78CYhirxvrjXHsigQ+uEjQcWQnEuOPvSZbZcrCLIqT11lyZCQIs5F6bQAItJSOojLe2EDfOVe4m9xPUSINc1cdW68vZOFhpBILnrt5SoaXmKDfibSpIiasPtNCyGHG6q97sxCqWr51/f9jX+9BqcDFHUeFueSvB4lpDEsryrXrY18NdvU+2a6g5WJ8Z38006W1Y0RBI4Y0E2D1DQq4XU2FwYHfwJ4rIdcWudRQZdd2RpccbORPV3+RvEA+f9YxRo9YbaFkL9SiGOynW2q5n/jMjI/+vim4STII4Sioexgxd+Iwu4n7MK52,iv:IFluEHkRefovUBLOPTtpZAuNl62LLH2tyAF+RG6d6iU=,tag:c6wx4YezQO5gO64yabuADA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5M2ZVaHZITzVZeTAycHNp
            NU8xZXRtOVVtV3Vvek9oQTdmYm1RaTExekNJCmxnWnlmaERDdkFmd1NRRis4L0Jx
            M2drVmVXbktQNlIrUUE0OVAwalFvWUUKLS0tIEZMcWhmVWNJbTVjSGNNU2tnWFNw
            SS9mOXlJQThJczRZOVZHbjBmTDJMSk0KxauA8j/8L857Bv0b8yoNI1N7JoiSgFMt
            PfhdYUPoN/QpholSJpBYEFHw6Nx6LgXIVJAL0IFif6NpiJi7Phiqvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T12:41:04Z"
    mac: ENC[AES256_GCM,data:yf0WN3m8ZCWp/t/dNrPqGA6Pvb5S0Y23FUvpjG/CIh5i4h/opBGsRNyyYKZlfGmblrfgD5Br9Bn/8oDHvr7iU/Pwavwu30x/ZabevbKL3Me0w3bqn909t0qWHO4n9GAkc1vMvEOQk8udz7x89YwwdMy/g+fCk2dRkR/hCPRihcQ=,iv:qa4RBq3/2ojZxmOM1z1/7DEIncMsz366lHV0hbZDM58=,tag:JZICRRjaH17LrJCtHweN+A==,type:str]
    version: 3.13.1
