apiVersion: v1
kind: Secret
metadata:
    name: bot-creds
    namespace: twitch-sub-bot
type: Opaque
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:woTgJTGMaqDnc2HfzOibucnJ9sHO4DounrJ3I0yqIOx/8rBzmr19N2tQBfwRtA==,iv:TfPDjxSI9NjIFJLpYRG2zousloXTkJ1CG7kj3Rczh4A=,tag:SjcULXB0K2xn3K+WPUyOzg==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:ImY8DysxNx2m,iv:DwbFIX0mfGNs3mjmmnltiVO30bTcYB5fVS9n8Wco3PM=,tag:RlQ0G8Z7hZ4vVtIB+PG2CA==,type:str]
    TWITCH_CLIENT_ID: ENC[AES256_GCM,data:VzLtAbwE0MQfLhDzOI8kcE/6UIhdbfdbfxqe96GL,iv:L94XYTQk79PRyDhXkczUJopGYg8EP9v7ZNcPYRNS1JY=,tag:n6pCkSnMzrVH/Nl+Iu6duA==,type:str]
    TWITCH_CLIENT_SECRET: ENC[AES256_GCM,data:s/F+E3h32I6nYzEP+UGwghyvUEkm7tqk/mMXbDu3,iv:mw5Dr6W73eitkFXPZS5ARtkCB3A0K1sf3tzLhJ+TvpM=,tag:LKOG4u7n96kH4zUehp+8ow==,type:str]
    TELEGRAM_PROXY: ENC[AES256_GCM,data:0P1FJTSmU/G2DxArE4EbEI7yYRPSOQ==,iv:8ajSf98u4973fv5zAqFRm2LDLBQTy36AlaytBfpNm/s=,tag:ohpbeCgo24MGvte6I6AV/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJN21pVXFyMFI0dS96aUZE
            Wm5ZcFhiMXBsMkNWK1llemNyc09oREVlemdrCjNGSElsU3ViclAxL3BENmcvQ05H
            bGFoR013c3BMcHM3cTM5UlNidWlxcWsKLS0tIFZhaHlMV2huaGpmMlpITmpoWi9E
            dW9QQVUzU3RSMUNwOXZhWmpUSkVKS1UK9YEULReB0cKrkdjgjLBLylWS2f9Pmxnr
            TPoRU9exKvnfIUg0Onh6WqLHMuI94/Ys83+fjU5o+Ckb/0OcOYfwLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T08:38:50Z"
    mac: ENC[AES256_GCM,data:tQYIrvkq1v+oKWAOPNHOwCUz6pHG9smbc0fu2Yq+PakAbb2B1Hd34GylcQw/TtWDMg2b//6IV6cxwY0jiNAnDzY4VebxtGVNHBz1714pUFmN3OLq8lTfYrnRwgvyiFf2soRvz872Mkf10migh0ijU1NuNRz/vMSMvSH5kmlKZPs=,iv:CeHJA+NnFBwLSVCEzFBZ/9loB/5wiPYylkno9lGrK4g=,tag:mQvM4OH1ySdf//mCRF+neg==,type:str]
    version: 3.13.2
