apiVersion: v1
data:
    admin-token: ENC[AES256_GCM,data:R24+YGef+7qIyjRw32E4jCvZzyqVry4FPf0PQ1/xYtJ+Bptas4rCkE3K+vi0XYkMlSV1erOTMArfRfM6T6Zs79Pko+1l6t+54LNOmSJzzwpJSsNMl5qMS6tSlXg1Xp2vGZ+2O64Gz9kbsHR7yw8p3qCwpwShgw==,iv:u8mZWq8Xp2RzeFYNwTkgh1htVM808lhy9/hPehisE2o=,tag:ISactHWOF64hibgRw+5Cmg==,type:str]
    sso-client-id: ENC[AES256_GCM,data:8TIYXzMrDUi02aUmkdX8Ov8cCfy+ABTtm7s9wgSusR+MQ0Ry1XSz9g==,iv:XbYdxsQqN8iavDjidUH4ezWwpmG/7BfXzYr2W9kZ7JY=,tag:xYOWpNv9w5SJ8NQPUN7Y4A==,type:str]
    sso-client-secret: ENC[AES256_GCM,data:wUKiXCY8AY5U9zdYXzLiL0YJ2al6tEgEs2WVye81FYbMXamcZzz3a0j4wIM2YwP2Kjpoan+grXWG/r6YtKz3t2hle76ijwt05QasoXmwtliDu8QcyByl/O3BTmBdgg2v1pqsKS/knjiP9OfZo7VviHa1OXRsy9sjntB27VaPdG4=,iv:75oR2A+4/EMDqXRSnJdzEsPrfmjH3XNSrlMtHW1UJFI=,tag:et1CmcelKZxR7YZkuWzlcw==,type:str]
kind: Secret
metadata:
    name: vaultwarden
    namespace: apps-warden
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZUM0UXV0ckxYMzRTWlB6
            RDhSSzlQanBDcUQ0TG4xcFpxQlg0M2FscTF3CkdPdUdpdE41NFdiOWlLcGRnd0Ft
            VWtTUVJDajQ0Rk03dWZpRFVkQVZVYjQKLS0tIE1QM3h0OWx6NHlOMkhEaW8va0ll
            K0YxRE8xZC9USGhQZEZLSTNuV2pWTWsKXuyRXi88hXX4cuqIW/UkM2JbnC0LcPzn
            5yGiAJetzlatKxZYiUIoRmUBdTB6O7TY25MNVVxth5RWZIvNZWubHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T12:09:57Z"
    mac: ENC[AES256_GCM,data:D2ZoQz6vlHThVl0Qy5gcWUQsxNGJrlx4oyvE+5mfA808z6p+FZYKpxZGzk83P434qK7UwtZOzzF5PQzVu0KpfWR8OTLF6OglZv7c8uVHdhn2EulV0jtB6RmfhUcy8HCoskHM9DR62qIs5fUtZU8i84TBdwhKsanyjbZ5oADl7L8=,iv:z1X8CxuXNZqiuKwij1Aopb2IiszDx5rJQXfwqWUIdwU=,tag:H8381ARum3iPkV+I/hCNZA==,type:str]
    version: 3.13.1
