apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: apps-warden
type: Opaque
stringData:
    admin-token: ENC[AES256_GCM,data:V8QRaDOs/7cAQQZkw57xmbWiKoMDtp53ZShAUaT6rHrcApRlxT8YXpUgtmQ1OrmOtYZhSWzU118xMBXYKlOx50Y+auECpy/LcGa0uHEsoJLu6PKL03fiL36i+LxyLvAe2rpjHcr0z23NXBjKz1HNp1yXpQZKSQ==,iv:ryYbjZRlRaeHW7LgtJPsP0i+s4t/caYjnIZrGDGq1OE=,tag:aRaoWqN8aJzIrcRcKTlKtA==,type:str]
    sso-client-id: ENC[AES256_GCM,data:L8kpI6coSRnn+HF9jltefIW/EQzKb34Cjzgs0p+WTfr5Z1wd+43fzQ==,iv:r1jHA04PCEf/XSao/cLOrv7W7y8Kx3jnegnnUlTNgJo=,tag:+BET+UtUeEArYE+dqgas5A==,type:str]
    sso-client-secret: ENC[AES256_GCM,data:iFDR8bPq43Obr2CkN4ciMZ+lU+snUOzd+kyzfUse0G+W0nP4EHzF+xz6J1BZCsXVz13sE0LYEWRRZi5NL3tFNoZZTV5VPeC3Kq8B5DTChoFJ+v0g20fLZe2VnX0vwqtVyNcCdxjVap+nHGJR+402Z2HG0ALaaFKPFVQ3PS92H0M=,iv:JjhuFjdsFYPu9NpkWQbVtQvywGwr3enrK/BFI1ypJIM=,tag:Knq1md4WM8vwmT+M7CJDoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWWZzelFMMFNWMXphakdD
            ckJsUlRudmxzZVdoQks2YytHbFJuRmZteWxZCkJET1hsSEJCc09QL0FFcmNXMnpx
            clFsSDVIcXYrQXl1aW1qeHJhdmtRQ1UKLS0tIENVb3VmMC95aHNMVis4QzVKVGR5
            d2RqbW5KTTIwN2R3ZXQ2OW1DOHVOaVkKlP80dlb+b6co25rMpk9O4FGmS+afUroz
            oBTCX/iDPukk6PEkMe0cq6/qYO03ZKWTrNtdG+QbBtMEFyjbauw6fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T18:29:21Z"
    mac: ENC[AES256_GCM,data:o/WhSNy1Q1hkxdXi85IAEjf2T/P/eqokKvceOrtJNaYtY+nRbApbhANMnK31Bzcn1uC3VD5VV50iJh+KbLWBAbIcYhmy+1J5NET2n6SwsO2XP8JXpYJ81m2/Ah9eBiUjvBFNr+LcOaRA47iX1DMvFHIWOXw7qFeBFz31muzA5yY=,iv:3qdP5gT1EA3M/m/2xzCNG5gq5DeQ/1r4bHciHeHUnrs=,tag:bhe691NRA7ly3yz4m/U8aA==,type:str]
    version: 3.13.1
