apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: apps-warden
type: Opaque
stringData:
    admin-token: ENC[AES256_GCM,data:iLHAieiVNAZF60tVndkzlt5S+owsISAkuuVlVe+Ba9Auwo6YcbMjqy3qWOcGa4aLibiE36Gfg3S3cc/L5zllRvIuqFwqJzhAcf6ki/yiWhJwSAjLFe/QuAf/2dt8+QQrTYi36wBm1vg2RV/7koggoYYulfVVwQ==,iv:idS2d65ysxrBBYnsqA9gI6YmUqDoo+8FZ7Y6O9899bQ=,tag:PgXcYqWg3byZqRIetB3sdA==,type:str]
    sso-client-id: ENC[AES256_GCM,data:KXDMat0en/VXj0cVY8kFRaUCbWh/GNm3hCLYAusWPaCMgX85ye4vFw==,iv:/JeaPlTJROogfo7WcdBdLFV7CJMRsGQAVRGeNQm3JcI=,tag:ZAJcJAKT2h4hhyO6+h8uCw==,type:str]
    sso-client-secret: ENC[AES256_GCM,data:hKVKn3FOqCnjzNOgaTOspOgr7156AhIQEfvZK2s/Y3T/pejoMpjJMtmZuGqRmvaS0wuX46QlbSa0gY1dYcrv1v2rr2cMdD6IhEs8qsVPqduSE2fiWKzrXAu1FUP2cbJEvhF+zO3vRsevkvkT7iBr4rqv4phyGGXL3joKUnCUyMY=,iv:bg1dxN9z077KRGsZsBFYbfiKLRVb7mOvsuz6owee4xM=,tag:q7zOqK6ty+Vst2jaCrDrWg==,type:str]
    db-password: ENC[AES256_GCM,data:9F/YlTbfof7JDDQERyc7THdRKVAMw5S2zgLORXE3lNo=,iv:iVw97hbe7bFwwhsGajhjpoAIJkBCY7BKOvpb+cdYaM8=,tag:QKU1PMQ3TovCm/vQL+sHMA==,type:str]
    username: ENC[AES256_GCM,data:D0B31JZ44/Ev8ls=,iv:2TVkmHw+iwkBjI5Dd3rKlV/uEVWSuAqj7rykWrD/mCI=,tag:9SWOXnDbqbLM0sAHT/2s7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0OXR3Yzc1VWoyQ0dLV3ZM
            aGRnbGlzQStsclAxOHJYNTJaV3BBTWQ0QUFJCmhmUnF4MitNNnhzbitNdzlZaUZi
            bWpjRC9tNUhjSGJIbWRyZ3Q2OXl6RkEKLS0tIFY0Q3lOd000ZDJERW1LQjFOeEQ2
            MDFCd3FpbytrcmhwNTlpQ29TL210cEkKFl3H/uEK43J6H+IgWcWl5GRxlIur/Lf9
            nZxCVEUXovc36lo1FVJmfpd6LrbQFCt+8x9pEs9mlB5Jt9mzsSwI8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T11:16:48Z"
    mac: ENC[AES256_GCM,data:C3tdry/KIr4tuQAXcTMjJcsTvjsOALhcvO7z5dQlGVJ9YptJ63AnE+NBrDHLtZWKWODd//wvKCyDa0lRoXJo+G9c8PWaeq2nc7ptHTr4aGjXNg/WOde+RIA4wHnxYdp3kVccuMCAiwVtThfgQGi2w0n3JpU9JrEkjoF6WbE55rE=,iv:d3JH+9OoMbMMJAfkPy40RrXeILJKQDBsP3m9Yxqwe4s=,tag:AQ6VmlP7DIFs5HSzeJp9vQ==,type:str]
    version: 3.13.1
