apiVersion: v1
data:
  config.yml: ENC[AES256_GCM,data:n4IsUK1DTRRUoK1FQLWfWoBNTvF8MC6hOkUsgEGSxoE81fewC6z4U6326xICHSOKnMVA82olhjalKqAdMbeSF5QkH68ke1VKFKltPsqpjSLYWpOw6eDWVX9LY+raoka5I0uztiatGTa2Cvovzr5jrlJTYGuGchq6S0MFWoNjGYxMENJjopjp99i5KXR9uTeZbn8CvXRYkIBfl3r8FwNWOvMJRMIj0hXhD+Qa4fQZnkt+UTZorRqmSawzaIyq1snuH6TVDcyhF2MWxBloSxVEFb4y3/hm106TWZhyFaNX1gfWcFtRXIWQsy8K3rUeli7EHWTik0FyYFDtZd9ppHITqaQzmnRp2ehuIdWXkAV4167zTthKtA8EVUsgH+UiRywHlCJtiQApzfT1GHopEZ9rri0DGLZRQuSfm1dSuW9xBesSmhI+CVGqYmiPPm7o4XZxhbspk8UiN1BZOOxj1qImUsOI8jLQ7n99oIFF8TfGAm73UPTMUyp6PMktz0TZw5tq27ZPrt9WaK7rLZCokzeNTCugMhfTbrXqnXoWS+htR9Md+dJ/ujFjxOMar+QvP8outbFt/PzEPcgMHJSfX+nbFSYjxjMmwiN4VvLC+LUclj2AWYqLCppyA2+QQaJTQjU2UwcxVletZyNG5s+2tIZ8qmoMitHfn1HhIpfZDFOggnF6AzYFhBcXvl806T4a9Up0Af1YPWP754aGrf5SNToKlzUQ4ALN8K9P/4H67vI1LLHCPsCshTZf/Fk1m29d0q4nA4njmyTgtyZTmVDDsiPQEqrA9J0hEmIwb2i1pK6uWBTmZ0Hx4oD71g3uG3vTpAk+x+C+bML9c4Cu/pmkmaqa4wVVRM9LofhJOMoNWb6YVFRkIahHo5xxzmjSWkWDLL3/zctLknOjKr66b1/GTp0V0jZRRuh9j8Pk+ytXmV6aN5e9LNd6dzBCK/MjmOfSwDlf7IzQ0q/X8sij7UVq3KwwpGObkV49BNx0mI4sxHJHS+JVObGUb47uLvOZv/FJVxKetzFwj/63zBI1t/FhrHB49dn49phqjdotbfON6w==,iv:MTxSzFRmC8qeb8TFYwv/miJfsguZBALPFdPHJFed54o=,tag:Ro9csw1Alf5qA4N/Xqy+4Q==,type:str]
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"config.yml":"c2VydmljZToKICBwdWJsaWN1cmw6IGh0dHBzOi8vdmlrdW5qYS54aW5mcmEucnUKICBlbmFibGVyZWdpc3RyYXRpb246IGZhbHNlCmF1dGg6CiAgbG9jYWw6CiAgICAgIGVuYWJsZWQ6IHRydWUKICBvcGVuaWQ6CiAgICAgIGVuYWJsZWQ6IHRydWUKICAgICAgcHJvdmlkZXJzOgogICAgICAgICAgYXV0aGVsaWE6CiAgICAgICAgICAgICAgbmFtZTogIkF1dGhlbGlhIExvZ2luIgogICAgICAgICAgICAgIHVzZXJuYW1lZmFsbGJhY2s6IHRydWUKICAgICAgICAgICAgICBlbWFpbGZhbGxiYWNrOiB0cnVlCiAgICAgICAgICAgICAgYXV0aHVybDogaHR0cHM6Ly9hdXRoLnhpbmZyYS5ydQogICAgICAgICAgICAgIGNsaWVudGlkOiA5R2FIZzlld2VRTjhlZEoxSjRPeDIwNVY1RWtrdFRNOTA3akdqenJiCiAgICAgICAgICAgICAgY2xpZW50c2VjcmV0OiA0SHAyOEI4WGM0TlBSUkZRY2JId2J5OXJSalVaTEJJeE1EdFcwOHFSSkEzWmNzOHEwcFUwTnZnaTRDV2dPNTdJc3Y2VXlBS3l0d2FWaE82RFVWVGpudmtKRzlLejNkRFhzUzJ2OHQ3eno5RDg2SkFGTHNLcHg3RUNaVTh5eG5GZQogICAgICAgICAgICAgIHNjb3BlOiBvcGVuaWQgZW1haWwgcHJvZmlsZQo="},"kind":"Secret","metadata":{"annotations":{},"name":"vikunja-config","namespace":"apps-vikunja"}}

      '
  creationTimestamp: '2026-06-01T10:23:34Z'
  name: vikunja-config
  namespace: apps-vikunja
  resourceVersion: '1831360'
  uid: 63c462d5-669b-4052-9fe7-12711f6f87b8
sops:
  age:
  - enc: '-----BEGIN AGE ENCRYPTED FILE-----

      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYUlSRWxleVJiZEs3Nm0v

      dFRmRklFOW5RMDk2ZFhqYy8wcU5saXdDUzNVClo0NmswbEgvdklBalNsc3ZEaG9t

      NkV3RU5WOTBnSy81b1Fkc05IZHg2b3MKLS0tIDJMUUJxbGZmNVdmdzdnNFNwWU1O

      NmV0N1A4L3lxZ2JKUWFWOXdZZkdYcDgKEHqpGVwnED59Nnvo8RJtpKY1v8KLiUdx

      dJTqSiGHZAHBUHgo3EgfHB/uHdJgAk95rW0ub+KEVuTZCHLZxZ6UZA==

      -----END AGE ENCRYPTED FILE-----

      '
    recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
  encrypted_regex: ^(data|stringData)$
  lastmodified: '2026-06-19T10:57:28Z'
  mac: ENC[AES256_GCM,data:jmMeIWbP4D52aYFbV4gd5srZ9EH/raWqbPZ+JOICbQG+Mai1sw/T3lqcLilbHyB1P7GgWX1rGPaHHclNtAtk0Rjka2Tkgz/ZRWbK+2Ez5LBUXUdBGii2DHF+KTE2bBmV8Qu7PU6jKXBJwkq2Y/GIbI+WGkvW8TLnov2ALCoXQXw=,iv:rmC8fDANft/GoV9sxxQO+JfYBnp70x7Xn9Av8DsHCJA=,tag:W/mvTRJNeZEdsF9UVJrCmg==,type:str]
  version: 3.13.1
type: Opaque
