apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:sRe/9aYEbvIagg13Hc6eqnikwjcYv3P9uQQqfr3ros933a+3sBZWMXeCdm0PFmV831rm0D7rVmoW0ITocAYlp5C9wJUXJ/d/flwQ6guEHl5TwCcs4oQCQXTrlIOWVsLR9b+ob7tUHW9DL4HNvCrI3o1zcmmmwR6kuT3aKZH58ALAYgWL4uVYdGE4Cr92mM/kPGdL4eU4GnMKPdcm69QWc9C4wl48luqOnEQzfh3A97AadPWpZXM455LuuzJq6rnx0ut5W/WYFMZv7UJwT8R/wAjpBZSAwaulamtqOvguPYfRQF/kStkOnFvGRvBhV5eUFJyCxCeCWvz9VjYqpzj09eutrN8jsuG6pg8YFN34GE+e+UNbNfMl6Vqb4mTAFkhz8BVXifiYRW2rocS8GdQGeKJ7ZZ7E2tsHcVT82a6cCVFldMBgTILC3hhqMf1dwKyBmmLzm22iN66hh9PnIgBkaw0cjx9xdauvMUSkAOUGldI0dzAwd60dgGQzmhlEui7aW3p3THLwo6mjQiSQ/AeM18uOw4Xnmsg6DhkRaHFhFQdGJDNo9fc6/OJYLqEkFZcYsoSCqItVYTspEaX7bqSD8MGo371IWo3QCBMtXki5emnHXzQOktegPZoP2FLHFpDgcFcohIV1xq/Nyqji4UeEepcmoHs7DVbsqDjW2W8aQdpw6qwAZzJQNmtsPZUOHKT3DrEGsMN5/+1KTyaMtUm9Dg3b1glc54+B/iVcL46zB10WJLyW+cqWQ0DXnFWaRTANAzJl+irRBS3D8s7JJh9O9RbNfwer4db2AWcMUtMfZ8QsFEWmdFeRj/TgdrW/q8SeBwFfyUaLUjSveGUqfr7qSBXBQQkhu3NJo4jpMzkSDWCHMruQx7dA63gWKgpvhEACj/8AeCBV4rD1g3SIwz2F6hhpYltj7n0XCPSCyLOgHQQpVeK2/kKSnYVC5Qns1N+2Xy4x9r/2IBaRQwK53k5LWEOW5gr5LpOJ9PskqVL1mWijrR4woVA3IXgd8K6k3Mx4fcXNSg1jSp0MeCLXSCKKJg4u0TmWGcsp0JwmKg==,iv:jxYUeo+z9hMl0kodADkokh9YoITumSBRS4sXkT9fExg=,tag:JpN7+KY74IQJao1yvVFTkg==,type:str]
kind: Secret
metadata:
    name: vikunja-config
    namespace: apps-vikunja
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaEtoYzZmK1g2ZWpsdGVv
            QlE5OVd6Ync4VG50SlpIYzZTcTJweGtGZmtVCnA3RGtSR2x5RWluUlhweG9iT2Jx
            WGVWajR6eGdOSVJyU1JvMzdDSm16QTgKLS0tIFdISThDZEV6bFV4NmJJbitNem01
            NHBJa1ZMTlBPZkp2VXNNTDhBM0hRRkUKYygh1njMylzu9VcTmJC3BeLXIG4bmH8+
            Is9GrjqUU4fuQ+vzZkEUITpvvBXEcDo8GX1uKsiLzDeWbCNjNWjjRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:01:33Z"
    mac: ENC[AES256_GCM,data:JfIUM0YXRznSJHHU8X3X9/ln3IPnDmL2IYCVAITJr9uPdSnXQ5uOs974HqxMP4clHOP+qcGe6kHCZtlc+exqB1gctoue76aQhKvnyfHujSAdGDpR20sBsHrGChRYPRIuADfcGL0hliUHvlVWC73CZtmk4Jtbri7bYTsg8w2NmwY=,iv:lO9nmnyESd03nZ7Mk/QSJvJHLGYbXgGfv3SUx7ly6Lc=,tag:4YnTLyWyWJmTQ8zCMne+Gg==,type:str]
    version: 3.13.1
