---
apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:5zUvVQV2r2jRhkqNcLbvlPB3PxGLAMmFOwSWJG/Yz49Edk/6GDN9eeCr0i2uik7mcTgiX2dcJU7liVC63M27uh+9UaSwJVS7OXqOAoTugb8MLB0CdLDMVKECBhwt5/UEgeJKAAY7T0CXFpDcnwQ3vwP12hf24l1KlctN3645cSEr7f+Oh4uLh3pIuPJkwO/REIdZ+q4icAhbLijx7jYE7hh4LEKy2SIo/71vSWnTICz50ac1qRsm7TJGijIl1Usk4DXPysCEuibsZHoi+h6fCEKB2U4kS3vQ3iwAQknQHJqocWbDH79r2mAxSxXQ5PgTrvnlYDLDJiuJousQ8wBOHsGnaW8c+4RQBk66d6KN1B778ZypQyJkwC3xg0a+CdHM14TsKXe9WelbLqnSkSCWKmfBGXv/4zfSGbBs83rYgONWZ/TCmMmG1DHa4WBTfws6H+VjFw6tIw8XXa2i0phz63bk89txVpDiMwZ6m44LNa2T9EyfYO6gNt3G8enYZh/D/+aR8o8F/JW0uK3vl8KU2IY6+cUQ311l88uGzASYR0LHsLAG5NKc9PiYliCtW5gjAXiKiBog7RGKr7LnzFO3LSNSwQ+m7iYWLt7Z6bFPXcT28WSo0WNal9yPpVld2BVykRW5edratW9kLNg6xesx1rp5lDr5liWVCefAX+f8jOOS5gGFGKYcaz0jZcNjBHt+yUR6BWGnyFW+9wp5glii8JbVXuTKl/NvOWr8rbcAWPYurXWJ/oouneQZbLg2c5BgKtPWktM7KYfRLnkD9XEyYlnebkk9rZcQCbWM9n+Q+W/v9NwYBUFYmJLN2mHZiv8DCWM6PlXfNoOWv+6f5tDlVVWdj4aNfzWvdL/VEoEr12IDjjkuLI473PWleiE7G4Ve0BOG+6fci9Zi/HSrU3aoiV+099aBpgvB8WwSYxiKMAVqyJEKqBmIdN7EEe+xwtmWoNisUQcqHA70+NxEzR0uwni64QTjgiXx7VEbVTjW9ZpdjTPI49Cixb4cz5nqDbbLXqGsn7XMxGjLFEG6M7qfRC/J81MaPdMw3VZBJA==,iv:303j2cdlpIkK71m/Gk1ECqTM/Rmc7OmNEwZQ4kx88c8=,tag:K/3lwALrRznarYaCM4obZw==,type:str]
kind: Secret
metadata:
    name: vikunja-config
    namespace: apps-vikunja
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMXdvS3JEU2I4RDF0MERI
            R2ZVTlczTzRsanJqMDd4VFdtU2daV2Q0RXlrCmJkV0o2dzhEZ1dEYnh5dVl4aXoz
            c1ozM3A4NlhDdjgzZDJnVjYyaERjQWcKLS0tIFpiSzhOalh1K0FmZXhESWprZGk3
            azJPRi84UU4xQTFXSWtLRDFGKzNVQTAKlp2SsrnJOvtQvGF7Kf0VyDAgZMJHV/oB
            luzD139MLi8l6jNGojEZUmnioJGMFcf076+fnpCTMmaErmHaA7QfiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:23:00Z"
    mac: ENC[AES256_GCM,data:wxKURCtEbNBXE5nXXZTQq0XetLWtyCqd3r8muVz6lpAsWTYrEGSilC9JJbu+M207v3Fzy77v8QUAXO87PknsTsvfXek1qGrUgznvmCaxkELAzhzAQPdU/vR0/CkdXqjC6DnGTY3DRavyP3GHi6YTPIandquXnLGG2Buv81gbyYM=,iv:oeyoBuA3lg7ps0nVfqGjcQmsEX9OgvjtqAmHgH0j9Sw=,tag:qYV4L5R5nJhrq9X/yMM1bg==,type:str]
    version: 3.13.1
