apiVersion: v1
kind: Secret
metadata:
    annotations: {}
    name: zot-secret-external
    namespace: developer-tools
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:GftLS5Tjzo90e/lukEZgZY/LtlxvtETsaLE8Hb8aXgXHLxAn+QY9jaozBnyjr5E8l89JcVExbsCZHIKSbTECrN9qVkMHeZ9rVDtlN+JwZODawaWXMljq9rIKyerWggLE2riQhuIPCpfcRWM/7DHhEQ3+PVBR8ES8unHU81fR4EFfq/Q3o6ViPndlrn4=,iv:Oh0dR7lzCXRw/Uc4xHixSbcCPIQ/wM+gToBkH74DmPU=,tag:6plP4eC8OnSYgn0htc5PdA==,type:str]
    sync-auth.json: ENC[AES256_GCM,data:v1I=,iv:BZGU9e6yz7TWyvXKUR4LD/LqxUH8AYixeW56rDnR3YI=,tag:MU4P1itLyoHsLz0fggf/ng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRU5pbEFYQ25STUV2Y1Vu
            M2xiNUNLUlJaa1Ftd1JWRkJZL1c5a3V0cWpzCmpQUmtueUpPVDZTUzZJd2ptd1Vo
            NytVNlh2NVVQTVNvUnRMcWJCbEV0NFUKLS0tIFN3S0FISlR5bG1vRERVYzV5L3Rh
            c2NUbU03dkJKMThabHc4MlJUeWNvZmMKogg++R/+znGXHGuLsLDxi91QufqNec7c
            GvlTZuKb8ERKjp5Za3z3c5/9RTMz/cOXwswGni5EarDSMfgMzyB55g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T10:42:24Z"
    mac: ENC[AES256_GCM,data:Z/hTFWFMtAcJiSgnewe/rblrU0dFrzxIn0GX+4hANDJxn3KuAJl5b6IMm269eBDL/CYjt6JPLlECpdXGti1JCFfRjHWuU49AGurn6KxjCU517IiKDkYY5tQoINGMzZZUfRQDb0BeDAWyiYXHCFm6dHEf1V9Y+RCzzFzadBT1WRo=,iv:0TeWwj5Gz+GKCMbp95Yhm9byOlsRiKdmqErdmPyzVdM=,tag:dkBLeWvQt1xcKxbZQQVZAQ==,type:str]
    version: 3.13.2
