apiVersion: v1
data:
    password: ENC[AES256_GCM,data:9UQG+fIwTjwI9dzRH7MiGSi/hgclF5p609WljHKRjKs=,iv:nZkhBmGAwweMyfTGOklyzIzx6j/2lsLx1GF/mEKbq/U=,tag:lqbY21BT/tFT9ObQ7gZ+3w==,type:str]
    username: ENC[AES256_GCM,data:RDJV0lMwVi4B2U8Gyxsjrw==,iv:L2zJMyhxARCckhFeNAD7gnqVYbC2y958BILPMPXF9KU=,tag:qA++bnWhN4cOoK7o5hPtrQ==,type:str]
kind: Secret
metadata:
    name: zot-metrics-basic-auth
    namespace: apps-zot
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOUg5RmhacGUrQ1pYRjNk
            aG85a2tRZTAxdUwzeHRsaVpxbFVseHRVSXljCnZjZDVMR3JUVXREZVZtMEZCZktW
            NkpvU2Q5NmgyaUVBR1IzTXdibzlrT1EKLS0tIDZNWmUxWEM4ZDlhYTF2YXVnUDIr
            V0Zwdlc1SDV4ZFhxWHZJTGcydDNhL28KwW94JNtJsjxlvzHTKdVuUpQHvJSF0Gvx
            yKH4bpGE/CQ+LxGfvz3yPQ7ybpxlr3ka2zLcrimLrMl9DqohCzuVKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:01:35Z"
    mac: ENC[AES256_GCM,data:Rkc7eKKVEotOzcNuAFgOf2rdj6qe41y68WgMTXjqEXGqj+Bdz3mI7wyodKtzbnld2oKSiPRoui6CBrczBkqBBuv37ZKWBkR/Ci2inHRGEzsYFq77PDYrLpSrT3TLvbK4D1nTeSeK8aNfrhzKm/K75Ew8nEcjpozV75PUZeWNCXg=,iv:mraSn6CmmxGwj6FHbjEpHsUwGo72lRtI2/uzcg4lcJo=,tag:jApDaYko/K02PSl3a6pwpQ==,type:str]
    version: 3.13.1
