apiVersion: v1
data:
    config-ldap-credentials.json: ENC[AES256_GCM,data:/WCbOXDR4M0jyzHJDgBkPbaX8lx3kAxZ0YB/C567QoLakCzyHW18ng2H/d6+Q3Q1IphursL9Cpib1GN5qweHbhb5fs+iOOxnm2axbUmDPOMWPOY4uD3qbQ0us/T76mZlzmNSAaWJaGpNNgxrV8PyoIMHlJczz7iQE7+6BVuWMX4JuRMn5dS/sA==,iv:JdSrbHc9bKTxQgt4TktSDP4r7xpLfjZIGaoy9BQCFk4=,tag:zoUFjmhvQPE9MBlX1o8FbQ==,type:str]
kind: Secret
metadata:
    name: zot-ldap
    namespace: apps-zot
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVDFoUUE3ZVpyNFFmRDdy
            dUNycXB2M3FxOElZRGJ1dHd6LzRxWGtJb25RCnN5dVNralo2TTNSN0wvbkZ4V1pO
            U2Y0ZTVUNjBzN1lPMmF5TXdtMFBIbFkKLS0tIFRmNkhWNjFySUIzK3VWbmhZQjhX
            UGpLSFlHSUhzcThUc1pYUnZGZTdla0kKoLos8JGqt4o+ypDTdjHNAogAnL22evxY
            ZFJLfU2FJok3u11rFYe1rOrqaZ3kT21icBQC1k8VGEvuKSVuIaNeBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:23:00Z"
    mac: ENC[AES256_GCM,data:0gEANU3YCvdQVoYpqCagX6WMJTXZT/uHFX7IhxC+ry9q05ONPXtQIo//jCUo2z1rTr8d89wJ8ddCAflzFuDLcCSi7R8R/PulzjV99lLqvI7eMpFyfyhrN7VrNU8d2nLXPFkMOTKaqj1+mSuA45w4is0jXa3eDbADf839gu9xbRs=,iv:w7H5ds2iZwT7p4oEnvlXE2iSDMoucefn90lIzTXB/n4=,tag:7i0RwUR30FLnFJVvAdhK8A==,type:str]
    version: 3.13.1
