apiVersion: v1
kind: Secret
metadata:
    annotations: {}
    name: zot-ldap
    namespace: developer-tools
type: Opaque
stringData:
    config-ldap-credentials.json: ENC[AES256_GCM,data:EwXADcVViusgCg3sz/fAxYB5S4W2b5JnU4Lsu/elacZ3/h5UkY/8+hWM/REVLAy0kZlp+HXmwKaVUMVF6ATz1ElySi9NBcJQY0fjXKmi8F9iURe8+9Nz8MbMvm1OzKOmDdmMTSA=,iv:J9H1oolx8ernhET/3s2UfbtL0OSDXCUDdjBUGFp542g=,tag:XAYVM+AJ4xkIPPWK0PWoJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Y05uZldDS3cwVkl3S0JE
            ZUE5TDBKOE9lQUhmQW4vUk91ZVZra3Vrdms0CldFSCt4dXFVVUc0ODk2Sm9yNFg1
            QnM5eWhiL0FTeHlUTnowc3FLSVBBRVEKLS0tIEM0Z0QxMnVmSzN2Q2hoVDJ0ZG52
            YWxWOXdjSzVhL2sxZzhWUGwwMkVBUmMKBsYeQQolQCrgmJZHbEWmEEE71oF/cMtJ
            oYRY+uia3KDl61HOp4BWNrKiiT5CPagYWM4aQ4j7PNtw26e2QTz+rg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T10:42:23Z"
    mac: ENC[AES256_GCM,data:PqY7MXEFJMrBX7/7zFnuGOOPHcDvCqTe6/U9VaOVPHcxL35w/T4wooEKR5EzJXI/SZ0SDuC0w1dNFBFwRjo1ksEe03Z6EE5PHTRIBm8nS5Ta07oZREgKImyFUePPDAbEus4swiHvsCi3YwiC/99Pkkk2zOxQ+K+GEw8mzlU7jtI=,iv:Tx+ns22LYy0tMJDw/Qp2UH3ZUZVtoRa/mVqKTyr0BpU=,tag:AUyTFijO6KWUkcyD/34ObQ==,type:str]
    version: 3.13.2
