apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:W8D5nU7IBhQUYHbrHbyXQjx3O6B57VnAgE36iwEsckvp4DWsvEEuMUqZqfjkAVxLAez7Yuob+ewNaXy5uJOrv10Fc+9dsS9lQGdbaeQMmtDsavmKuzzbFvL4IGkJoVbn89aQ5U3frNkcUlCCJDre8lf5GNWMsqhacgNwEzJdJQRwCp/IxxajzpLlVEp81fiBIvAFMxdtIyvcCxma0AKYPCp6cd5ROA76krB36URMCfRlNFjAmdl94pDxP7z12iV5QHteiLfKRoZePTl/tpsQRE2VXm5AfgPBQV1dexUVh62syDRd+XxLKWwTGRw=,iv:UB8aGkL4qrT/RKXxQ4ZYfM/eE2vpLv5yy95TJu44BgM=,tag:oGsjbnAem6Q3Zh5J8/lKxA==,type:str]
kind: Secret
metadata:
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: apps,developer-tools,monitoring,security
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: apps,developer-tools,monitoring,security
    name: zot-reader
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQzdZTjdBZTR6b3llN0Jq
            QkRqU041Zlg2S0ZMQ0lxRW9pR0VETmZvL2pZCnpVZG0yZUtBSldJeHJXbjBmNFRI
            SVZ4YUdHVmxFcEc2aDZaTHZPNlNuQmsKLS0tIGFBcURBUE11NGk0cnFMTEdiTXJR
            RkN3bysvd1VpRUxaOFM3bzM0KzRUWFkKdD4oTt89fq0dK5i1iEPQWjwhogq2b5jS
            kfCzs9rxn8VsBrDxXxUQBf5xUMdV/AFECDRUJ/ar1feBSu+3V4eBAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-13T11:22:00Z"
    mac: ENC[AES256_GCM,data:VxdD9GMbpB9MVSSTmVRFn4vxsiNdGnwh6qszaDFT0E5GCkwyKEYAFN1vy6i48xcqLSLP+thFB1q/UNG3kf+C/QpQ+RVUiToZztOiM23slpx6fG596l3DqcJ4CaPvdqOdIv/VumPgoRhNCYA3ArCPi3H/+cql+UfH9TQruu9olko=,iv:iKGIRPlN7lGeWVy+EuM6rfx0IZi5vg1r8nH4uVNPPkw=,tag:pmcPupEyzmA8LJSsokeUAA==,type:str]
    version: 3.13.3
