apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:1vX0qA7yQU4A4fVezFpBIC4lxNZkosplpl5lHI/IvRuh1+RPtoYLPIAegc0qCkVM0///xL/6tZC6fBZ31tw6y4dOxpn2575w4ZP8FZd20KkeztIRXyiZ7YJcsl0qaPHnBgXE9k3L1u9uWiac9nJhhqgnyoJ4mYIRG+G+jzN0bjcbRqi1Cy5aMDFYrIz8LlO6cgmM1P6A1Ib2Lj5EwewTR9Vpn5j8cvb7GC/+NpdgxT24N06DstWX2NNU3A0+B2LKa+wxoGXLf9txkff3TR9GeOoxN4cXt98DKYa9lFLJv2ftfXvwbhyviXeuN60=,iv:tVJeO0ykIcnw7xU3kPfK6UKUEQ0I5+oNWRUQmELobFo=,tag:K3QwanjqfT7pou0serMaDA==,type:str]
kind: Secret
metadata:
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: apps
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: apps
    name: zot-reader
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUnFURTZtdDg2ZTFBR2k1
            SWxtNG5HWk9WeDY1NExzSXY5bkNWS0pWeEQ0Ck4xZERMUU1BMld4Nk9kT3I3M2ZD
            d0dOUU9xVUExVHJ5N1p3Vmp5Unk2eTgKLS0tIDdPaHlzc0crSndMY3U4Z05PemtY
            VCttcUlERytFSEt6UldoK1VEOFp0ZzAKc3uIncZ+818m3qujKomC4SnbCkLRLbsS
            WLCxuVyrpq1b90hNzATukvO++MiH8dy/x5aibJjVO3G5r8LyqXHTlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T05:38:59Z"
    mac: ENC[AES256_GCM,data:7AUinqZbCpOgSUtl/YOVGgbrhG3c9uW4i9TOgzgftwUuHYDr506D0Yj5BsyKsx7mDaPKGkL8g7kveotwuGSTWGj7+ifoe0+CuMmeXIiA26k3fs7U0Ew+2rhYwbwjStWsvBTRgmokhOQl7k/s3CHDRAoiJFC67sw05Z/yV102Ad0=,iv:dzebDGKlZ71FmId8pWLzkyT2xbO1DgDMZL3nAN7uQFc=,tag:mpGpPrWAFP5kkXIXLzFXwA==,type:str]
    version: 3.13.3
