apiVersion: v1
kind: Secret
metadata:
    annotations: {}
    name: zot-metrics-basic-auth
    namespace: developer-tools
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:P/2nr+cT6U2u1nUxowKAP2koK/r3DIA6,iv:70j186yPPtkmEbYcHdeIjJaS8/6YqR8VogiVFNVeDd8=,tag:CANbUAOK0HhI7MHxBxpfKA==,type:str]
    username: ENC[AES256_GCM,data:AKU9paOsOn3zYQ==,iv:3LoOfyTMje/fIX3USr0f8Xl0CIK7yG2jC/1WLDX6XcE=,tag:kbUJQSk7ffAj+DjUiuKKzw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVHZvMW5XK3hIQXVBd0o1
            cUcwN0JERGhqK0lDaUVUZWs3SzVPSzhTZTE0CnB3ZEJ1UERhWG90bVBLdmMvNEJG
            R3dnZWRPMllmdFVZSTNZWi9lTGVCVDgKLS0tIE5ENHZKZmdqbXdhK1BiTHF3Vmkw
            bHhtME13T1ZrQUtySW5wazBLV3A1WHMKwCZRVjrY5/w5vHhIKwklciDWtEcgnfTl
            BMCU0kPKgymIjCe11NYEGOjCfQg8eTtf5Hzba10qqbBzHq8CouwWWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T10:42:24Z"
    mac: ENC[AES256_GCM,data:TmdZZHwQ2KYDOM6o92fKwcF2Tqp3iB23dq+mDqroDOII4cNAZQGxhglvDm9Ugia2+UGq29FbNoAAgUwRKaJCeVsWEaG9EnL62ZytXviDsrYj6ra33bnT3ZtP9DPYn3zfAcdXqZ9mpm0VWkM6cPts9+0X78rM3PAQTxm5C6qbKCA=,iv:jq0Vd0bSZWc+chXsDxPdM1SQLne3+5ITlBkz6KUWhZY=,tag:pqTj59yx3Escz6VJ2qGt9A==,type:str]
    version: 3.13.2
