apiVersion: v1
kind: Secret
metadata:
    name: zot-secret-external
    namespace: apps-zot
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:8r68bjkcDFRGc8SC+Nt09Tbac3d6HyOQwPCxS+ATdepJOcKPtOf2aQ4EE+qKMg0+iVVlbjiL27sWxVoeeTnY6AeOJ7ZxE2ZqFVFc5yX7CdUzy8FNht61V0cjNu+KPQtA7pnymZUHAdicAYAAp233Lal0OJoUJToAf3Qi6RdUPvRdEZzj5bRaXWGsq5Q=,iv:rUBaOdsKtmvNWfSmv7kXEBnPfeSApRKFq5kvX1rEpHs=,tag:zJR7eMowpnzx7WpHGbLrog==,type:str]
    sync-auth.json: ENC[AES256_GCM,data:THc=,iv:ItYcbcATUOUa/FoCwKp8zZUKpM7scPufHPX4cQ/m2CQ=,tag:YI6PwkVUaskSddoW4fEftA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaK2NCK2syTU8yWjliV0RH
            d1NnbU8xZ0o4NS91Q1YvYkNWd1c4Y1BQbGtZCnBRZVRwRjE4UFQ0UFgrd1puWHJZ
            ZnY3SW5nUW1iUlkwNWN1QUpPQzNCajgKLS0tIFJIVkdwNitSaTk2aFkvbThPeWNh
            cVY1SzJQV3hCTWExRXBlTnNucXptSlUKUa7+OCBSvCD9eS2f7odQOTCLKmPZcer8
            z4AKf8NcGNzYd+hwc9rrYQ8kUTZhpP9SsbNEyuCR+9Ndwb0l36LUSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T18:29:08Z"
    mac: ENC[AES256_GCM,data:kq7Ioh6VTsomnyPvGyXztrdA/syqBgawtruxZwmbwzfLcBbNuGniXmjLKsLVMNxVIStCqmqjwrGe20VhIiqeF5gehgkgE5+fctNaz52/5v+MazyXTBap13e+NXfidpu1RFFUgo48Hu9VjHXKnNc2UjwuCZTNMR+PMgYSHkHYc3k=,iv:brH3sOs+WTwf5cmH+v1VrpRJIHSOOGcqrDuU5Ir/DnQ=,tag:LnXK0K28a3HE5i1xzaBPzw==,type:str]
    version: 3.13.1
