apiVersion: v1
kind: Secret
metadata:
    name: zot-reader
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: apps
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: apps
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:/i4cmxCZcx3cmfdgpT200ujDqjqKpBvKlnCh9NTwLBMw2HrQGeLakxiLPCdRck3aOAtu6CIXi8czO8G1dLt/T7tm2sxGdcYhB7LKI/wyl/BQZEzH66qWkK5NO5IaZCeyfICKrEnWXmfEj8SXiIkSq9SRwhfkH8NSJooEROb6WqpBP7LihgWQU33m+xjjWptw8XMXOY0Wh9CqZbdOPSLy8X64iACC7+eBRef73uHRJLJc8rm+zPua039+i9/z+8PpPCRs+Ixb1Zv94y3iPabfwP/cFy8obMLwOPD8W+s5Du633cYl/C5HSBsc/d0rsXucAyJ87g==,iv:W3hISZHvJ06fN6D4VeoDY33NB1qTUa9dzmq6WWO0Q3A=,tag:VEJ7PYqnVs/sWSVdpIQjeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUDQ4dy9oYzQ2d21PbU9j
            NGczdDJNMTlwcXJBdExXbDNpOVFZRldZb3prClNTaktXdWlDNVJmNmdDWk4yVVpk
            Tmt0cWhDVWcxMkVqWVNOcXo5eC9XdzgKLS0tIG5iWnZvZllkZ1cyRTBsRjM4SVly
            MXQ1c1V5V1JZejVZdXAyWWQvd2tVaEEKICJ+aTuZRFuhrdTA+hDXpVoRfIpCbNvv
            wnqrzTQXdYxlVjgb4jyzhwOxf6MJUem/rrodS+kHGWzINg94sYJ/lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T15:48:17Z"
    mac: ENC[AES256_GCM,data:Xs2tQnoE9Vaxb7zebtugU2wG7Y7xPZyklAGHyzOFN03SBOVW1x1hd4lLKBNMujdR0n06it1xHh/3kjRz0/thQdvsEmdSvB2iczs/vJ2qK8spPOtZlRfEDv5GMf9XpkGFQl206yL299Vl3ameEh2qoI3CNys5c3VFM7shCiiJE0M=,iv:CP2tsnE4Inr4Pt3kdyJYeGFyhdf2lpjWMXeWqMH8q5I=,tag:6OZ/5dJL8CLSb1snQaFcLg==,type:str]
    version: 3.13.3
