apiVersion: v1
kind: Secret
metadata:
    name: zot-metrics-basic-auth
    namespace: developer-tools
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:iTVbWV0Ngw0e7bkan5sp8w7q7TCZVxya,iv:i4cX2iMv4PupeJ/l2NVRLg9Ikq1+iRsAvwYxVamSTNc=,tag:wGEMjU9hxuZ1iB8yj+Mcgg==,type:str]
    username: ENC[AES256_GCM,data:fThwVHOxOTQ71g==,iv:rAdpk3YcuOu2uCEmmrdEAaydG4+4S7/Ebmkj3THFYGQ=,tag:Ken1gIbP+0lNpDGD8YWC5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWEIrY21qY3N2U1lEV2lz
            MFJXZlZvQnE3WGVjaUN4TW52ZFdreGpTMDF3CmhUQVowQkpwd3ZBVDNKMzJSd2xO
            THpZSFBKVEduZFdCNUpTWnNUTkkvWGMKLS0tIGx1dDgzdkwxZzh0Y1ZpaGZuTnhv
            bnZvdzJqcVM3WlhJNldkdVp0dk1Wb3cKRuIIy4KFvSFDYzeo7ME+q8oVFqVfuiJG
            SG5SUWPfvq3Hc7WnzwCsLBipEcrc5eof+Hy4z9pPBKy78CpMPb3Lxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xtaan5pavyap70dhgj3n34grsjqcwt66rhsrcfk3dcp04l47sassanmyk0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T10:00:31Z"
    mac: ENC[AES256_GCM,data:OtduMSmu3gQs8JT713/XjN2eCWEX0R9qXIr0B2sc416em3diHXGn9CHpQHVNR/DqVVnotKXFDQD3cDKQ5VGGLXAnAiDqBGHArCrpSLViy/vZ650fvmZqp8ih4BP3HE7ub1CX5faee5HW3KQ91+aHd4Eh2IsnCGeTwfXabF9DCFw=,iv:Tpp9hUjMjLu9QUpRmGrt653pcnzRP/5qeATAEzsVaBI=,tag:Uqt5chjlr7vwqhUdm7keNA==,type:str]
    version: 3.13.2
