crds:
  enabled: true

extraEnv:
  - name: TZ
    value: Asia/Novosibirsk
  - name: GODEBUG
    value: http2client=0

cainjector:
  extraEnv:
    - name: TZ
      value: Asia/Novosibirsk

webhook:
  extraEnv:
    - name: TZ
      value: Asia/Novosibirsk
