---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-xinfra-ru
  namespace: networking
spec:
  secretName: wildcard-xinfra-ru-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "networking,monitoring,apps-.*,flux-system,longhorn-system"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "networking,monitoring,apps-.*,flux-system,longhorn-system"
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - xinfra.ru
    - "*.xinfra.ru"
