---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps-charts-source.yaml
- emberstack-helm.yaml
- project-zot-helm.yaml
- crowdsec-helm.yaml
- vikunja-helm.yaml
- vaultwarden-helm.yaml
- kube-prometheus-stack-helm.yaml
- mailu-helm.yaml
- rm3l-adguard-home-helm.yaml
- excalidraw-helm.yaml
- longhorn-helm.yaml
