---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  url: https://github.com/longhorn/charts.git
  ref:
    tag: v1.12.0
