---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m0s
  type: oci
  url: oci://zot.xinfra.ru/charts
  secretRef:
    name: zot
