---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: rm3l
  namespace: flux-system
spec:
  interval: 1h
  type: oci
  url: oci://zot.xinfra.ru/charts
  secretRef:
    name: zot
