---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: twitch-sub-bot
  namespace: flux-system
spec:
  image: ghcr.io/nikmosi/twitch-sub-check
  interval: 5m
  secretRef:
    name: zot
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: twitch-sub-bot
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: twitch-sub-bot
  filterTags:
    pattern: "^v(?P<semver>.*)"
  policy:
    semver:
      range: ">=0.2.0 <1.0.0"
---
# 3. Автоматический коммит в Git
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcd@xinfra.ru
        name: fluxcdbot
      messageTemplate: "chroma(ci): update image tags [bot]"
    push:
      branch: main
  update:
    path: ./clusters/my-cluster/releases/apps
    strategy: Setters
