---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: k8s-lb-pool
spec:
  blocks:
    - cidr: 10.10.0.0/24
  disabled: false
---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: Service
      selector: {}
      service:
        addresses:
          - LoadBalancerIP
---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer-config
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
    connectRetryTimeSeconds: 120
  ebgpMultihop: 2
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: bgp
---
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
    - name: instance-64513
      localASN: 64513
      peers:
        - name: openwrt
          peerAddress: 192.168.3.1
          peerASN: 64512
          peerConfigRef:
            name: cilium-peer-config
