apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: mtls-strict
  namespace: networking
spec:
  clientAuth:
    clientAuthType: RequireAndVerifyClientCert
    secretNames:
      - homelab-ca-secret
