---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps-adguard.yaml
- apps-authelia.yaml
# - apps-docs.yaml
- apps-forgejo.yaml
- apps-forgejo-runner.yaml
- apps-gickup.yaml
- apps-goldilocks.yaml
- apps-kube-prometheus-stack.yaml
- apps-lldap.yaml
# - apps-mealie.yaml
- apps-noise.yaml
- apps-ntfy.yaml
# - apps-twitch-sub-bot.yaml
- apps-warden.yaml
# - apps-zipline.yaml
- apps-zot.yaml
- cert-manager.yaml
- reflector.yaml
- crowdsec.yaml
# - gitlab-runner.yaml
- monitoring.yaml
# - trivy-system.yaml
- goldilocks-middleware.yaml
- apps-supersync.yaml
- longhorn-system.yaml
- longhorn-system-middleware.yaml
- database.yaml
- apps-pgadmin.yaml
- pgadmin-middleware.yaml
- twitch-sub-bot.yaml
