---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: networking
  labels:
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    pod-security.kubernetes.io/enforce: restricted
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: monitoring
#   labels:
#     pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: database
#   labels:
#     pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: developer-tools
  labels:
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: ci-runners
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    pod-security.kubernetes.io/enforce: restricted


# ========================================================================
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-forgejo
  labels:
    name: apps-forgejo
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-ntfy
  labels:
    name: apps-ntfy
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-supersync
  labels:
    name: apps-supersync
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-zot
  labels:
    name: apps-zot
---
apiVersion: v1
kind: Namespace
metadata:
  name: crowdsec
  labels:
    name: crowdsec
---
apiVersion: v1
kind: Namespace
metadata:
  name: forgesync
  labels:
    name: forgesync
