apiVersion: v1
kind: Namespace
metadata:
  name: networking
  labels:
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    pod-security.kubernetes.io/enforce: restricted
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: monitoring
#   labels:
#     pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: database
#   labels:
#     pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: developer-tools
  labels:
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: ci-runners
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    pod-security.kubernetes.io/enforce: restricted


# ========================================================================
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-adguard
  labels:
    name: apps-adguard
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-authelia
  labels:
    name: apps-authelia
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-forgejo
  labels:
    name: apps-forgejo
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-forgejo-runner
  labels:
    name: apps-forgejo-runner
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-gickup
  labels:
    name: apps-gickup
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-goldilocks
  labels:
    name: apps-goldilocks
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-kube-prometheus-stack
  labels:
    name: apps-kube-prometheus-stack
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-lldap
  labels:
    name: apps-lldap
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-noise
  labels:
    name: apps-noise
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-ntfy
  labels:
    name: apps-ntfy
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-pgadmin
  labels:
    name: apps-pgadmin
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-supersync
  labels:
    name: apps-supersync
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-warden
  labels:
    name: apps-warden
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-zot
  labels:
    name: apps-zot
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: crowdsec
  labels:
    name: crowdsec
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
---
apiVersion: v1
kind: Namespace
metadata:
  name: forgesync
  labels:
    name: forgesync
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: proxy
  labels:
    name: proxy
---
apiVersion: v1
kind: Namespace
metadata:
  name: reflector
  labels:
    name: reflector
---
apiVersion: v1
kind: Namespace
metadata:
  name: twitch-sub-bot
  labels:
    name: twitch-sub-bot
